// SSF-IMS grouped navigation (sidebar). English + Hindi labels via i18n keys.
// `resource` present => opens the generic resource browser; `path` => custom page.

export const NAV = [
  {
    group: 'main', items: [
      { key: 'main_dashboard', icon: 'LayoutDashboard', path: '/ims' },
      { key: 'global_search', icon: 'Search', path: '/ims/search' },
      { key: 'notifications', icon: 'Bell', path: '/ims/notifications' },
      { key: 'learning_certificates', icon: 'Award', path: '/ims/learning-certificates' },
    ],
  },
  {
    group: 'organisation', items: [
      { key: 'organisation_dashboard', icon: 'LayoutDashboard', path: '/ims/sections/organisation' },
      { key: 'org_profile', icon: 'Building2', path: '/ims/org-profile' },
      { key: 'membership_contributions', icon: 'Coins', path: '/ims/membership-contributions', resource: 'membershipContributions' },
      { key: 'appointment_letters', icon: 'Mail', path: '/ims/appointment-letters', resource: 'appointmentLetters' },
      { key: 'official_documents', icon: 'FileCheck2', path: '/ims/official-documents', resource: 'officialDocuments' },
      { key: 'donor_slips', icon: 'Receipt', path: '/ims/donor-slips', resource: 'donorSlips' },
      { key: 'separations', icon: 'UserMinus', path: '/ims/separations', resource: 'separations' },
      { key: 'constitution', icon: 'ScrollText', path: '/ims/constitution' },
      { key: 'governanceRules', icon: 'Scale', resource: 'governanceRules' },
      { key: 'registers_required', icon: 'BookMarked', path: '/ims/registers' },
      { key: 'policies', icon: 'FileText', path: '/ims/policies', resource: 'policies' },
      { key: 'office_history', icon: 'History', path: '/ims/history', resource: 'officeHistory' },
    ],
  },
  {
    group: 'governance', items: [
      { key: 'governance_dashboard', icon: 'LayoutDashboard', path: '/ims/sections/governance' },
      { key: 'persons', icon: 'UserRound', resource: 'persons' },
      { key: 'members', icon: 'IdCard', path: '/ims/members', resource: 'members' },
      { key: 'managing_committee', icon: 'UserTie', path: '/ims/managing-committee', resource: 'managingCommittee' },
      { key: 'committee', icon: 'Users', resource: 'committeeMembers' },
      { key: 'committees', icon: 'Landmark', resource: 'committees' },
      { key: 'meetings', icon: 'CalendarClock', path: '/ims/meetings', resource: 'meetings' },
      { key: 'resolutions', icon: 'Gavel', resource: 'resolutions' },
      { key: 'actions', icon: 'ListChecks', resource: 'actions' },
      { key: 'notices_cases', icon: 'AlertTriangle', path: '/ims/cases', resource: 'cases' },
    ],
  },
  {
    group: 'programmes', items: [
      { key: 'programmes_dashboard', icon: 'LayoutDashboard', path: '/ims/sections/programmes' },
      { key: 'programmes', icon: 'Layers', resource: 'programmes' },
      { key: 'projects', icon: 'FolderKanban', resource: 'projects' },
      { key: 'activities', icon: 'Activity', path: '/ims/activities', resource: 'activities' },
      { key: 'beneficiaries', icon: 'HeartHandshake', resource: 'beneficiaries' },
      { key: 'impact', icon: 'TrendingUp', path: '/ims/impact' },
    ],
  },
  {
    group: 'finance', items: [
      { key: 'finance_dashboard', icon: 'PieChart', path: '/ims/finance' },
      { key: 'receipts_payments', icon: 'ReceiptText', path: '/ims/finance/receipts-payments' },
      { key: 'ledger_journal', icon: 'BookOpen', path: '/ims/finance/ledger' },
      { key: 'financialYears', icon: 'CalendarRange', resource: 'financialYears' },
      { key: 'funds', icon: 'Wallet', resource: 'funds' },
      { key: 'chart_of_accounts', icon: 'BookOpen', resource: 'accounts' },
      { key: 'cost_centres', icon: 'Target', path: '/ims/finance/cost-centres' },
      { key: 'bank_accounts', icon: 'Landmark', resource: 'bankAccounts' },
      { key: 'cash_accounts', icon: 'Banknote', resource: 'cashAccounts' },
      { key: 'bank_book', icon: 'BookText', path: '/ims/bank-book', resource: 'bank' },
      { key: 'cash_book', icon: 'BookText', path: '/ims/cash-book', resource: 'cash' },
      { key: 'parties', icon: 'Handshake', resource: 'parties' },
      { key: 'vouchers', icon: 'ReceiptText', resource: 'vouchers' },
      { key: 'budgets', icon: 'Target', resource: 'budgets' },
      { key: 'transactions', icon: 'ArrowLeftRight', resource: 'transactions' },
      { key: 'sahyog', icon: 'FileText', path: '/ims/legacy/sahyog' },
      { key: 'petty_cash', icon: 'FileText', path: '/ims/legacy/pettyCash' },
      { key: 'transfer', icon: 'FileText', path: '/ims/legacy/transfer' },
      { key: 'adjustment', icon: 'FileText', path: '/ims/legacy/adjustment' },
      { key: 'audited_statements', icon: 'FileText', path: '/ims/legacy/auditedStatements' },
      { key: 'audit_observations', icon: 'FileText', path: '/ims/legacy/auditObservations' },
      { key: 'depreciation', icon: 'FileText', path: '/ims/legacy/depreciation' },
      { key: 'corpus_fund', icon: 'FileText', path: '/ims/legacy/corpusFund' },
      { key: 'fund_classification', icon: 'FileText', path: '/ims/legacy/fundClassification' },
      { key: 'payroll', icon: 'FileText', path: '/ims/legacy/payroll' },
      { key: 'honorarium', icon: 'FileText', path: '/ims/legacy/honorarium' },
      { key: 'fund_utilisation', icon: 'FileText', path: '/ims/legacy/fundUtilisation' },
      { key: 'fcra', icon: 'FileText', path: '/ims/legacy/fcra' },
      { key: 'income_expenditure', icon: 'FileText', path: '/ims/legacy/incomeExpenditure' },
      { key: 'balance_sheet', icon: 'FileText', path: '/ims/legacy/balanceSheet' },
      { key: 'trial_balance', icon: 'FileText', path: '/ims/legacy/trialBalance' },
      { key: 'corpus_donation', icon: 'FileText', path: '/ims/legacy/corpusDonation' },
      { key: 'in_kind', icon: 'FileText', path: '/ims/legacy/inKind' },
      { key: 'csr_fund', icon: 'FileText', path: '/ims/legacy/csrFund' },
      { key: 'interest_income', icon: 'FileText', path: '/ims/legacy/interestIncome' },
      { key: 'event_income', icon: 'FileText', path: '/ims/legacy/eventIncome' },
      { key: 'anonymous_donation', icon: 'FileText', path: '/ims/legacy/anonymousDonation' },
      { key: 'fund_wise_income', icon: 'FileText', path: '/ims/legacy/fundWiseIncome' },
      { key: 'pledge', icon: 'FileText', path: '/ims/legacy/pledge' },
      { key: 'payment_voucher', icon: 'FileText', path: '/ims/legacy/paymentVoucher' },
      { key: 'rent', icon: 'FileText', path: '/ims/legacy/rent' },
      { key: 'programme_expense', icon: 'FileText', path: '/ims/legacy/programmeExpense' },
      { key: 'travel', icon: 'FileText', path: '/ims/legacy/travel' },
      { key: 'advance', icon: 'FileText', path: '/ims/legacy/advance' },
      { key: 'capital_expenditure', icon: 'FileText', path: '/ims/legacy/capitalExpenditure' },
      { key: 'bank_charges', icon: 'FileText', path: '/ims/legacy/bankCharges' },
      { key: 'security_deposit', icon: 'FileText', path: '/ims/legacy/securityDeposit' },
      { key: 'creditors', icon: 'FileText', path: '/ims/legacy/creditors' },
      { key: 'debtors', icon: 'FileText', path: '/ims/legacy/debtors' },
      { key: 'reserve_fund', icon: 'FileText', path: '/ims/legacy/reserveFund' },
      { key: 'contingent_liability', icon: 'FileText', path: '/ims/legacy/contingentLiability' },
      { key: 'physical_verification', icon: 'FileText', path: '/ims/legacy/physicalVerification' },
      { key: 'insurance', icon: 'FileText', path: '/ims/legacy/insurance' },
      { key: 'bank_account_master', icon: 'FileText', path: '/ims/legacy/bankAccountMaster' },
      { key: 'cheque_issue', icon: 'FileText', path: '/ims/legacy/chequeIssue' },
      { key: 'cheque_book', icon: 'FileText', path: '/ims/legacy/chequeBook' },
      { key: 'signatory_authority', icon: 'FileText', path: '/ims/legacy/signatoryAuthority' },
      { key: 'fd_receipt', icon: 'FileText', path: '/ims/legacy/fdReceipt' },
      { key: 'budget_revision', icon: 'FileText', path: '/ims/legacy/budgetRevision' },
      { key: 'cash_flow', icon: 'FileText', path: '/ims/legacy/cashFlow' },
      { key: 'variance', icon: 'FileText', path: '/ims/legacy/variance' },
      { key: 'party_master', icon: 'FileText', path: '/ims/legacy/partyMaster' },
      { key: 'cost_centre', icon: 'FileText', path: '/ims/legacy/costCentre' },
      { key: 'document_index', icon: 'FileText', path: '/ims/legacy/documentIndex' },
    ],
  },
  {
    group: 'resources', items: [
      { key: 'resources_dashboard', icon: 'LayoutDashboard', path: '/ims/sections/resources' },
      { key: 'donors', icon: 'Heart', resource: 'donors' },
      { key: 'donations', icon: 'Gift', resource: 'donations' },
      { key: 'grants', icon: 'BadgeDollarSign', resource: 'grants' },
      { key: 'procurement', icon: 'ShoppingCart', path: '/ims/procurement' },
      { key: 'assets', icon: 'Package', resource: 'assets' },
      { key: 'inventory', icon: 'Boxes', resource: 'inventory' },
      { key: 'employees', icon: 'BriefcaseBusiness', resource: 'employees' },
      { key: 'volunteers', icon: 'HandHeart', resource: 'volunteers' },
      { key: 'attendance', icon: 'CalendarCheck', resource: 'attendance' },
      { key: 'employee_master', icon: 'FileText', path: '/ims/legacy/employeeMaster' },
      { key: 'volunteer_intern', icon: 'FileText', path: '/ims/legacy/volunteerIntern' },
      { key: 'reimbursement_advance', icon: 'FileText', path: '/ims/legacy/reimbursementAdvance' },
    ],
  },
  {
    group: 'compliance', items: [
      { key: 'compliance_dashboard', icon: 'LayoutDashboard', path: '/ims/sections/compliance' },
      { key: 'compliance', icon: 'ShieldCheck', resource: 'compliance' },
      { key: 'legal', icon: 'Scale', resource: 'agreements' },
      { key: 'audit_risk', icon: 'SearchCheck', resource: 'audits' },
      { key: 'risks', icon: 'TriangleAlert', resource: 'risks' },
      { key: 'integrity', icon: 'Fingerprint', path: '/ims/integrity' },
      { key: 'statutory_registrations', icon: 'FileText', path: '/ims/legacy/statutoryRegistrations' },
      { key: 'tax_returns', icon: 'FileText', path: '/ims/legacy/taxReturns' },
      { key: 'compliance_calendar', icon: 'FileText', path: '/ims/legacy/complianceCalendar' },
      { key: 'legal_case', icon: 'FileText', path: '/ims/legacy/legalCase' },
      { key: 'property_lease', icon: 'FileText', path: '/ims/legacy/propertyLease' },
      { key: 'related_party', icon: 'FileText', path: '/ims/legacy/relatedParty' },
      { key: 'licence', icon: 'FileText', path: '/ims/legacy/licence' },
      { key: 'agm_minutes', icon: 'FileText', path: '/ims/legacy/agmMinutes' },
      { key: 'ec_minutes', icon: 'FileText', path: '/ims/legacy/ecMinutes' },
      { key: 'resolution', icon: 'FileText', path: '/ims/legacy/resolution' },
      { key: 'delegation', icon: 'FileText', path: '/ims/legacy/delegation' },
      { key: 'policy', icon: 'FileText', path: '/ims/legacy/policy' },
      { key: 'member_register', icon: 'FileText', path: '/ims/legacy/memberRegister' },
      { key: 'office_bearer', icon: 'FileText', path: '/ims/legacy/officeBearer' },
      { key: 'donor_master', icon: 'FileText', path: '/ims/legacy/donorMaster' },
      { key: 'grant_agreement', icon: 'FileText', path: '/ims/legacy/grantAgreement' },
      { key: 'utilisation_certificate', icon: 'FileText', path: '/ims/legacy/utilisationCertificate' },
      { key: 'donor_reporting', icon: 'FileText', path: '/ims/legacy/donorReporting' },
      { key: 'foreign_donor', icon: 'FileText', path: '/ims/legacy/foreignDonor' },
      { key: 'segregation_of_duties', icon: 'FileText', path: '/ims/legacy/segregationOfDuties' },
      { key: 'maker_checker', icon: 'FileText', path: '/ims/legacy/makerChecker' },
      { key: 'access_log', icon: 'FileText', path: '/ims/legacy/accessLog' },
      { key: 'whistleblower', icon: 'FileText', path: '/ims/legacy/whistleblower' },
      { key: 'risk', icon: 'FileText', path: '/ims/legacy/risk' },
      { key: 'internal_audit', icon: 'FileText', path: '/ims/legacy/internalAudit' },
      { key: 'management_response', icon: 'FileText', path: '/ims/legacy/managementResponse' },
    ],
  },
  {
    group: 'records', items: [
      { key: 'records_dashboard', icon: 'LayoutDashboard', path: '/ims/sections/records' },
      { key: 'documents', icon: 'Files', resource: 'documents' },
      { key: 'communications', icon: 'MessageSquare', resource: 'communications' },
      { key: 'reports', icon: 'BarChart3', path: '/ims/reports' },
      { key: 'knowledge', icon: 'BookMarked', path: '/ims/knowledge' },
    ],
  },
  {
    group: 'admin', items: [
      { key: 'users', icon: 'UserCog', path: '/ims/users', resource: 'users' },
      { key: 'users_perms', icon: 'KeyRound', path: '/ims/permissions' },
      { key: 'audit_trail', icon: 'ClipboardList', path: '/ims/audit-trail' },
      { key: 'import_export', icon: 'Database', path: '/ims/data' },
    ],
  },
];
