// Field schemas for the generic SSF-IMS resource browser.
// type: text | textarea | number | date | select | checkbox | person | ref:<resource>
// l: [english, hindi] label

const F = (name, en, hi, type = 'text', extra = {}) => ({ name, l: [en, hi], type, ...extra });

export const SCHEMAS = {
  persons: {
    titleKey: 'persons', icon: 'UserRound', dup: ['mobile', 'email'],
    fields: [
      F('fullName', 'Full Name', 'पूरा नाम', 'text', { required: true }),
      F('fullNameHi', 'Name (Hindi)', 'नाम (हिंदी)'),
      F('mobile', 'Mobile', 'मोबाइल'), F('altMobile', 'Alternate Mobile', 'वैकल्पिक मोबाइल'),
      F('email', 'Email', 'ईमेल'),
      F('gender', 'Gender', 'लिंग', 'select', { options: ['Male', 'Female', 'Other'] }),
      F('dob', 'Date of Birth', 'जन्म तिथि', 'date'),
      F('address', 'Address', 'पता', 'textarea'),
      F('city', 'City', 'शहर'), F('state', 'State', 'राज्य'), F('pinCode', 'PIN Code', 'पिन कोड'),
      F('occupation', 'Occupation', 'व्यवसाय'),
      F('idType', 'ID Type', 'पहचान प्रकार', 'select', { options: ['Aadhaar', 'PAN', 'Voter ID', 'Passport', 'Driving Licence'] }),
      F('idNumber', 'ID Number', 'पहचान संख्या'), F('pan', 'PAN', 'पैन'),
      F('notes', 'Notes', 'टिप्पणी', 'textarea'),
    ],
  },
  members: {
    titleKey: 'members', icon: 'IdCard',
    fields: [
      F('personId', 'Person', 'व्यक्ति', 'ref:persons', { required: true }),
      F('category', 'Category', 'श्रेणी', 'select', { options: ['Guardian/Patron', 'Lifetime', 'Ordinary', 'Honorary'] }),
      F('admissionDate', 'Admission Date', 'प्रवेश तिथि', 'date'),
      F('receiptNumber', 'Receipt Number', 'रसीद संख्या'),
      F('feeAmount', 'Fee Amount', 'शुल्क राशि', 'number'),
      F('feeFrequency', 'Fee Frequency', 'शुल्क आवृत्ति', 'select', { options: ['monthly', 'yearly', 'one-time'] }),
      F('applicationStatus', 'Application Status', 'आवेदन स्थिति', 'select', { options: ['submitted', 'review', 'approved', 'rejected'] }),
      F('approvedBy', 'Approved By', 'अनुमोदक'),
      F('approvalDate', 'Approval Date', 'अनुमोदन तिथि', 'date'),
      F('terminationDate', 'Termination Date', 'समाप्ति तिथि', 'date'),
      F('terminationReason', 'Termination Reason', 'समाप्ति कारण', 'textarea'),
    ],
  },
  meetings: {
    titleKey: 'meetings', icon: 'CalendarClock',
    fields: [
      F('meetingType', 'Meeting Type', 'बैठक प्रकार', 'select', { options: ['General Body', 'AGM', 'Special General Body', 'Managing Committee', 'Project Meeting', 'Committee Meeting', 'Other'] }),
      F('title', 'Title', 'शीर्षक', 'text', { required: true }),
      F('meetingDate', 'Date', 'दिनांक', 'date'),
      F('startTime', 'Start Time', 'प्रारंभ समय'), F('endTime', 'End Time', 'समाप्ति समय'),
      F('mode', 'Mode', 'माध्यम', 'select', { options: ['offline', 'online', 'hybrid'] }),
      F('venue', 'Venue', 'स्थान'), F('meetingLink', 'Meeting Link', 'बैठक लिंक'), F('platform', 'Platform', 'प्लेटफ़ॉर्म'),
      F('noticeDate', 'Notice Date', 'सूचना तिथि', 'date'), F('noticeDeadline', 'Notice Deadline', 'सूचना अंतिम तिथि', 'date'),
      F('agenda', 'Agenda', 'कार्यसूची', 'textarea'),
      F('quorumRequired', 'Quorum Required', 'आवश्यक कोरम'),
      F('quorumAchieved', 'Quorum Achieved', 'कोरम पूर्ण', 'checkbox'),
      F('chairman', 'Chairman', 'अध्यक्ष'),
      F('minutesStatus', 'Minutes Status', 'कार्यवृत्त स्थिति', 'select', { options: ['draft', 'review', 'approved', 'final'] }),
      F('minutes', 'Minutes', 'कार्यवृत्त', 'textarea'),
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
      F('nextMeetingDate', 'Next Meeting', 'अगली बैठक', 'date'),
    ],
  },
  resolutions: {
    titleKey: 'resolutions', icon: 'Gavel',
    fields: [
      F('meetingId', 'Meeting', 'बैठक', 'ref:meetings'),
      F('resolutionNo', 'Resolution No.', 'संकल्प संख्या'),
      F('title', 'Title', 'शीर्षक', 'text', { required: true }),
      F('body', 'Resolution Text', 'संकल्प पाठ', 'textarea'),
      F('votingResult', 'Voting Result', 'मतदान परिणाम', 'select', { options: ['passed', 'rejected', 'deferred'] }),
      F('isSpecial', 'Special Resolution', 'विशेष संकल्प', 'checkbox'),
      F('dissent', 'Dissent', 'असहमति', 'textarea'),
    ],
  },
  actions: {
    titleKey: 'actions', icon: 'ListChecks',
    fields: [
      F('title', 'Title', 'शीर्षक', 'text', { required: true }),
      F('description', 'Description', 'विवरण', 'textarea'),
      F('sourceMeetingId', 'Source Meeting', 'स्रोत बैठक', 'ref:meetings'),
      F('sourceResolutionId', 'Source Resolution', 'स्रोत संकल्प', 'ref:resolutions'),
      F('responsiblePersonId', 'Responsible Person', 'उत्तरदायी व्यक्ति', 'ref:persons'),
      F('department', 'Department', 'विभाग'),
      F('dueDate', 'Due Date', 'नियत तिथि', 'date'),
      F('priority', 'Priority', 'प्राथमिकता', 'select', { options: ['low', 'medium', 'high', 'critical'] }),
      F('actionStatus', 'Status', 'स्थिति', 'select', { options: ['pending', 'inProgress', 'completed', 'overdue', 'cancelled', 'deferred'] }),
      F('evidence', 'Evidence', 'प्रमाण', 'textarea'),
      F('completionDate', 'Completion Date', 'पूर्णता तिथि', 'date'),
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
      F('remarks', 'Remarks', 'टिप्पणी', 'textarea'),
    ],
  },
  cases: {
    titleKey: 'cases', icon: 'AlertTriangle',
    fields: [
      F('caseType', 'Case Type', 'प्रकरण प्रकार', 'select', { options: ['feeUnpaid', 'absence', 'violation', 'complaint', 'grievance', 'compliance', 'audit', 'project', 'donorReporting', 'document'] }),
      F('title', 'Title', 'शीर्षक', 'text', { required: true }),
      F('description', 'Description', 'विवरण', 'textarea'),
      F('personId', 'Person', 'व्यक्ति', 'ref:persons'),
      F('responsiblePersonId', 'Responsible Person', 'उत्तरदायी व्यक्ति', 'ref:persons'),
      F('stage', 'Stage', 'चरण', 'select', { options: ['detected', 'assigned', 'notified', 'response', 'review', 'decision', 'action', 'followUp', 'closed'] }),
      F('deadline', 'Deadline', 'अंतिम तिथि', 'date'),
      F('response', 'Response', 'उत्तर', 'textarea'),
      F('decision', 'Decision', 'निर्णय', 'textarea'),
      F('confidential', 'Confidential', 'गोपनीय', 'checkbox'),
      F('closedOn', 'Closed On', 'बंद दिनांक', 'date'),
    ],
  },
  projects: {
    titleKey: 'projects', icon: 'FolderKanban',
    fields: [
      F('programmeId', 'Programme', 'कार्यक्रम', 'ref:programmes'),
      F('name', 'Project Name', 'परियोजना नाम', 'text', { required: true }),
      F('objective', 'Objective', 'उद्देश्य', 'textarea'),
      F('startDate', 'Start Date', 'प्रारंभ तिथि', 'date'), F('endDate', 'End Date', 'समाप्ति तिथि', 'date'),
      F('responsiblePersonId', 'Responsible Person', 'उत्तरदायी व्यक्ति', 'ref:persons'),
      F('budget', 'Budget', 'बजट', 'number'),
      F('fundId', 'Fund', 'निधि', 'ref:funds'),
      F('donorId', 'Donor', 'दानदाता', 'ref:donors'),
      F('grantId', 'Grant', 'अनुदान', 'ref:grants'),
      F('risks', 'Risks', 'जोखिम', 'textarea'),
      F('results', 'Results', 'परिणाम', 'textarea'),
      F('projectStatus', 'Status', 'स्थिति', 'select', { options: ['active', 'completed', 'onHold', 'cancelled'] }),
    ],
  },
  activities: {
    titleKey: 'activities', icon: 'Activity',
    fields: [
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
      F('activityType', 'Activity Type', 'गतिविधि प्रकार', 'select', { options: ['awarenessCamp', 'counselling', 'volunteerService', 'fieldVisit', 'communityMeeting', 'training', 'educationSupport', 'plantation', 'health', 'social'] }),
      F('title', 'Title', 'शीर्षक', 'text', { required: true }),
      F('activityDate', 'Date', 'दिनांक', 'date'),
      F('isFree', 'Free / ₹0 Activity', 'निःशुल्क / ₹0 गतिविधि', 'checkbox'),
      F('participants', 'Participants', 'प्रतिभागी', 'number'),
      F('outcome', 'Outcome', 'परिणाम', 'textarea'),
    ],
  },
  transactions: {
    titleKey: 'transactions', icon: 'ArrowLeftRight',
    fields: [
      F('txnDate', 'Date', 'दिनांक', 'date'),
      F('transactionType', 'Type', 'प्रकार', 'select', { options: ['income', 'donation', 'contribution', 'grant', 'interest', 'csr', 'expense', 'rent', 'travel', 'reimbursement', 'advance', 'capital', 'bankCharges', 'transfer', 'adjustment'] }),
      F('amount', 'Amount', 'राशि', 'number', { required: true }),
      F('direction', 'Direction', 'दिशा', 'select', { options: ['in', 'out'] }),
      F('paymentMode', 'Payment Mode', 'भुगतान माध्यम', 'select', { options: ['cash', 'bank', 'upi', 'cheque', 'online'] }),
      F('financialYearId', 'Financial Year', 'वित्तीय वर्ष', 'ref:financialYears'),
      F('fundId', 'Fund', 'निधि', 'ref:funds'),
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
      F('accountId', 'Account', 'खाता', 'ref:accounts'),
      F('personId', 'Person', 'व्यक्ति', 'ref:persons'),
      F('donorId', 'Donor', 'दानदाता', 'ref:donors'),
      F('partyId', 'Party', 'पक्ष', 'ref:parties'),
      F('bankAccountId', 'Bank Account', 'बैंक खाता', 'ref:bankAccounts'),
      F('cashAccountId', 'Cash Account', 'रोकड़ खाता', 'ref:cashAccounts'),
      F('voucherId', 'Voucher', 'वाउचर', 'ref:vouchers'),
      F('needsReview', 'Needs Review', 'समीक्षा आवश्यक', 'checkbox'),
    ],
  },
  vouchers: {
    titleKey: 'vouchers', icon: 'ReceiptText',
    fields: [
      F('voucherNo', 'Voucher No.', 'वाउचर संख्या'),
      F('voucherType', 'Type', 'प्रकार', 'select', { options: ['payment', 'receipt', 'journal', 'contra', 'adjustment'] }),
      F('voucherDate', 'Date', 'दिनांक', 'date'),
      F('amount', 'Amount', 'राशि', 'number'),
      F('narration', 'Narration', 'विवरण', 'textarea'),
      F('approvedBy', 'Approved By', 'अनुमोदक'),
    ],
  },
  donations: {
    titleKey: 'donations', icon: 'Gift',
    fields: [
      F('donorId', 'Donor', 'दानदाता', 'ref:donors'),
      F('donationDate', 'Date', 'दिनांक', 'date'),
      F('amount', 'Amount', 'राशि', 'number', { required: true }),
      F('mode', 'Mode', 'माध्यम', 'select', { options: ['cash', 'bank', 'upi', 'cheque', 'online'] }),
      F('fundId', 'Fund', 'निधि', 'ref:funds'),
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
      F('restricted', 'Restricted', 'प्रतिबंधित', 'checkbox'),
      F('receiptNo', 'Receipt No.', 'रसीद संख्या'),
      F('is80G', '80G Applicable', '80G लागू', 'checkbox'),
      F('anonymous', 'Anonymous', 'अनाम', 'checkbox'),
    ],
  },
  donors: {
    titleKey: 'donors', icon: 'Heart',
    fields: [
      F('personId', 'Person', 'व्यक्ति', 'ref:persons', { required: true }),
      F('donorType', 'Donor Type', 'दानदाता प्रकार', 'select', { options: ['individual', 'corporate', 'trust', 'foreign'] }),
      F('pan', 'PAN', 'पैन'),
      F('is80G', '80G', '80G', 'checkbox'),
      F('fcra', 'FCRA', 'एफ.सी.आर.ए.', 'checkbox'),
    ],
  },
  grants: {
    titleKey: 'grants', icon: 'BadgeDollarSign',
    fields: [
      F('donorId', 'Donor', 'दानदाता', 'ref:donors'),
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
      F('fundId', 'Fund', 'निधि', 'ref:funds'),
      F('amount', 'Amount', 'राशि', 'number'),
      F('conditions', 'Conditions', 'शर्तें', 'textarea'),
      F('agreementDate', 'Agreement Date', 'अनुबंध तिथि', 'date'),
      F('utilisationDue', 'Utilisation Due', 'उपयोग अंतिम तिथि', 'date'),
      F('reportDue', 'Report Due', 'रिपोर्ट अंतिम तिथि', 'date'),
      F('utilisationCertNo', 'Utilisation Cert. No.', 'उपयोग प्रमाण संख्या'),
      F('grantStatus', 'Status', 'स्थिति', 'select', { options: ['active', 'utilised', 'closed'] }),
    ],
  },
  funds: {
    titleKey: 'funds', icon: 'Wallet',
    fields: [
      F('name', 'Fund Name', 'निधि नाम', 'text', { required: true }),
      F('fundType', 'Type', 'प्रकार', 'select', { options: ['restricted', 'unrestricted', 'corpus'] }),
      F('donorId', 'Donor', 'दानदाता', 'ref:donors'),
      F('purpose', 'Purpose', 'उद्देश्य', 'textarea'),
    ],
  },
  accounts: {
    titleKey: 'accounts', icon: 'BookOpen',
    fields: [
      F('code', 'Code', 'कोड', 'text', { required: true }),
      F('name', 'Account Name', 'खाता नाम', 'text', { required: true }),
      F('accountType', 'Type', 'प्रकार', 'select', { options: ['asset', 'liability', 'income', 'expense', 'equity'] }),
      F('parentId', 'Parent Account', 'मूल खाता', 'ref:accounts'),
    ],
  },
  financialYears: {
    titleKey: 'financialYears', icon: 'CalendarRange',
    fields: [
      F('label', 'Label', 'लेबल', 'text', { required: true }),
      F('startDate', 'Start Date', 'प्रारंभ तिथि', 'date'),
      F('endDate', 'End Date', 'समाप्ति तिथि', 'date'),
      F('isCurrent', 'Current', 'वर्तमान', 'checkbox'),
      F('isClosed', 'Closed', 'बंद', 'checkbox'),
    ],
  },
  assets: {
    titleKey: 'assets', icon: 'Package',
    fields: [
      F('name', 'Asset Name', 'संपत्ति नाम', 'text', { required: true }),
      F('category', 'Category', 'श्रेणी'),
      F('purchaseDate', 'Purchase Date', 'खरीद तिथि', 'date'),
      F('cost', 'Cost', 'लागत', 'number'),
      F('custodianPersonId', 'Custodian', 'अभिरक्षक', 'ref:persons'),
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
      F('fundId', 'Fund', 'निधि', 'ref:funds'),
      F('depreciationRate', 'Depreciation Rate %', 'मूल्यह्रास दर %', 'number'),
      F('insuranceDue', 'Insurance Due', 'बीमा देय', 'date'),
      F('verificationDue', 'Verification Due', 'सत्यापन देय', 'date'),
      F('assetStatus', 'Status', 'स्थिति', 'select', { options: ['active', 'disposed', 'transferred'] }),
    ],
  },
  documents: {
    titleKey: 'documents', icon: 'Files',
    fields: [
      F('title', 'Title', 'शीर्षक', 'text', { required: true }),
      F('category', 'Category', 'श्रेणी'),
      F('docType', 'Document Type', 'दस्तावेज़ प्रकार'),
      F('version', 'Version', 'संस्करण', 'number'),
      F('issueDate', 'Issue Date', 'जारी तिथि', 'date'),
      F('effectiveDate', 'Effective Date', 'प्रभावी तिथि', 'date'),
      F('expiryDate', 'Expiry Date', 'समाप्ति तिथि', 'date'),
      F('owner', 'Owner', 'स्वामी'),
      F('confidentiality', 'Confidentiality', 'गोपनीयता', 'select', { options: ['public', 'internal', 'restricted', 'confidential'] }),
      F('fileUrl', 'File URL', 'फ़ाइल लिंक'),
    ],
  },
  compliance: {
    titleKey: 'compliance', icon: 'ShieldCheck',
    fields: [
      F('obligation', 'Obligation', 'दायित्व', 'text', { required: true }),
      F('legalSource', 'Legal / Policy Source', 'विधिक / नीति स्रोत'),
      F('dueDate', 'Due Date', 'अंतिम तिथि', 'date'),
      F('responsiblePersonId', 'Responsible Person', 'उत्तरदायी व्यक्ति', 'ref:persons'),
      F('reviewerId', 'Reviewer', 'समीक्षक', 'ref:persons'),
      F('complianceStatus', 'Status', 'स्थिति', 'select', { options: ['pending', 'filed', 'overdue', 'na'] }),
      F('submittedOn', 'Submitted On', 'जमा दिनांक', 'date'),
      F('acknowledgement', 'Acknowledgement', 'पावती'),
      F('nextDueDate', 'Next Due', 'अगली तिथि', 'date'),
    ],
  },
  audits: {
    titleKey: 'audits', icon: 'SearchCheck',
    fields: [
      F('auditType', 'Audit Type', 'लेखा-परीक्षण प्रकार', 'select', { options: ['internal', 'external'] }),
      F('financialYearId', 'Financial Year', 'वित्तीय वर्ष', 'ref:financialYears'),
      F('auditor', 'Auditor', 'लेखा परीक्षक'),
      F('periodStart', 'Period Start', 'अवधि प्रारंभ', 'date'),
      F('periodEnd', 'Period End', 'अवधि समाप्ति', 'date'),
      F('scope', 'Scope', 'दायरा', 'textarea'),
      F('observation', 'Observation', 'अवलोकन', 'textarea'),
      F('riskLevel', 'Risk Level', 'जोखिम स्तर', 'select', { options: ['low', 'medium', 'high'] }),
      F('managementResponse', 'Management Response', 'प्रबंधन उत्तर', 'textarea'),
      F('correctiveAction', 'Corrective Action', 'सुधारात्मक कार्य', 'textarea'),
      F('dueDate', 'Due Date', 'नियत तिथि', 'date'),
      F('closureDate', 'Closure Date', 'बंद दिनांक', 'date'),
    ],
  },
  risks: {
    titleKey: 'risks', icon: 'TriangleAlert',
    fields: [
      F('title', 'Risk', 'जोखिम', 'text', { required: true }),
      F('category', 'Category', 'श्रेणी'),
      F('likelihood', 'Likelihood', 'संभावना', 'select', { options: ['low', 'medium', 'high'] }),
      F('impact', 'Impact', 'प्रभाव', 'select', { options: ['low', 'medium', 'high'] }),
      F('rating', 'Rating', 'रेटिंग'),
      F('ownerPersonId', 'Owner', 'स्वामी', 'ref:persons'),
      F('mitigation', 'Mitigation', 'शमन', 'textarea'),
      F('dueDate', 'Due Date', 'नियत तिथि', 'date'),
    ],
  },
  policies: {
    titleKey: 'policies', icon: 'FileText',
    fields: [
      F('title', 'Title', 'शीर्षक', 'text', { required: true }),
      F('category', 'Category', 'श्रेणी'),
      F('effectiveDate', 'Effective Date', 'प्रभावी तिथि', 'date'),
      F('version', 'Version', 'संस्करण', 'number'),
      F('approvedBy', 'Approved By', 'अनुमोदक'),
      F('body', 'Body', 'पाठ', 'textarea'),
    ],
  },
  governanceRules: {
    titleKey: 'governanceRules', icon: 'Scale',
    fields: [
      F('key', 'Key', 'कुंजी', 'text', { required: true }),
      F('value', 'Value', 'मान'),
      F('source', 'Source', 'स्रोत'),
      F('ruleText', 'Rule (English)', 'नियम (अंग्रेज़ी)', 'textarea'),
      F('ruleTextHi', 'Rule (Hindi)', 'नियम (हिंदी)', 'textarea'),
      F('effectiveDate', 'Effective Date', 'प्रभावी तिथि', 'date'),
      F('version', 'Version', 'संस्करण', 'number'),
      F('approvedBy', 'Approved By', 'अनुमोदक'),
    ],
  },
  committeeMembers: {
    titleKey: 'committeeMembers', icon: 'Users',
    fields: [
      F('committeeId', 'Committee', 'समिति', 'ref:committees'),
      F('personId', 'Person', 'व्यक्ति', 'ref:persons', { required: true }),
      F('position', 'Position', 'पद', 'select', { options: ['President', 'Vice President', 'Secretary', 'Treasurer', 'Joint Secretary', 'Member'] }),
      F('responsibility', 'Responsibility', 'जिम्मेदारी'),
      F('fromDate', 'From', 'से', 'date'), F('toDate', 'To', 'तक', 'date'),
    ],
  },
  committees: {
    titleKey: 'committees', icon: 'Landmark',
    fields: [
      F('name', 'Committee Name', 'समिति नाम', 'text', { required: true }),
      F('termStart', 'Term Start', 'कार्यकाल प्रारंभ', 'date'),
      F('termEnd', 'Term End', 'कार्यकाल समाप्ति', 'date'),
      F('isCurrent', 'Current Committee', 'वर्तमान समिति', 'checkbox'),
      F('formedOn', 'Formed On', 'गठन दिनांक', 'date'),
      F('remarks', 'Remarks', 'टिप्पणी', 'textarea'),
    ],
  },
  organisations: {
    titleKey: 'organisations', icon: 'Building2',
    fields: [
      F('name', 'Name', 'नाम', 'text', { required: true }),
      F('legalName', 'Legal Name', 'विधिक नाम'),
      F('regNumber', 'Registration Number', 'पंजीकरण संख्या'),
      F('regAuthority', 'Registering Authority', 'पंजीकरण प्राधिकारी'),
      F('regDate', 'Registration Date', 'पंजीकरण तिथि', 'date'),
      F('pan', 'PAN', 'पैन'), F('tan', 'TAN', 'टैन'),
      F('address', 'Address', 'पता', 'textarea'),
      F('areaOfOperation', 'Area of Operation', 'कार्यक्षेत्र', 'textarea'),
      F('contactEmail', 'Contact Email', 'संपर्क ईमेल'),
      F('contactPhone', 'Contact Phone', 'संपर्क फ़ोन'),
      F('website', 'Website', 'वेबसाइट'),
    ],
  },
  programmes: {
    titleKey: 'programmes', icon: 'Layers',
    fields: [
      F('name', 'Programme Name', 'कार्यक्रम नाम', 'text', { required: true }),
      F('objective', 'Objective', 'उद्देश्य', 'textarea'),
      F('theme', 'Theme', 'विषय'),
    ],
  },
  beneficiaries: {
    titleKey: 'beneficiaries', icon: 'HeartHandshake',
    fields: [
      F('personId', 'Person', 'व्यक्ति', 'ref:persons', { required: true }),
      F('household', 'Household / Group', 'परिवार / समूह'),
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
      F('services', 'Services Received', 'प्राप्त सेवाएँ', 'textarea'),
      F('consent', 'Consent Given', 'सहमति', 'checkbox'),
      F('caseNotes', 'Case Notes', 'प्रकरण टिप्पणी', 'textarea'),
    ],
  },
  employees: {
    titleKey: 'employees', icon: 'BriefcaseBusiness',
    fields: [
      F('personId', 'Person', 'व्यक्ति', 'ref:persons', { required: true }),
      F('designation', 'Designation', 'पदनाम'),
      F('department', 'Department', 'विभाग'),
      F('joinDate', 'Join Date', 'जॉइन दिनांक', 'date'),
      F('salary', 'Salary', 'वेतन', 'number'),
      F('separationDate', 'Separation Date', 'पृथक्करण दिनांक', 'date'),
    ],
  },
  volunteers: {
    titleKey: 'volunteers', icon: 'HandHeart',
    fields: [
      F('personId', 'Person', 'व्यक्ति', 'ref:persons', { required: true }),
      F('skills', 'Skills', 'कौशल', 'textarea'),
      F('availability', 'Availability', 'उपलब्धता'),
      F('joinDate', 'Join Date', 'जॉइन दिनांक', 'date'),
    ],
  },
  attendance: {
    titleKey: 'attendance', icon: 'CalendarCheck',
    fields: [
      F('personId', 'Person', 'व्यक्ति', 'ref:persons'),
      F('refType', 'Context', 'संदर्भ', 'select', { options: ['employee', 'volunteer', 'meeting'] }),
      F('attDate', 'Date', 'दिनांक', 'date'),
      F('attStatus', 'Status', 'स्थिति', 'select', { options: ['present', 'absent', 'late', 'leave'] }),
      F('remarks', 'Remarks', 'टिप्पणी', 'textarea'),
    ],
  },
  parties: {
    titleKey: 'parties', icon: 'Handshake',
    fields: [
      F('name', 'Name', 'नाम', 'text', { required: true }),
      F('partyType', 'Type', 'प्रकार', 'select', { options: ['vendor', 'creditor', 'debtor', 'other'] }),
      F('personId', 'Linked Person', 'जुड़ा व्यक्ति', 'ref:persons'),
      F('gstin', 'GSTIN', 'जी.एस.टी.आई.एन.'),
      F('contact', 'Contact', 'संपर्क'),
    ],
  },
  bankAccounts: {
    titleKey: 'bankAccounts', icon: 'Landmark',
    fields: [
      F('bankName', 'Bank Name', 'बैंक नाम', 'text', { required: true }),
      F('accountNo', 'Account Number', 'खाता संख्या'),
      F('ifsc', 'IFSC', 'आई.एफ.एस.सी.'),
      F('branch', 'Branch', 'शाखा'),
      F('openingBalance', 'Opening Balance', 'प्रारंभिक शेष', 'number'),
    ],
  },
  cashAccounts: {
    titleKey: 'cashAccounts', icon: 'Banknote',
    fields: [
      F('name', 'Name', 'नाम', 'text', { required: true }),
      F('custodianPersonId', 'Custodian', 'अभिरक्षक', 'ref:persons'),
      F('openingBalance', 'Opening Balance', 'प्रारंभिक शेष', 'number'),
    ],
  },
  costCentres: {
    titleKey: 'costCentres', icon: 'Target',
    fields: [
      F('name', 'Name', 'नाम', 'text', { required: true }),
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
    ],
  },
  inventory: {
    titleKey: 'inventory', icon: 'Boxes',
    fields: [
      F('name', 'Item Name', 'वस्तु नाम', 'text', { required: true }),
      F('unit', 'Unit', 'इकाई'),
      F('openingQty', 'Opening Qty', 'प्रारंभिक मात्रा', 'number'),
      F('minQty', 'Minimum Qty', 'न्यूनतम मात्रा', 'number'),
    ],
  },
  agreements: {
    titleKey: 'agreements', icon: 'Scale',
    fields: [
      F('title', 'Title', 'शीर्षक', 'text', { required: true }),
      F('agreementType', 'Type', 'प्रकार', 'select', { options: ['mou', 'lease', 'grant', 'other'] }),
      F('partyId', 'Party', 'पक्ष', 'ref:parties'),
      F('projectId', 'Project', 'परियोजना', 'ref:projects'),
      F('fromDate', 'From', 'से', 'date'), F('toDate', 'To', 'तक', 'date'),
      F('terms', 'Terms', 'शर्तें', 'textarea'),
    ],
  },
  communications: {
    titleKey: 'communications', icon: 'MessageSquare',
    fields: [
      F('channel', 'Channel', 'माध्यम', 'select', { options: ['system', 'email', 'sms', 'whatsapp', 'manual', 'phone'] }),
      F('personId', 'Person', 'व्यक्ति', 'ref:persons'),
      F('recipient', 'Recipient', 'प्राप्तकर्ता'),
      F('sender', 'Sender', 'प्रेषक'),
      F('subject', 'Subject', 'विषय'),
      F('message', 'Message', 'संदेश', 'textarea'),
      F('deliveryStatus', 'Delivery Status', 'डिलीवरी स्थिति'),
      F('response', 'Response', 'उत्तर', 'textarea'),
    ],
  },
  users: {
    titleKey: 'users', icon: 'UserCog',
    fields: [
      F('username', 'Username', 'उपयोगकर्ता नाम', 'text', { required: true }),
      F('displayName', 'Display Name', 'प्रदर्शन नाम'),
      F('email', 'Email', 'ईमेल'),
      F('personId', 'Linked Person', 'जुड़ा व्यक्ति', 'ref:persons'),
      F('roleCode', 'Role', 'भूमिका', 'select', { options: ['super_admin', 'org_admin', 'president', 'secretary', 'treasurer', 'finance_officer', 'programme_manager', 'hr_admin', 'compliance_officer', 'auditor', 'reviewer', 'data_entry', 'volunteer_coordinator', 'read_only', 'case_officer'] }),
      F('isActive', 'Active', 'सक्रिय', 'checkbox'),
    ],
  },
  notices: {
    titleKey: 'notices_cases', icon: 'Bell',
    fields: [
      F('noticeType', 'Notice Type', 'सूचना प्रकार'),
      F('subject', 'Subject', 'विषय', 'text', { required: true }),
      F('body', 'Body', 'पाठ', 'textarea'),
      F('meetingId', 'Meeting', 'बैठक', 'ref:meetings'),
      F('deliveryStatus', 'Delivery Status', 'डिलीवरी स्थिति'),
      F('reminderCount', 'Reminder Count', 'अनुस्मारक संख्या', 'number'),
    ],
  },
  attendees: {
    titleKey: 'attendance', icon: 'CalendarCheck',
    fields: [
      F('meetingId', 'Meeting', 'बैठक', 'ref:meetings', { required: true }),
      F('personId', 'Person', 'व्यक्ति', 'ref:persons', { required: true }),
      F('invited', 'Invited', 'आमंत्रित', 'checkbox'),
      F('acknowledged', 'Acknowledged', 'पुष्टि', 'checkbox'),
      F('attendance', 'Attendance', 'उपस्थिति', 'select', { options: ['present', 'absent', 'late', 'leftEarly', 'online', 'offline', 'apology'] }),
      F('joinedMode', 'Joined Mode', 'जुड़ने का माध्यम'),
      F('evidence', 'Evidence', 'प्रमाण', 'textarea'),
    ],
  },
};

// Generic fallback: show any field returned by the API.
export function schemaFor(resource) {
  return SCHEMAS[resource] || null;
}

export const PRIMARY_FIELD = {
  persons: 'fullName', members: 'memberNo', meetings: 'title', resolutions: 'title',
  actions: 'title', cases: 'title', projects: 'name', activities: 'title', transactions: 'transactionNo',
  vouchers: 'voucherNo', donations: 'receiptNo', donors: 'donorType', grants: 'utilisationCertNo',
  funds: 'name', accounts: 'name', financialYears: 'label', assets: 'name', documents: 'title',
  compliance: 'obligation', audits: 'auditor', risks: 'title', policies: 'title',
  governanceRules: 'key', committeeMembers: 'position', committees: 'name', organisations: 'name',
  programmes: 'name', beneficiaries: 'household', employees: 'designation', volunteers: 'skills',
  attendance: 'attStatus', parties: 'name', bankAccounts: 'accountNo', cashAccounts: 'name',
  costCentres: 'name', inventory: 'name', agreements: 'title', communications: 'subject',
  users: 'username', notices: 'subject', attendees: 'attendance',
};
