// SSF Social Awareness Publisher — IMS workspace.
// Connect every social account, watch today's bilingual posts, and let the
// scheduler publish them automatically (twice a day). Nothing here removes any
// existing feature; it is a new module on top of the IMS.
import { useEffect, useMemo, useState } from 'react';
import * as Icons from 'lucide-react';
import ImsLayout from '../ImsLayout';
import { Card, SectionHero, Button, Badge, Spinner, Toggle } from '../ui';
import { useLang } from '../LangContext';
import { ims } from '../api';
import { makeReel, speakPost, downloadBlob } from '../reelMaker';
import { profileUrlFor, idHintFor, captionFor, noteFor } from '../socialProfiles';

const FIELD_LABELS = {
  pageId: { en: 'Page ID', hi: 'पेज ID' },
  igUserId: { en: 'Instagram User ID', hi: 'इंस्टाग्राम यूज़र ID' },
  botToken: { en: 'Bot Token', hi: 'बॉट टोकन' },
  chatId: { en: 'Chat ID / Channel', hi: 'चैट ID / चैनल' },
  authorUrn: { en: 'Author URN (urn:li:organization:…)', hi: 'लेखक URN' },
  accessToken: { en: 'Access Token', hi: 'एक्सेस टोकन' },
  phoneNumberId: { en: 'Phone Number ID', hi: 'फ़ोन नंबर ID' },
  to: { en: 'Send-to number', hi: 'भेजने का नंबर' },
  consumerKey: { en: 'API Key (Consumer Key)', hi: 'API Key (कंज़्यूमर Key)' },
  consumerSecret: { en: 'API Key Secret', hi: 'API Key Secret' },
  accessTokenSecret: { en: 'Access Token Secret', hi: 'Access Token Secret' },
};

const STATUS_STYLE = {
  published: 'text-emerald-700 bg-emerald-50 ring-emerald-100',
  partial: 'text-amber-700 bg-amber-50 ring-amber-100',
  draft: 'text-slate-600 bg-slate-100 ring-slate-200',
  failed: 'text-rose-700 bg-rose-50 ring-rose-100',
  connected: 'text-emerald-700 bg-emerald-50 ring-emerald-100',
  not_connected: 'text-slate-500 bg-slate-100 ring-slate-200',
  error: 'text-rose-700 bg-rose-50 ring-rose-100',
};

// Ready-made branded covers/banners (generated by
// backend_node/scripts/makeSocialCovers.js). Static files under /social-covers.
const COVERS = [
  { file: 'facebook-cover-1640x664.png', size: '1640 × 664', group: 'social', en: 'Facebook Page Cover', hi: 'फेसबुक पेज कवर' },
  { file: 'linkedin-cover-1128x191.png', size: '1128 × 191', group: 'social', en: 'LinkedIn Company Cover', hi: 'लिंक्डइन कंपनी कवर' },
  { file: 'x-header-1500x500.png', size: '1500 × 500', group: 'social', en: 'X (Twitter) Header', hi: 'एक्स हेडर' },
  { file: 'youtube-channel-art-2560x1440.png', size: '2560 × 1440', group: 'social', en: 'YouTube Channel Art', hi: 'यूट्यूब चैनल आर्ट' },
  { file: 'instagram-logo-320x320.png', size: '320 × 320', group: 'social', en: 'Instagram Profile Logo', hi: 'इंस्टाग्राम प्रोफ़ाइल लोगो' },
  { file: 'header-education-1920x480.png', size: '1920 × 480', group: 'site', en: 'Website Header — Education', hi: 'वेबसाइट हेडर — शिक्षा' },
  { file: 'header-health-1920x480.png', size: '1920 × 480', group: 'site', en: 'Website Header — Health', hi: 'वेबसाइट हेडर — स्वास्थ्य' },
  { file: 'header-environment-1920x480.png', size: '1920 × 480', group: 'site', en: 'Website Header — Environment', hi: 'वेबसाइट हेडर — पर्यावरण' },
  { file: 'header-women-1920x480.png', size: '1920 × 480', group: 'site', en: 'Website Header — Women', hi: 'वेबसाइट हेडर — महिला' },
  { file: 'header-skills-1920x480.png', size: '1920 × 480', group: 'site', en: 'Website Header — Skills', hi: 'वेबसाइट हेडर — कौशल' },
  { file: 'header-community-1920x480.png', size: '1920 × 480', group: 'site', en: 'Website Header — Community', hi: 'वेबसाइट हेडर — समुदाय' },
  { file: 'header-relief-1920x480.png', size: '1920 × 480', group: 'site', en: 'Website Header — Relief', hi: 'वेबसाइट हेडर — राहत' },
  { file: 'header-youth-1920x480.png', size: '1920 × 480', group: 'site', en: 'Website Header — Youth', hi: 'वेबसाइट हेडर — युवा' },
  { file: 'header-cta-band-1920x520.png', size: '1920 × 520', group: 'site', en: 'Website Header — Brand Band', hi: 'वेबसाइट हेडर — ब्रांड बैंड' },
  { file: 'header-office-1920x420.png', size: '1920 × 420', group: 'site', en: 'Website Header — Organisation', hi: 'वेबसाइट हेडर — संस्था' },
];
const COVER_BASE = '/social-covers/';

function BrandKit() {
  const { lang } = useLang();
  return (
    <div className="mb-8">
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <h2 className="text-sm font-black uppercase tracking-wider text-slate-500">
          {lang === 'hi' ? 'तैयार कवर और बैनर' : 'Ready-made Covers & Banners'}
        </h2>
        <span className="text-[11px] text-slate-400">
          {lang === 'hi' ? 'डाउनलोड कर सीधे लगाएँ — कोई फोटो नहीं, कोड से बने' : 'Download and upload — code-drawn, no stock photos'}
        </span>
      </div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
        {COVERS.map((c) => (
          <Card key={c.file} className="overflow-hidden">
            <img src={COVER_BASE + c.file} alt={c.en} loading="lazy"
              className="h-40 w-full border-b border-slate-100 bg-slate-50 object-cover object-top" />
            <div className="flex items-center justify-between gap-2 p-3">
              <div className="min-w-0">
                <div className="truncate text-xs font-bold text-[#002344]">{lang === 'hi' ? c.hi : c.en}</div>
                <div className="text-[11px] text-slate-400">{c.size}{c.group === 'social' ? '' : (lang === 'hi' ? ' • वेबसाइट' : ' • website')}</div>
              </div>
              <a href={COVER_BASE + c.file} download={c.file}
                className="inline-flex shrink-0 items-center gap-1 rounded-full bg-[#002344] px-3 py-1.5 text-[11px] font-bold text-white hover:bg-[#FF6600]">
                <Icons.Download size={13} /> {lang === 'hi' ? 'डाउनलोड' : 'Download'}
              </a>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}

function Chip({ label, tone = 'draft' }) {
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-[11px] font-semibold ring-1 ${STATUS_STYLE[tone] || STATUS_STYLE.draft}`}>{label}</span>;
}

function KpiBox({ icon, en, hi, value, tone = 'text-[#002344]' }) {
  const { lang } = useLang();
  const I = Icons[icon] || Icons.Activity;
  return (
    <Card className="p-4">
      <div className="flex items-center gap-3">
        <span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-[#002344]"><I size={18} /></span>
        <div className="min-w-0">
          <div className={`text-2xl font-black leading-none ${tone}`}>{value}</div>
          <div className="mt-1 truncate text-[11px] font-semibold text-slate-500">{lang === 'hi' ? hi : en}</div>
        </div>
      </div>
    </Card>
  );
}

function ChannelCard({ ch, onSave, onDisconnect, onTest, onFbExchange, onIgResolve, busy }) {
  const { lang } = useLang();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({});
  const [copied, setCopied] = useState('');
  const [testing, setTesting] = useState(false);
  const [testMsg, setTestMsg] = useState('');
  const [fb, setFb] = useState({ appId: '', appSecret: '', shortToken: '' });
  const [fbBusy, setFbBusy] = useState(false);
  const [fbMsg, setFbMsg] = useState('');
  const [igBusy, setIgBusy] = useState(false);
  const [igMsg, setIgMsg] = useState('');
  const required = ch.fields || [];
  const profileUrl = profileUrlFor(ch.platform);

  // One-time exchange: short-lived token -> permanent Page token.
  const runFbExchange = async () => {
    setFbBusy(true); setFbMsg('');
    try {
      const out = await onFbExchange(fb);
      if (out && out.ok) {
        const never = !out.expiresAt;
        const tail = never
          ? (lang === 'hi' ? 'कभी expire नहीं होगा ✅' : 'never expires ✅')
          : (lang === 'hi' ? `expire: ${new Date(out.expiresAt * 1000).toLocaleString('en-IN')}` : `expires: ${new Date(out.expiresAt * 1000).toLocaleString('en-IN')}`);
        setFbMsg(lang === 'hi'
          ? `✅ स्थायी token सेव हुआ — पेज: ${out.pageName || out.pageId} · ${tail}`
          : `✅ Permanent token saved — page: ${out.pageName || out.pageId} · ${tail}`);
      } else {
        setFbMsg(`⚠️ ${(out && (out.error || out.hint)) || 'failed'}`);
      }
    } catch (e) { setFbMsg(`⚠️ ${e.message}`); } finally { setFbBusy(false); }
  };

  // Instagram: pull the numeric id straight from the linked Facebook Page.
  const runIgResolve = async () => {
    setIgBusy(true); setIgMsg('');
    try {
      const out = await onIgResolve();
      setIgMsg(out && out.ok
        ? (lang === 'hi' ? `✅ Instagram जुड़ गया${out.username ? ` — @${out.username}` : ''}` : `✅ Instagram connected${out.username ? ` — @${out.username}` : ''}`)
        : `⚠️ ${(out && (out.hint || out.error)) || 'failed'}`);
    } catch (e) { setIgMsg(`⚠️ ${e.message}`); } finally { setIgBusy(false); }
  };

  const copyProfile = async () => {
    try { await navigator.clipboard.writeText(profileUrl); setCopied('url'); setTimeout(() => setCopied(''), 1500); } catch { /* clipboard blocked */ }
  };

  const runTest = async () => {
    setTesting(true); setTestMsg('');
    try {
      const out = await onTest(ch.platform);
      setTestMsg(out && out.ok
        ? (lang === 'hi' ? '✅ भेज दिया — अपने चैनल में देखें' : '✅ Sent — check your channel')
        : `⚠️ ${(out && (out.error || out.hint)) || 'failed'}`);
    } catch (e) {
      setTestMsg(`⚠️ ${e.message}`);
    } finally { setTesting(false); }
  };

  return (
    <Card className="p-4">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <span className="truncate text-sm font-bold text-[#002344]">{lang === 'hi' ? ch.hi : ch.en}</span>
            <Chip label={ch.always ? (lang === 'hi' ? 'हमेशा चालू' : 'Always on') : ch.status} tone={ch.always ? 'connected' : ch.status} />
          </div>
          <div className="mt-1 text-[11px] text-slate-400">
            {ch.lastPublishedAt ? `${lang === 'hi' ? 'अंतिम पोस्ट' : 'Last posted'}: ${new Date(ch.lastPublishedAt).toLocaleString('en-IN')}` : (lang === 'hi' ? 'अभी तक पोस्ट नहीं' : 'No posts yet')}
          </div>
          {ch.lastError && <div className="mt-1 truncate text-[11px] text-rose-500" title={ch.lastError}>{ch.lastError}</div>}
          {profileUrl && (
            <div className="mt-1.5 flex items-center gap-2 text-[11px]">
              <a href={profileUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold text-[#002344] hover:text-[#FF6600]">
                <Icons.ExternalLink size={12} /> {lang === 'hi' ? 'आपका पेज खोलें' : 'Open your page'}
              </a>
              <button type="button" onClick={copyProfile} className="inline-flex items-center gap-1 font-semibold text-slate-400 hover:text-[#FF6600]">
                <Icons.Copy size={12} /> {copied === 'url' ? (lang === 'hi' ? 'कॉपी हुआ' : 'Copied') : (lang === 'hi' ? 'लिंक कॉपी' : 'Copy link')}
              </button>
            </div>
          )}
        </div>
        {!ch.always && (
          <div className="flex shrink-0 items-center gap-2">
            <Toggle on={ch.enabled} onChange={(v) => onSave(ch.platform, { enabled: v })} label={ch.enabled ? (lang === 'hi' ? 'ऑन' : 'On') : (lang === 'hi' ? 'ऑफ' : 'Off')} />
          </div>
        )}
      </div>

      {!ch.always && (
        <div className="mt-3">
          <button onClick={() => setOpen((o) => !o)} className="inline-flex items-center gap-1 text-xs font-semibold text-[#FF6600]">
            <Icons.KeyRound size={13} /> {lang === 'hi' ? 'क्रेडेंशियल जोड़ें' : 'Add credentials'} <Icons.ChevronDown size={13} />
          </button>
          {open && (
            <div className="mt-2 space-y-2 rounded-xl border border-slate-200 bg-slate-50/60 p-3">
              {noteFor(ch.platform, lang) && (
                <div className="rounded-lg border border-amber-300 bg-amber-50 p-2 text-[10px] leading-snug text-amber-800">
                  {noteFor(ch.platform, lang)}
                </div>
              )}
              {required.map((f) => (
                <label key={f} className="block">
                  <span className="mb-1 block text-[11px] font-semibold text-slate-500">{lang === 'hi' ? FIELD_LABELS[f]?.hi : FIELD_LABELS[f]?.en}{f === 'accessToken' || f === 'botToken' ? ' 🔒' : ''}</span>
                  <input
                    value={form[f] || ''} onChange={(e) => setForm((s) => ({ ...s, [f]: e.target.value }))}
                    className="w-full rounded-lg border border-slate-300 px-3 py-1.5 text-sm outline-none focus:border-[#FF6600]"
                    placeholder={f}
                  />
                  {idHintFor(ch.platform, f, lang) && (
                    <span className="mt-1 block text-[10px] leading-snug text-slate-400">{idHintFor(ch.platform, f, lang)}</span>
                  )}
                </label>
              ))}
              {ch.platform === 'facebook' && (
                <div className="mt-1 rounded-xl border border-[#FF6600]/30 bg-[#FFF7F0] p-3">
                  <div className="text-[11px] font-bold text-[#002344]">
                    {lang === 'hi' ? '🔁 स्थायी token बनाएँ (कभी expire न हो)' : '🔁 Get a permanent token (never expires)'}
                  </div>
                  <p className="mt-1 text-[10px] leading-snug text-slate-500">
                    {lang === 'hi'
                      ? 'Facebook App ID, App Secret और एक छोटा user token डालें — हम उसे स्थायी Page token में बदलकर सेव कर देंगे।'
                      : 'Enter the Facebook App ID, App Secret and a short-lived user token — we exchange it for a permanent Page token and save it.'}
                  </p>
                  <div className="mt-2 space-y-2">
                    {[['appId', 'App ID'], ['appSecret', 'App Secret'], ['shortToken', lang === 'hi' ? 'छोटा user token' : 'Short-lived user token']].map(([k, ph]) => (
                      <input key={k} type={k === 'appSecret' || k === 'shortToken' ? 'password' : 'text'}
                        value={fb[k]} onChange={(e) => setFb((s) => ({ ...s, [k]: e.target.value }))}
                        placeholder={ph} className="w-full rounded-lg border border-slate-300 px-3 py-1.5 text-sm outline-none focus:border-[#FF6600]" />
                    ))}
                  </div>
                  <div className="mt-2">
                    <Button variant="ghost" icon="KeyRound" disabled={fbBusy} onClick={runFbExchange}>
                      {fbBusy ? (lang === 'hi' ? 'बदल रहे हैं…' : 'Exchanging…') : (lang === 'hi' ? 'स्थायी token बनाएँ' : 'Exchange for permanent token')}
                    </Button>
                  </div>
                  {fbMsg && <div className="mt-1 text-[11px] font-semibold text-slate-600">{fbMsg}</div>}
                </div>
              )}
              {ch.platform === 'instagram' && (
                <div className="mt-1 rounded-xl border border-[#FF6600]/30 bg-[#FFF7F0] p-3">
                  <div className="text-[11px] font-bold text-[#002344]">
                    {lang === 'hi' ? '🔎 Instagram id अपने-आप भरें' : '🔎 Fill the Instagram id automatically'}
                  </div>
                  <p className="mt-1 text-[10px] leading-snug text-slate-500">
                    {lang === 'hi'
                      ? 'Facebook पेज जुड़ा हो तो यह बटन Instagram Business account की id खुद ले लेगा — मैन्युअल id की ज़रूरत नहीं।'
                      : 'If your Facebook Page is connected, this pulls the Instagram Business account id for you — no manual id needed.'}
                  </p>
                  <div className="mt-2">
                    <Button variant="ghost" icon="KeyRound" disabled={igBusy} onClick={runIgResolve}>
                      {igBusy ? (lang === 'hi' ? 'ढूँढ रहे हैं…' : 'Detecting…') : (lang === 'hi' ? 'Instagram id अपने-आप लाएँ' : 'Detect Instagram id')}
                    </Button>
                  </div>
                  {igMsg && <div className="mt-1 text-[11px] font-semibold text-slate-600">{igMsg}</div>}
                </div>
              )}
              <div className="flex flex-wrap items-center gap-2 pt-1">
                <Button disabled={busy} icon="Check" onClick={() => { onSave(ch.platform, { ...form, enabled: true }); setForm({}); setOpen(false); }}>
                  {lang === 'hi' ? 'सहेजें' : 'Save & connect'}
                </Button>
                {ch.configured && (
                  <>
                    <Button variant="ghost" icon="FlaskConical" disabled={testing} onClick={runTest}>
                      {testing ? (lang === 'hi' ? 'भेज रहे हैं…' : 'Sending…') : (lang === 'hi' ? 'टेस्ट भेजें' : 'Send test')}
                    </Button>
                    <Button variant="danger" icon="Trash2" disabled={busy} onClick={() => onDisconnect(ch.platform)}>
                      {lang === 'hi' ? 'हटाएँ' : 'Disconnect'}
                    </Button>
                  </>
                )}
              </div>
              {testMsg && <div className="pt-1 text-[11px] font-semibold text-slate-600">{testMsg}</div>}
            </div>
          )}
        </div>
      )}
    </Card>
  );
}

function PostCard({ post, onPublish, onEdit, busy }) {
  const { lang } = useLang();
  const [editing, setEditing] = useState(false);
  const [body, setBody] = useState(lang === 'hi' ? post.bodyHi : post.bodyEn);
  const [reelBusy, setReelBusy] = useState(false);
  const [reelPct, setReelPct] = useState(0);
  const [copied, setCopied] = useState('');
  // format=png so the preview shows the exact rasterised image that gets published.
  const img = `${import.meta.env.VITE_BACKEND_URL || ''}/api/social/image/daily?postId=${post.id}&format=png`;
  const imgSrc = img.startsWith('/') ? `${(import.meta.env.VITE_BACKEND_URL || '').replace(/\/$/, '')}${img}` : img;

  const genReel = async () => {
    setReelBusy(true); setReelPct(0);
    try {
      const blob = await makeReel(post, lang, { seconds: 18, onProgress: setReelPct });
      downloadBlob(blob, `ssf-reel-${post.postRef || post.id}.webm`);
    } catch (e) {
      alert(e.message);
    } finally {
      setReelBusy(false); setReelPct(0);
    }
  };

  // Token-free sharing: copy the caption, or open WhatsApp/Telegram prefilled.
  // This is what makes the module useful on day one, before any API keys exist.
  const copyCaption = async () => {
    try { await navigator.clipboard.writeText(captionFor(post, lang)); setCopied('caption'); setTimeout(() => setCopied(''), 1500); } catch { /* clipboard blocked */ }
  };
  const shareTo = (kind) => {
    const text = captionFor(post, lang);
    const url = kind === 'telegram'
      ? `https://t.me/share/url?url=${encodeURIComponent('https://swastiksrijan.in/Blog')}&text=${encodeURIComponent(text)}`
      : `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  return (
    <Card className="overflow-hidden">
      <div className="flex gap-4 p-4">
        <div className="hidden w-28 shrink-0 overflow-hidden rounded-xl ring-1 ring-slate-200 sm:block">
          <img src={imgSrc} alt="" className="h-full w-full object-cover" loading="lazy" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <Chip label={post.slot} />
            <Chip label={post.status} tone={post.status} />
            {post.category && <Chip label={post.category} />}
            <span className="text-[11px] font-semibold text-slate-400">{post.postRef}</span>
          </div>
          <h3 className="mt-2 text-sm font-bold text-[#002344]">{lang === 'hi' ? post.titleHi : post.titleEn}</h3>
          {lang !== 'hi' && <p className="text-xs font-semibold text-slate-500">{post.titleHi}</p>}
          {editing ? (
            <textarea value={body} onChange={(e) => setBody(e.target.value)} rows={6}
              className="mt-2 w-full rounded-lg border border-slate-300 p-2 text-xs outline-none focus:border-[#FF6600]" />
          ) : (
            <pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-2 text-[11px] leading-relaxed text-slate-600">{body}</pre>
          )}
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <Button icon="Send" disabled={busy} onClick={() => onPublish(post.id)}>{lang === 'hi' ? 'अभी पोस्ट करें' : 'Publish now'}</Button>
            {editing ? (
              <Button variant="ghost" icon="Check" disabled={busy} onClick={() => { onEdit(post.id, lang === 'hi' ? { bodyHi: body } : { bodyEn: body }); setEditing(false); }}>
                {lang === 'hi' ? 'सहेजें' : 'Save'}
              </Button>
            ) : (
              <Button variant="ghost" icon="Pencil" onClick={() => setEditing(true)}>{lang === 'hi' ? 'संपादित करें' : 'Edit'}</Button>
            )}
            <Button variant="ghost" icon="Video" disabled={reelBusy} onClick={genReel}>
              {reelBusy ? `${Math.round(reelPct * 100)}%` : (lang === 'hi' ? 'रील बनाएँ' : 'Make reel')}
            </Button>
            <Button variant="ghost" icon="Volume2" disabled={reelBusy} onClick={() => speakPost(post, lang)}>
              {lang === 'hi' ? 'सुनें (हिंदी)' : 'Listen'}
            </Button>
            <Button variant="ghost" icon="Copy" onClick={copyCaption}>
              {copied === 'caption' ? (lang === 'hi' ? 'कॉपी हुआ' : 'Copied') : (lang === 'hi' ? 'कैप्शन कॉपी' : 'Copy caption')}
            </Button>
            <Button variant="ghost" icon="MessageCircle" onClick={() => shareTo('whatsapp')}>
              {lang === 'hi' ? 'WhatsApp शेयर' : 'Share WhatsApp'}
            </Button>
            <Button variant="ghost" icon="Send" onClick={() => shareTo('telegram')}>
              {lang === 'hi' ? 'Telegram शेयर' : 'Share Telegram'}
            </Button>
          </div>
          {post.results && post.results.length > 0 && (
            <div className="mt-3 flex flex-wrap gap-1.5">
              {post.results.map((r) => (
                <span key={r.platform} className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold ${r.ok ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-600'}`}>
                  {r.ok ? '✓' : '✕'} {r.platform}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>
    </Card>
  );
}

// Distinct connection states — the dashboard must not blur "connected",
// "authenticated", "configured", "scheduled" and "published".
function StatusStrip({ data, lang }) {
  const hb = data.heartbeat || {};
  const chips = [
    { en: 'Scheduler', hi: 'शेड्यूलर', ok: !hb.failing, text: hb.lastRunAt ? new Date(hb.lastRunAt).toLocaleString(lang === 'hi' ? 'hi-IN' : 'en-IN') : (lang === 'hi' ? 'कभी नहीं चला' : 'never ran') },
    { en: 'Last success', hi: 'अंतिम सफल', ok: !!hb.lastSuccessAt, text: hb.lastSuccessAt ? new Date(hb.lastSuccessAt).toLocaleString(lang === 'hi' ? 'hi-IN' : 'en-IN') : '—' },
    { en: 'Runs / 24h', hi: '24घं में रन', ok: true, text: String(hb.runsLast24h ?? 0) },
    { en: 'Next post', hi: 'अगली पोस्ट', ok: !!data.nextScheduledAt, text: data.nextScheduledAt ? data.nextScheduledAt.replace('T', ' ') : '—' },
  ];
  return (
    <Card className="mb-6 p-4">
      <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
        <h2 className="text-sm font-black uppercase tracking-wider text-slate-500">
          {lang === 'hi' ? 'शेड्यूलर एवं स्थिति' : 'Scheduler & Status'}
        </h2>
        <span className="text-[11px] text-slate-400">{data.timezone} · {data.todayLocalTime}</span>
      </div>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        {chips.map((c) => (
          <div key={c.en} className="rounded-xl border border-slate-100 bg-slate-50 p-3">
            <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wide text-slate-400">
              <span className={`inline-block h-2 w-2 rounded-full ${c.ok ? 'bg-emerald-500' : 'bg-rose-500'}`} />
              {lang === 'hi' ? c.hi : c.en}
            </div>
            <div className="mt-1 truncate text-xs font-semibold text-[#002344]">{c.text}</div>
          </div>
        ))}
      </div>
      {hb.failing && (
        <div className="mt-3 rounded-xl border border-rose-200 bg-rose-50 p-2 text-xs text-rose-700">
          ⚠️ {lang === 'hi' ? 'पिछला शेड्यूलर रन विफल रहा' : 'The last scheduler run failed'}: {hb.lastRunError || '—'}
        </div>
      )}
      {data.calendarWarnings?.uncertainCount > 0 && (
        <div className="mt-2 rounded-xl border border-amber-200 bg-amber-50 p-2 text-xs text-amber-700">
          📅 {lang === 'hi' ? `${data.calendarWarnings.uncertainCount} तिथियाँ समीक्षा हेतु अनिश्चित हैं (चंद्र तिथियाँ)` : `${data.calendarWarnings.uncertainCount} dates are flagged uncertain for review (lunar/moon-sighting)`}
        </div>
      )}
      {data.freshness?.warning && (
        <div className="mt-2 rounded-xl border border-amber-200 bg-amber-50 p-2 text-xs text-amber-700">
          🔁 {lang === 'hi' ? 'हाल के पोस्टों में विषय दोहराव मिला' : 'Recent posts repeat a topic'} ({data.freshness.repeats.map((r) => r.topicKey).join(', ')})
        </div>
      )}
    </Card>
  );
}

const TRADITIONS = ['hindu', 'muslim', 'sikh', 'christian', 'buddhist', 'jain', 'jewish', 'indigenous', 'national', 'regional', 'un', 'other'];

// Admin-editable, searchable multicultural calendar. Add / approve / exclude
// entries without any code change.
function CalendarTab({ data, busy, run, lang }) {
  const [q, setQ] = useState('');
  const [tradition, setTradition] = useState('');
  const [form, setForm] = useState(null);
  const filtered = useMemo(() => (data.calendar || []).filter((e) => {
    if (tradition && e.tradition !== tradition) return false;
    if (!q) return true;
    const s = `${e.titleEn} ${e.titleHi} ${e.altNames || ''} ${e.region} ${e.date}`.toLowerCase();
    return s.includes(q.toLowerCase());
  }), [data.calendar, q, tradition]);

  const empty = { date: new Date().toISOString().slice(0, 10), titleEn: '', titleHi: '', tradition: 'other', region: 'India', calendarSystem: 'gregorian', eventType: 'observance', greetingEn: '', greetingHi: '', significanceEn: '', significanceHi: '', verified: true, uncertain: false };

  return (
    <div className="mb-8">
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <input value={q} onChange={(e) => setQ(e.target.value)} placeholder={lang === 'hi' ? 'खोजें…' : 'Search…'}
          className="w-48 rounded-xl border border-slate-200 px-3 py-2 text-sm" />
        <select value={tradition} onChange={(e) => setTradition(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm">
          <option value="">{lang === 'hi' ? 'सभी परंपराएँ' : 'All traditions'}</option>
          {TRADITIONS.map((t) => <option key={t} value={t}>{t}</option>)}
        </select>
        <Button variant="ghost" icon="Plus" disabled={busy} onClick={() => setForm(form ? null : empty)}>
          {lang === 'hi' ? 'कार्यक्रम जोड़ें' : 'Add event'}
        </Button>
      </div>

      {form && (
        <Card className="mb-4 space-y-2 p-4">
          <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
            <input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} className="rounded-xl border px-3 py-2 text-sm" />
            <input placeholder="Title (EN)" value={form.titleEn} onChange={(e) => setForm({ ...form, titleEn: e.target.value })} className="rounded-xl border px-3 py-2 text-sm" />
            <input placeholder="Title (HI)" value={form.titleHi} onChange={(e) => setForm({ ...form, titleHi: e.target.value })} className="rounded-xl border px-3 py-2 text-sm" />
            <select value={form.tradition} onChange={(e) => setForm({ ...form, tradition: e.target.value })} className="rounded-xl border px-3 py-2 text-sm">
              {TRADITIONS.map((t) => <option key={t} value={t}>{t}</option>)}
            </select>
            <input placeholder="Greeting (EN)" value={form.greetingEn} onChange={(e) => setForm({ ...form, greetingEn: e.target.value })} className="rounded-xl border px-3 py-2 text-sm sm:col-span-2" />
            <input placeholder="Greeting (HI)" value={form.greetingHi} onChange={(e) => setForm({ ...form, greetingHi: e.target.value })} className="rounded-xl border px-3 py-2 text-sm sm:col-span-2" />
            <label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.verified} onChange={(e) => setForm({ ...form, verified: e.target.checked })} />{lang === 'hi' ? 'सत्यापित' : 'Verified'}</label>
            <label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.uncertain} onChange={(e) => setForm({ ...form, uncertain: e.target.checked })} />{lang === 'hi' ? 'अनिश्चित तिथि' : 'Uncertain date'}</label>
            <label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.solemn || false} onChange={(e) => setForm({ ...form, solemn: e.target.checked })} />{lang === 'hi' ? 'गंभीर (स्मरण)' : 'Solemn'}</label>
          </div>
          <div className="flex gap-2">
            <Button variant="hero" disabled={busy || !form.titleEn} onClick={() => run(() => ims.socialSaveEvent(form), lang === 'hi' ? 'सहेजा' : 'Saved').then(() => setForm(null))}>{lang === 'hi' ? 'सहेजें' : 'Save'}</Button>
            <Button variant="ghost" onClick={() => setForm(null)}>{lang === 'hi' ? 'रद्द' : 'Cancel'}</Button>
          </div>
        </Card>
      )}

      <div className="mb-3 text-xs text-slate-500">
        {lang === 'hi' ? 'स्रोत' : 'Sources'}: {data.calendarWarnings?.sources?.join(' · ')}
      </div>

      <Card className="divide-y divide-slate-100">
        {filtered.length === 0 && <div className="p-6 text-center text-sm text-slate-400">—</div>}
        {filtered.slice(0, 120).map((e) => (
          <div key={e.id} className="flex flex-wrap items-center justify-between gap-2 px-4 py-2.5">
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-[#002344]">{e.date}</span>
                <span className="truncate text-xs text-slate-700">{lang === 'hi' ? (e.titleHi || e.titleEn) : e.titleEn}</span>
                {e.solemn && <Chip label="solemn" tone="failed" />}
                {e.uncertain && <Chip label="uncertain" tone="partial" />}
                {!e.verified && <Chip label="unverified" tone="partial" />}
                {e.status === 'excluded' && <Chip label="excluded" tone="failed" />}
              </div>
              <div className="text-[11px] text-slate-400">{e.tradition} · {e.region} · {e.calendarSystem}</div>
            </div>
            <div className="flex items-center gap-1">
              {e.uncertain && <Button variant="ghost" disabled={busy} onClick={() => run(() => ims.socialPatchEvent(e.id, { uncertain: false, verified: true }), lang === 'hi' ? 'सत्यापित' : 'Confirmed')}>{lang === 'hi' ? 'पुष्टि' : 'Confirm'}</Button>}
              <Button variant="ghost" disabled={busy} onClick={() => run(() => ims.socialPatchEvent(e.id, { status: e.status === 'excluded' ? 'active' : 'excluded' }), 'OK')}>
                {e.status === 'excluded' ? (lang === 'hi' ? 'बहाल' : 'Restore') : (lang === 'hi' ? 'हटाएँ' : 'Exclude')}
              </Button>
            </div>
          </div>
        ))}
      </Card>
    </div>
  );
}

export default function ImsSocial() {
  const { lang } = useLang();
  const [data, setData] = useState(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const [note, setNote] = useState('');
  const [tab, setTab] = useState('dashboard');
  const [preview, setPreview] = useState(null);
  const [filterStatus, setFilterStatus] = useState('');

  const load = async () => {
    try { setData(await ims.socialDashboard()); } catch (e) { setErr(e.message); }
  };
  useEffect(() => { load(); }, []);

  const run = async (fn, msg) => {
    setBusy(true); setErr(''); setNote('');
    try { await fn(); setNote(msg); await load(); }
    catch (e) { setErr(e.message); }
    finally { setBusy(false); }
  };

  const times = (data && data.times) || { morning: '08:00', evening: '18:00' };
  const todayPosts = (data && data.todayPosts) || [];
  const recentFiltered = (data && data.recent || []).filter((p) => !filterStatus || p.status === filterStatus);

  const openPreview = async (date, slot) => {
    setErr('');
    try { const out = await ims.socialPreview(date, slot); setPreview(out.post); }
    catch (e) { setErr(e.message); }
  };

  return (
    <ImsLayout active="social_publisher">
      <SectionHero
        eyebrow={lang === 'hi' ? 'सोशल मीडिया' : 'Social Media'}
        title={lang === 'hi' ? 'जागरूकता प्रकाशक' : 'Awareness Publisher'}
        hi={lang === 'hi' ? undefined : 'जागरूकता प्रकाशक'}
        icon="Megaphone"
        tone="orange"
        actions={
          <>
            <Button variant="hero" icon="PlayCircle" disabled={busy} onClick={() => run(() => ims.socialRun(false), lang === 'hi' ? 'शेड्यूलर चला' : 'Scheduler run')}>
              {lang === 'hi' ? 'शेड्यूलर चलाएँ' : 'Run scheduler'}
            </Button>
            <Button variant="hero" icon="FileText" disabled={busy} onClick={() => run(() => ims.socialPlan(false), lang === 'hi' ? 'ड्राफ़्ट बने' : 'Drafts generated')}>
              {lang === 'hi' ? 'सामग्री बनाएँ' : 'Generate content'}
            </Button>
            <Button variant="hero" icon="Send" disabled={busy} onClick={() => run(() => ims.socialRun(true), lang === 'hi' ? 'प्रकाशित' : 'Published')}>
              {lang === 'hi' ? 'अभी प्रकाशित करें' : 'Publish now'}
            </Button>
          </>
        }
      >
        <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-white/85">
          <span>🌅 {lang === 'hi' ? 'सुबह' : 'Morning'} <b className="text-white">{times.morning}</b></span>
          <span>🌙 {lang === 'hi' ? 'शाम' : 'Evening'} <b className="text-white">{times.evening}</b></span>
          <span className="inline-flex items-center gap-2">
            {lang === 'hi' ? 'ऑटो-प्रकाशन' : 'Auto-publish'}:{' '}
            <Toggle on={!!data?.autoApprove} onChange={(v) => run(() => (v ? ims.socialResume() : ims.socialPause()), v ? (lang === 'hi' ? 'चालू' : 'Resumed') : (lang === 'hi' ? 'रोका' : 'Paused'))} label={data?.autoApprove ? 'ON' : 'OFF'} />
          </span>
          <span className="text-white/70">🌐 {data?.timezone || 'Asia/Kolkata'}</span>
        </div>
      </SectionHero>

      {err && <Card className="mb-4 border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{err}</Card>}
      {note && <Card className="mb-4 border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{note}</Card>}
      {!data && !err && <Spinner />}

      {data && (
        <>
          <div className="mb-4 flex gap-2">
            {[['dashboard', lang === 'hi' ? 'डैशबोर्ड' : 'Dashboard'], ['calendar', lang === 'hi' ? 'कैलेंडर' : 'Calendar']].map(([k, label]) => (
              <button key={k} onClick={() => setTab(k)}
                className={`rounded-xl px-4 py-2 text-sm font-bold ${tab === k ? 'bg-[#002344] text-white' : 'bg-slate-100 text-slate-600'}`}>{label}</button>
            ))}
          </div>

          <div className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-5">
            <KpiBox icon="CalendarClock" en="Posts / day" hi="पोस्ट / दिन" value={data.scheduledPerDay} />
            <KpiBox icon="CheckCircle2" en="Published" hi="प्रकाशित" value={data.stats.published} tone="text-emerald-600" />
            <KpiBox icon="CircleDot" en="Draft" hi="ड्राफ़्ट" value={data.stats.draft} />
            <KpiBox icon="AlertTriangle" en="Partial" hi="आंशिक" value={data.stats.partial} tone="text-amber-600" />
            <KpiBox icon="PlugZap" en="Channels on" hi="चैनल चालू" value={data.channels.filter((c) => c.enabled).length} tone="text-[#FF6600]" />
          </div>

          <StatusStrip data={data} lang={lang} />

          {tab === 'calendar' && <CalendarTab data={data} busy={busy} run={run} lang={lang} />}

          {tab === 'dashboard' && (
          <>
          <div className="mb-8 grid gap-4 lg:grid-cols-2">
            <Card className="p-4">
              <h2 className="mb-2 text-sm font-black uppercase tracking-wider text-slate-500">
                📅 {lang === 'hi' ? 'आज के पर्व एवं अवसर' : "Today's festivals & observances"}
              </h2>
              {(data.todayEvents || []).length === 0
                ? <div className="text-xs text-slate-400">{lang === 'hi' ? 'आज कोई सत्यापित पर्व नहीं — सामान्य जागरूकता पोस्ट जाएगी।' : 'No verified festival today — a regular awareness post will go out.'}</div>
                : (data.todayEvents || []).map((e) => (
                  <div key={e.id} className="mb-2 rounded-xl border border-slate-100 bg-slate-50 p-3">
                    <div className="text-xs font-bold text-[#002344]">{lang === 'hi' ? (e.titleHi || e.titleEn) : e.titleEn}</div>
                    <div className="text-[11px] text-slate-500">{e.greetingEn} · {e.tradition} · {e.region}</div>
                  </div>
                ))}
            </Card>
            <Card className="p-4">
              <h2 className="mb-2 text-sm font-black uppercase tracking-wider text-slate-500">
                🗓️ {lang === 'hi' ? 'अगले 7 दिन' : 'Next 7 days'}
              </h2>
              {(data.upcomingSevenDays || []).length === 0
                ? <div className="text-xs text-slate-400">—</div>
                : (data.upcomingSevenDays || []).map((e) => (
                  <div key={e.id} className="flex items-center justify-between border-b border-slate-100 py-1.5 text-xs last:border-0">
                    <span className="font-bold text-[#002344]">{e.date}</span>
                    <span className="truncate text-slate-600">{lang === 'hi' ? (e.titleHi || e.titleEn) : e.titleEn}</span>
                    <span className="text-slate-400">{e.tradition}</span>
                  </div>
                ))}
            </Card>
          </div>

          {(data.draftsAwaitingApproval || []).length > 0 && (
            <Card className="mb-8 border-amber-200 bg-amber-50 p-4">
              <h2 className="mb-2 text-sm font-black uppercase tracking-wider text-amber-700">
                ✏️ {lang === 'hi' ? 'स्वीकृति हेतु ड्राफ़्ट' : 'Drafts awaiting approval'} ({data.draftsAwaitingApproval.length})
              </h2>
              <div className="grid gap-2">
                {data.draftsAwaitingApproval.slice(0, 8).map((p) => (
                  <div key={p.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-white/70 px-3 py-2">
                    <div className="min-w-0 text-xs">
                      <span className="font-bold text-[#002344]">{p.postDate} {p.slot}</span>
                      <span className="ml-2 text-slate-600">{p.titleEn}</span>
                    </div>
                    <Button variant="ghost" disabled={busy} onClick={() => run(() => ims.socialPublishPost(p.id), lang === 'hi' ? 'प्रकाशित' : 'Published')}>
                      {lang === 'hi' ? 'अभी भेजें' : 'Publish'}
                    </Button>
                  </div>
                ))}
              </div>
            </Card>
          )}

          {(data.failedPosts || []).length > 0 && (
            <Card className="mb-8 border-rose-200 bg-rose-50 p-4">
              <h2 className="mb-2 text-sm font-black uppercase tracking-wider text-rose-700">
                ⚠️ {lang === 'hi' ? 'विफल / आंशिक पोस्ट' : 'Failed / partial posts'}
              </h2>
              <div className="grid gap-2">
                {data.failedPosts.slice(0, 6).map((p) => (
                  <div key={p.id} className="rounded-xl bg-white/70 px-3 py-2 text-xs">
                    <span className="font-bold text-[#002344]">{p.postDate} {p.slot}</span> — {p.titleEn}
                    <div className="mt-1 flex flex-wrap gap-1">
                      {(p.failures || []).map((f) => (
                        <span key={f.platform} className="rounded-full bg-rose-100 px-2 py-0.5 text-[10px] text-rose-700">{f.platform}: {f.error || 'error'}</span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </Card>
          )}

          <BrandKit />

          <div className="mb-8">
            <h2 className="mb-3 text-sm font-black uppercase tracking-wider text-slate-500">{lang === 'hi' ? 'चैनल' : 'Channels'}</h2>
            <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
              {data.channels.map((ch) => (
                <ChannelCard key={ch.platform} ch={ch} busy={busy}
                  onSave={(p, payload) => run(() => ims.socialConnect(p, payload), lang === 'hi' ? 'चैनल अपडेट' : 'Channel updated')}
                  onTest={(p) => ims.socialTestChannel(p)}
                  onFbExchange={(payload) => ims.socialFbExchange(payload).then((out) => { if (out && out.ok) run(() => Promise.resolve(out), lang === 'hi' ? 'स्थायी token सेव' : 'Permanent token saved'); return out; })}
                  onIgResolve={() => ims.socialIgResolve({}).then((out) => { if (out && out.ok) run(() => Promise.resolve(out), lang === 'hi' ? 'Instagram जुड़ा' : 'Instagram connected'); return out; })}
                  onDisconnect={(p) => run(() => ims.socialDisconnect(p), lang === 'hi' ? 'डिसकनेक्ट' : 'Disconnected')} />
              ))}
            </div>
          </div>

          <div className="mb-8">
            <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
              <h2 className="text-sm font-black uppercase tracking-wider text-slate-500">{lang === 'hi' ? 'आज के पोस्ट' : "Today's posts"}</h2>
              <div className="flex gap-2">
                <Button variant="ghost" icon="Eye" disabled={busy} onClick={() => openPreview(data.today, 'morning')}>{lang === 'hi' ? 'पूर्वावलोकन' : 'Preview'}</Button>
                <Button variant="ghost" icon="RefreshCw" disabled={busy} onClick={() => run(() => ims.socialPlan(true), lang === 'hi' ? 'फिर बनाया' : 'Regenerated')}>
                  {lang === 'hi' ? 'फिर बनाएँ' : 'Regenerate'}
                </Button>
              </div>
            </div>
            <div className="grid gap-3">
              {todayPosts.length === 0 && <Card className="p-6 text-center text-sm text-slate-400">{lang === 'hi' ? 'आज के लिए अभी कोई पोस्ट नहीं — “सामग्री बनाएँ” दबाएँ।' : 'No posts for today yet — press “Generate content”.'}</Card>}
              {todayPosts.map((p) => (
                <PostCard key={p.id} post={p} busy={busy}
                  onPublish={(id) => run(() => ims.socialPublishPost(id), lang === 'hi' ? 'प्रकाशित' : 'Published')}
                  onEdit={(id, payload) => run(() => ims.socialEditPost(id, payload), lang === 'hi' ? 'सहेजा' : 'Saved')} />
              ))}
            </div>
          </div>

          {preview && (
            <Card className="mb-8 border-[#002344]/20 bg-slate-50 p-4">
              <div className="mb-2 flex items-center justify-between">
                <h2 className="text-sm font-black uppercase tracking-wider text-slate-500">{lang === 'hi' ? 'पूर्वावलोकन' : 'Preview'} {preview.postDate} · {preview.slot}</h2>
                <Button variant="ghost" onClick={() => setPreview(null)}>✕</Button>
              </div>
              <div className="text-sm font-bold text-[#002344]">{lang === 'hi' ? preview.titleHi : preview.titleEn}</div>
              <pre className="mt-2 whitespace-pre-wrap text-xs text-slate-600">{lang === 'hi' ? preview.bodyHi : preview.bodyEn}</pre>
            </Card>
          )}

          <div>
            <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
              <h2 className="text-sm font-black uppercase tracking-wider text-slate-500">{lang === 'hi' ? 'हाल के पोस्ट' : 'Recent posts'}</h2>
              <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-1.5 text-xs">
                <option value="">{lang === 'hi' ? 'सभी स्थिति' : 'All statuses'}</option>
                {['published', 'partial', 'draft', 'failed'].map((s) => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>
            <Card className="divide-y divide-slate-100">
              {recentFiltered.length === 0 && <div className="p-6 text-center text-sm text-slate-400">—</div>}
              {recentFiltered.map((p) => (
                <div key={p.id} className="flex flex-wrap items-center justify-between gap-2 px-4 py-2.5">
                  <div className="min-w-0">
                    <span className="text-xs font-semibold text-[#002344]">{p.postRef}</span>
                    <span className="ml-2 text-xs text-slate-500">{p.titleEn}</span>
                    {p.contentSource && <span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5 text-[10px] text-slate-500">{p.contentSource}</span>}
                    {p.tradition && <span className="ml-1 rounded-full bg-slate-100 px-2 py-0.5 text-[10px] text-slate-500">{p.tradition}</span>}
                  </div>
                  <div className="flex items-center gap-2">
                    <Chip label={p.slot} />
                    <Chip label={p.status} tone={p.status} />
                    <span className="text-[11px] text-slate-400">{p.postDate}</span>
                  </div>
                </div>
              ))}
            </Card>
          </div>

          <Card className="mt-6 p-4 text-xs text-slate-500">
            <b className="text-slate-700">{lang === 'hi' ? 'नोट' : 'Note'}:</b>{' '}
            {lang === 'hi'
              ? 'सामग्री स्रोत बैज में दिखता है — “library” = पूर्व-समीक्षित द्विभाषी पुस्तकालय, “calendar” = सत्यापित त्योहार। किसी साँचे को AI-निर्मित नहीं कहा जाता।'
              : 'The content-source badge shows provenance — “library” = pre-reviewed bilingual library, “calendar” = verified festival. No template is ever labelled AI-generated.'}
          </Card>
          </>
          )}
        </>
      )}
    </ImsLayout>
  );
}
