const express = require('express');
const Member = require('../models/Member');
const Volunteer = require('../models/Volunteer');
const Donor = require('../models/Donor');
const InternshipApplication = require('../models/InternshipApplication');
const router = express.Router();
const FRONTEND_URL=(process.env.FRONTEND_URL||'https://swastiksrijan.in').replace(/\/$/,'');
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const absolute=v=>v?(/^https?:\/\//i.test(v)?v:`${(process.env.BACKEND_PUBLIC_URL||'https://ngo-backend-03hq.onrender.com').replace(/\/$/,'')}${v.startsWith('/')?'':'/'}${v}`):'';
const verifyUrl=id=>`${FRONTEND_URL}/verify/${encodeURIComponent(id)}`;
const requireAccount=async(req,res)=>{const id=String(req.query.account||'').trim();if(!id){res.status(400).json({message:'Account reference is required.'});return null}const m=await Member.findByPk(id,{attributes:['id','fullName','email','phone','memberType','status','memberId','certId','certificateType','certificateIssuedAt','profilePhotoPath','createdAt']});if(!m){res.status(404).json({message:'Account not found.'});return null}return m};
const css=`body{font-family:Arial,Helvetica,sans-serif;background:#eef3f6;margin:0;color:#17324d}.sheet{width:900px;max-width:calc(100vw - 32px);margin:32px auto;background:#fff;border:1px solid #d9e2e8;border-radius:20px;overflow:hidden;box-shadow:0 12px 40px rgba(0,35,68,.12)}.head{background:#002344;color:#fff;padding:28px 34px}.brand{font-size:13px;letter-spacing:2px;font-weight:800}.title{font-size:28px;font-weight:900;margin:8px 0}.body{padding:36px}.muted{color:#667788}.row{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid #e7edf1;padding:13px 0}.value{font-weight:800;color:#002344}.footer{padding:20px 34px;background:#f7fafb;font-size:12px;color:#667788}.print{position:fixed;right:20px;top:20px;background:#ff6600;color:#fff;border:0;border-radius:10px;padding:12px 16px;font-weight:800;cursor:pointer}@media print{body{background:#fff}.sheet{width:100%;max-width:none;margin:0;border:0;box-shadow:none}.print{display:none}}`;
const row=(a,b)=>`<div class="row"><span class="muted">${escapeHtml(a)}</span><span class="value">${escapeHtml(b||'—')}</span></div>`;
const docHtml=(title,body,id)=>`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>${css}</style></head><body><button class="print" onclick="window.print()">Print / Save as PDF</button><main class="sheet"><header class="head"><div class="brand">SWASTIK SRIJAN FOUNDATION SAMITI</div><div class="title">${escapeHtml(title)}</div><div>Official document • Rewa, Madhya Pradesh, India</div></header><section class="body">${body}</section><footer class="footer">Document ID: <strong>${escapeHtml(id)}</strong><br>Verify authenticity: ${escapeHtml(verifyUrl(id))}</footer></main></body></html>`;

router.get('/user-document/:type/:id',async(req,res)=>{try{const m=await requireAccount(req,res);if(!m)return;const type=String(req.params.type||'').toLowerCase(),id=String(req.params.id||'').trim(),email=String(m.email||'').toLowerCase();let title='',docId=id,body='';
 if(type==='membership-id'||type==='membership-certificate'){if(m.status!=='approved'||!m.memberId||(id!==m.memberId&&id!==m.certId))return res.status(403).send('Document is not available for this account.');const isId=type==='membership-id';title=isId?'Membership Identity Card':'Membership Certificate';docId=isId?m.memberId:m.certId;const photo=absolute(m.profilePhotoPath);body=isId?`<div style="display:flex;gap:28px;align-items:center"><div style="width:150px;height:180px;border-radius:14px;background:#edf2f5;overflow:hidden;display:flex;align-items:center;justify-content:center">${photo?`<img src="${escapeHtml(photo)}" style="width:100%;height:100%;object-fit:cover">`:'<span class="muted">PHOTO</span>'}</div><div style="flex:1">${row('Name',m.fullName)}${row('Member ID',m.memberId)}${row('Membership Type',m.memberType)}${row('Certificate ID',m.certId)}${row('Issued',m.certificateIssuedAt?new Date(m.certificateIssuedAt).toLocaleDateString('en-IN'):'')}</div></div>`:`<h2 style="font-size:34px;margin-top:0">Certificate of Membership</h2><p>This is to certify that</p><h1 style="font-size:34px;color:#002344">${escapeHtml(m.fullName)}</h1><p>has been approved as a member of <strong>Swastik Srijan Foundation Samiti</strong>.</p>${row('Membership ID',m.memberId)}${row('Certificate ID',m.certId)}${row('Membership Type',m.memberType)}${row('Issue Date',m.certificateIssuedAt?new Date(m.certificateIssuedAt).toLocaleDateString('en-IN'):'')}`;
 }else if(type==='volunteer-id'||type==='volunteer-certificate'){const v=await Volunteer.findOne({where:{email},order:[['createdAt','DESC']]});if(!v||v.status!=='approved'||(id!==v.volunteerId&&id!==v.certId))return res.status(403).send('Document is not available for this account.');const isId=type==='volunteer-id';title=isId?'Volunteer Identity Card':'Volunteer Certificate';docId=isId?v.volunteerId:v.certId;const photo=absolute(m.profilePhotoPath);body=isId?`<div style="display:flex;gap:28px;align-items:center"><div style="width:150px;height:180px;border-radius:14px;background:#edf2f5;overflow:hidden;display:flex;align-items:center;justify-content:center">${photo?`<img src="${escapeHtml(photo)}" style="width:100%;height:100%;object-fit:cover">`:'<span class="muted">PHOTO</span>'}</div><div style="flex:1">${row('Name',v.fullName)}${row('Volunteer ID',v.volunteerId)}${row('Position',v.position)}${row('Certificate ID',v.certId)}${row('Approved',v.approvedAt?new Date(v.approvedAt).toLocaleDateString('en-IN'):'')}</div></div>`:`<h2 style="font-size:34px;margin-top:0">Certificate of Volunteering</h2><p>This is to certify that</p><h1 style="font-size:34px;color:#002344">${escapeHtml(v.fullName)}</h1><p>has been approved as a volunteer with <strong>Swastik Srijan Foundation Samiti</strong>.</p>${row('Volunteer ID',v.volunteerId)}${row('Certificate ID',v.certId)}${row('Role / Position',v.position)}${row('Approval Date',v.approvedAt?new Date(v.approvedAt).toLocaleDateString('en-IN'):'')}`;
 }else if(type==='donation-receipt'){const d=await Donor.findOne({where:{email,donorId:id}});if(!d||!['paid','offline'].includes(String(d.paymentStatus).toLowerCase()))return res.status(403).send('Donation receipt is available only after payment confirmation.');title='Donation Receipt';docId=d.donorId;body=`<h2 style="font-size:30px;margin-top:0">Thank You for Supporting the Mission</h2>${row('Donor',d.fullName)}${row('Donor ID',d.donorId)}${row('Amount',d.amount?`₹${d.amount}`:'')}${row('Purpose',d.donationPurpose||'General donation')}${row('Payment Status',d.paymentStatus)}${row('Payment Mode',d.paymentMode)}${row('Date',new Date(d.createdAt).toLocaleDateString('en-IN'))}`;
 }else if(type==='intern-id'||type==='intern-letter'||type==='intern-certificate'){const i=await InternshipApplication.findOne({where:{email,id}});if(!i||!['selected','completed'].includes(String(i.status).toLowerCase()))return res.status(403).send('Internship document is not available yet.');if(type==='intern-id'){if(!i.internId)return res.status(404).send('Intern ID has not been issued yet.');title='Internship Identity Card';docId=i.internId;body=`<h2 style="font-size:30px;margin-top:0">Internship Identity</h2>${row('Name',i.fullName)}${row('Intern ID',i.internId)}${row('College',i.college)}${row('Course',i.course)}${row('Internship Area',i.internshipType)}${row('Duration',i.duration)}`}if(type==='intern-letter'){if(!i.joiningLetterId)return res.status(404).send('Joining letter has not been issued yet.');title='Internship Joining / Selection Letter';docId=i.joiningLetterId;body=`<h2 style="font-size:30px;margin-top:0">Internship Selection</h2><p>Dear <strong>${escapeHtml(i.fullName)}</strong>,</p><p>We are pleased to record your selection for an internship with <strong>Swastik Srijan Foundation Samiti</strong>.</p>${row('Intern ID',i.internId)}${row('Internship Area',i.internshipType)}${row('Duration',i.duration)}${row('Start Date',i.startDate||'')}${row('Letter ID',i.joiningLetterId)}`}if(type==='intern-certificate'){if(!i.completionCertId||String(i.status).toLowerCase()!=='completed')return res.status(404).send('Completion certificate is issued only after completion is recorded.');title='Internship Completion Certificate';docId=i.completionCertId;body=`<h2 style="font-size:30px;margin-top:0">Certificate of Internship Completion</h2><p>This is to certify that</p><h1 style="font-size:34px;color:#002344">${escapeHtml(i.fullName)}</h1><p>has successfully completed the recorded internship with <strong>Swastik Srijan Foundation Samiti</strong>.</p>${row('Intern ID',i.internId)}${row('Internship Area',i.internshipType)}${row('Duration',i.duration)}${row('Certificate ID',i.completionCertId)}`}}
 else return res.status(404).send('Unknown document type.');res.setHeader('Content-Type','text/html; charset=utf-8');res.send(docHtml(title,body,docId));}catch(e){console.error('❌ User document error:',e);res.status(500).send('Unable to generate document.')}});

router.get('/verify/:id',async(req,res)=>{try{const id=String(req.params.id||'').trim();let r=null;
 if(id.startsWith('SSF-MCERT-')){const m=await Member.findOne({where:{certId:id,status:'approved'},attributes:['fullName','memberId','certId','certificateType','certificateIssuedAt','memberType']});if(m)r={valid:true,type:'Membership Certificate',name:m.fullName,officialId:m.memberId,documentId:m.certId,issuedAt:m.certificateIssuedAt,category:m.memberType}}
 if(!r&&id.startsWith('SSF-MEM-')){const m=await Member.findOne({where:{memberId:id,status:'approved'},attributes:['fullName','memberId','certId','certificateIssuedAt','memberType']});if(m)r={valid:true,type:'Membership ID Card',name:m.fullName,officialId:m.memberId,documentId:m.memberId,issuedAt:m.certificateIssuedAt,category:m.memberType}}
 if(!r&&id.startsWith('SSF-VOL-')){const v=await Volunteer.findOne({where:{volunteerId:id,status:'approved'},attributes:['fullName','volunteerId','certId','approvedAt','position']});if(v)r={valid:true,type:'Volunteer ID Card',name:v.fullName,officialId:v.volunteerId,documentId:v.volunteerId,issuedAt:v.approvedAt,category:v.position}}
 if(!r&&id.startsWith('SSF-VCERT-')){const v=await Volunteer.findOne({where:{certId:id,status:'approved'},attributes:['fullName','volunteerId','certId','approvedAt','position']});if(v)r={valid:true,type:'Volunteer Certificate',name:v.fullName,officialId:v.volunteerId,documentId:v.certId,issuedAt:v.approvedAt,category:v.position}}
 if(!r&&id.startsWith('SSF-DON-')){const d=await Donor.findOne({where:{donorId:id,paymentStatus:['paid','offline']},attributes:['fullName','donorId','donationPurpose','createdAt']}).catch(()=>null);if(d)r={valid:true,type:'Donation Receipt',name:d.fullName,officialId:d.donorId,documentId:d.donorId,issuedAt:d.createdAt,category:d.donationPurpose||'Donation'}}
 if(!r&&(id.startsWith('SSF-INT-')||id.startsWith('SSF-ILTR-')||id.startsWith('SSF-ICERT-'))){const where=id.startsWith('SSF-INT-')?{internId:id}:id.startsWith('SSF-ILTR-')?{joiningLetterId:id}:{completionCertId:id};const i=await InternshipApplication.findOne({where,attributes:['fullName','internId','joiningLetterId','completionCertId','internshipType','status','selectedAt','completedAt']});if(i&&((id.startsWith('SSF-ICERT-')&&i.status==='completed')||!id.startsWith('SSF-ICERT-')))r={valid:true,type:id.startsWith('SSF-INT-')?'Internship ID Card':id.startsWith('SSF-ILTR-')?'Internship Joining Letter':'Internship Completion Certificate',name:i.fullName,officialId:i.internId,documentId:id,issuedAt:id.startsWith('SSF-ICERT-')?i.completedAt:i.selectedAt,category:i.internshipType}}
 if(!r)return res.status(404).json({valid:false,message:'No verified SSF document was found for this ID.'});res.json(r);}catch(e){console.error('❌ Verification error:',e);res.status(500).json({valid:false,message:'Verification service unavailable.'})}});
module.exports=router;
