import { useState } from "react";
import { motion } from "framer-motion";
import { Link } from "@tanstack/react-router";
import { FaHeart, FaArrowRight, FaCheckCircle, FaUsers, FaGlobeAsia, FaHandshake, FaBullseye, FaHandsHelping, FaBookOpen, FaLaptop, FaHeartbeat, FaLeaf, FaLightbulb, FaFileAlt } from "react-icons/fa";
import OptimizedImage from "../components/OptimizedImage";
import FloatingTicker from "../components/FloatingTicker";
import ImpactTimeline from "../components/ImpactTimeline";
import EliteDonationCard from "../components/EliteDonationCard";
import AuthModal from "../components/AuthModal";
import { CONTACT_INFO } from "../config/contact";
import pageHeader from "../assets/page-header.jpg";

export default function Home() {
  const [authOpen, setAuthOpen] = useState(false);
  const [authMode, setAuthMode] = useState("signup");
  const fadeInUp = { hidden: { opacity: 0, y: 30 }, visible: { opacity: 1, y: 0, transition: { duration: 0.6 } } };
  const openAuth = (mode = "signup") => { setAuthMode(mode); setAuthOpen(true); };
  const focusAreas = [
    { title: "Education & Learning", hi: "शिक्षा एवं सीखना", icon: <FaBookOpen />, path: "/OurInitiatives" },
    { title: "Skill & Livelihood", hi: "कौशल एवं आजीविका", icon: <FaLightbulb />, path: "/SkillPrograms" },
    { title: "Health & Well-being", hi: "स्वास्थ्य एवं कल्याण", icon: <FaHeartbeat />, path: "/OurInitiatives#health" },
    { title: "Women & Child Welfare", hi: "महिला एवं बाल कल्याण", icon: <FaHandsHelping />, path: "/OurInitiatives" },
    { title: "Digital Learning", hi: "डिजिटल शिक्षा", icon: <FaLaptop />, path: "/LearningHub" },
    { title: "Environment & Awareness", hi: "पर्यावरण एवं जागरूकता", icon: <FaLeaf />, path: "/OurInitiatives#awareness" }
  ];
  const annualJourney = ["2013–14", "2014–15", "2015–16", "2016–17", "2017–18", "2018–19", "2019–20", "2020–21", "2021–22", "2022–23", "2023–24", "2024–25", "2025–26"];
  const workHighlights = [
    { title: "Education & Learning", text: "Learning opportunities and community-focused education initiatives.", image: "/images/real/scholarship_distribution.jpg" },
    { title: "Digital Learning", text: "Supporting access to computers and practical digital learning.", image: "/images/real/computer-donation-clipping.jpg" },
    { title: "Community Support", text: "Community-oriented support and awareness initiatives during times of need.", image: "/images/real/online-food-support-clipping.jpg" },
    { title: "Public Awareness", text: "Social awareness, responsible communication and community participation.", image: "/images/real/news_media_1.jpg" }
  ];
  const quickActions = [
    { title: "Join SSF", text: "Create your SSF account and get started", action: () => openAuth("signup"), icon: <FaUsers /> },
    { title: "Volunteer", text: "Give your time and skills", path: "/Volunteer", icon: <FaHandsHelping /> },
    { title: "Support Our Work", text: "Help create meaningful change", path: "/Donate", icon: <FaHeart /> }
  ];
  return (
    <div className="w-full bg-white font-sans text-zinc-800">
      <section className="relative min-h-[85vh] flex items-center pt-20 pb-20 overflow-hidden bg-[#001529]">
        <div className="absolute inset-0 z-0"><OptimizedImage src={pageHeader} alt="Swastik Srijan Foundation community activity" className="w-full h-full object-cover brightness-[0.8] contrast-[1.08]" /><div className="absolute inset-0 bg-gradient-to-r from-[#001529] via-[#001529]/70 to-[#001529]/15" /></div>
        <div className="container mx-auto px-6 relative z-10 flex items-center h-full"><motion.div initial="hidden" animate="visible" variants={fadeInUp} className="max-w-4xl space-y-7">
          <div className="flex items-center gap-3"><div className="h-[2px] w-12 bg-[#FF6600]" /><span className="text-white font-bold tracking-widest uppercase text-sm">Swastik Srijan Foundation Samiti</span></div>
          <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold text-white leading-tight drop-shadow-2xl">Creating Change.<br />Inspiring Lives.<span className="block text-2xl md:text-4xl mt-4 font-normal text-zinc-100">सहयोग • कौशल • जागरूकता • सृजन</span></h1>
          <p className="max-w-2xl text-lg md:text-xl text-zinc-100 leading-relaxed">Working for inclusive community development across India through education, skills, health, awareness and meaningful partnerships.</p>
          <div className="flex flex-col sm:flex-row gap-4 pt-2"><button type="button" onClick={() => openAuth("signup")} className="px-8 py-4 bg-[#FF6600] text-white font-bold rounded-full hover:bg-[#e65c00] transition-all shadow-xl text-lg text-center">Join SSF</button><button type="button" onClick={() => openAuth("login")} className="px-8 py-4 bg-white/10 backdrop-blur-md border-2 border-white text-white font-bold rounded-full hover:bg-white hover:text-[#002344] transition-all text-lg text-center">Login</button><Link to="/Volunteer" className="px-8 py-4 bg-white/10 backdrop-blur-md border-2 border-white/70 text-white font-bold rounded-full hover:bg-white hover:text-[#002344] transition-all text-lg text-center">Volunteer</Link><a href="https://pages.razorpay.com/pl_NCiTn7wnBOJFYG/view" target="_blank" rel="noreferrer noopener" className="px-8 py-4 bg-white text-[#002344] font-bold rounded-full hover:bg-zinc-100 transition-all text-lg text-center">Donate <FaHeart className="inline ml-2 text-[#FF6600]" /></a></div>
        </motion.div></div>
      </section>
      <div className="bg-[#002344] text-zinc-300 py-3 text-center text-xs md:text-sm font-medium border-t border-white/10"><div className="container mx-auto px-4">Registered NGO | Registered December 2013 | Reg. No. 05/22/03/11448/13 | Rewa, Madhya Pradesh | Working Across India</div></div>
      <FloatingTicker />
      <section className="py-14 bg-zinc-50 border-y border-zinc-200"><div className="container mx-auto px-4 max-w-6xl"><div className="text-center mb-9"><p className="text-[#FF6600] font-bold text-sm tracking-[0.2em] uppercase">SSF at a glance</p><h2 className="text-3xl md:text-4xl font-bold text-[#002344] mt-2">A Journey of Service Since 2013</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">{[{ text: "2013–2026", sub: "Service Journey", hi: "सेवा यात्रा", icon: <FaHeart className="text-[#FF6600] text-3xl" /> },{ text: "December 2013", sub: "Registered Foundation", hi: "पंजीकृत संस्था", icon: <FaBullseye className="text-[#002344] text-3xl" /> },{ text: "Pan India", sub: "Area of Work", hi: "कार्य क्षेत्र", icon: <FaGlobeAsia className="text-[#002344] text-3xl" /> },{ text: "6 Focus Areas", sub: "Community Priorities", hi: "प्रमुख कार्य क्षेत्र", icon: <FaHandshake className="text-green-600 text-3xl" /> }].map((item,index)=><motion.div key={index} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*0.08}} className="bg-white p-7 rounded-2xl shadow-sm hover:shadow-lg transition-shadow text-center border border-zinc-100 flex flex-col items-center"><div className="mb-4">{item.icon}</div><h3 className="text-2xl md:text-3xl font-extrabold text-zinc-800 mb-1">{item.text}</h3><p className="text-zinc-600 font-bold uppercase text-xs md:text-sm tracking-wider">{item.sub}</p><p className="text-zinc-400 text-xs mt-1">{item.hi}</p></motion.div>)}</div></div></section>
      <section className="py-16 bg-white"><div className="container mx-auto px-4 max-w-6xl"><div className="text-center mb-10"><p className="text-[#FF6600] font-bold text-sm tracking-[0.2em] uppercase">What we do</p><h2 className="text-3xl md:text-4xl font-bold text-[#002344] mt-2">Our Focus Areas</h2><p className="text-zinc-500 mt-3 max-w-2xl mx-auto">Our work brings together education, skills, health, awareness and community participation to support inclusive development.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">{focusAreas.map((item,index)=><Link key={index} to={item.path} className="group p-6 rounded-2xl border border-zinc-200 bg-white hover:border-[#FF6600]/40 hover:shadow-xl transition-all"><div className="w-12 h-12 rounded-xl bg-[#002344]/5 text-[#FF6600] flex items-center justify-center text-xl mb-5 group-hover:bg-[#FF6600] group-hover:text-white transition-colors">{item.icon}</div><h3 className="font-bold text-lg text-[#002344]">{item.title}</h3><p className="text-sm text-zinc-500 mt-1">{item.hi}</p><span className="inline-flex items-center gap-2 mt-5 text-sm font-bold text-[#FF6600]">Explore <FaArrowRight className="group-hover:translate-x-1 transition-transform" /></span></Link>)}</div></div></section>
      <section className="py-16 bg-[#f8fafc] border-y border-zinc-100"><div className="container mx-auto px-4 max-w-6xl"><div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-10"><div><p className="text-[#FF6600] font-bold text-sm tracking-[0.2em] uppercase">Annual highlights</p><h2 className="text-3xl md:text-4xl font-bold text-[#002344] mt-2">SSF Journey • Year by Year</h2><p className="text-zinc-500 mt-3 max-w-2xl">A visual record of the journey from 2013–14 to 2025–26. Year-wise details can grow here as verified reports and highlights are published.</p></div><Link to="/Impact" className="inline-flex items-center gap-2 text-[#FF6600] font-bold whitespace-nowrap">Explore Impact <FaArrowRight /></Link></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4">{annualJourney.map((year,index)=><motion.div key={year} initial={{opacity:0,scale:.94}} whileInView={{opacity:1,scale:1}} viewport={{once:true,margin:"-40px"}} transition={{delay:(index%5)*.06}} className="group bg-white rounded-2xl border border-zinc-200 p-5 min-h-[132px] flex flex-col justify-between hover:-translate-y-1 hover:shadow-xl hover:border-[#FF6600]/50 transition-all"><div className="flex items-center justify-between"><span className="w-9 h-9 rounded-xl bg-[#002344] text-white flex items-center justify-center text-sm group-hover:bg-[#FF6600] transition-colors"><FaFileAlt /></span><span className="text-xs font-bold text-zinc-300">{String(index + 1).padStart(2,"0")}</span></div><div><h3 className="text-lg md:text-xl font-black text-[#002344]">{year}</h3><p className="text-xs text-zinc-500 mt-1">Annual highlight</p></div></motion.div>)}</div></div></section>
      <section className="py-16 bg-white"><div className="container mx-auto px-4 max-w-6xl"><div className="text-center mb-10"><p className="text-[#FF6600] font-bold text-sm tracking-[0.2em] uppercase">From our work</p><h2 className="text-3xl md:text-4xl font-bold text-[#002344] mt-2">Real Work. Real Participation.</h2><p className="text-zinc-500 mt-3 max-w-2xl mx-auto">A few glimpses from SSF's work and outreach. We prefer authentic activity visuals over stock imagery.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">{workHighlights.map((item,index)=><motion.div key={item.title} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.08}} className="group overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm hover:shadow-xl transition-all"><div className="aspect-[4/3] overflow-hidden bg-zinc-100"><img src={item.image} alt={item.title} loading="lazy" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" /></div><div className="p-5"><h3 className="font-bold text-lg text-[#002344]">{item.title}</h3><p className="text-sm text-zinc-500 leading-relaxed mt-2">{item.text}</p></div></motion.div>)}</div></div></section>
      <section className="py-12 bg-transparent"><div className="container mx-auto px-4"><EliteDonationCard /></div></section>
      <section className="py-16 bg-[#f8fafc]"><div className="container mx-auto px-4 max-w-6xl"><div className="text-center mb-9"><p className="text-[#FF6600] font-bold text-sm tracking-[0.2em] uppercase">Get involved</p><h2 className="text-3xl md:text-4xl font-bold text-[#002344] mt-2">You Can Be Part of the Change</h2></div><div className="grid md:grid-cols-3 gap-5">{quickActions.map((item,i)=>item.action?<button type="button" key={i} onClick={item.action} className="text-left bg-white rounded-2xl p-7 border border-zinc-200 hover:shadow-xl hover:-translate-y-1 transition-all"><div className="text-[#FF6600] text-3xl mb-4">{item.icon}</div><h3 className="text-xl font-bold text-[#002344]">{item.title}</h3><p className="text-zinc-500 mt-2">{item.text}</p><span className="inline-flex items-center gap-2 mt-5 text-sm font-bold text-[#FF6600]">Create account <FaArrowRight /></span></button>:<Link key={i} to={item.path} className="bg-white rounded-2xl p-7 border border-zinc-200 hover:shadow-xl hover:-translate-y-1 transition-all"><div className="text-[#FF6600] text-3xl mb-4">{item.icon}</div><h3 className="text-xl font-bold text-[#002344]">{item.title}</h3><p className="text-zinc-500 mt-2">{item.text}</p><span className="inline-flex items-center gap-2 mt-5 text-sm font-bold text-[#FF6600]">Get started <FaArrowRight /></span></Link>)}</div></div></section>
      <section className="py-20 bg-white"><div className="container mx-auto px-4 max-w-5xl"><div className="text-center mb-10"><p className="text-[#FF6600] font-bold text-sm tracking-[0.2em] uppercase">About SSF</p><h2 className="text-3xl md:text-4xl font-bold text-[#002344] mt-2">Serving Communities, Creating Possibilities</h2><div className="w-20 h-1 bg-[#FF6600] mx-auto rounded-full mt-5" /></div><div className="text-lg text-zinc-600 leading-relaxed text-center"><p>Swastik Srijan Foundation is a registered non-government organization established in December 2013, working with communities across India. We believe meaningful social change grows through participation, learning, skills, awareness and cooperation.</p><div className="grid md:grid-cols-3 gap-5 text-left mt-10">{[["Our Mission","To contribute to inclusive development through education, skills, health, awareness and community participation."],["Our Approach","We encourage cooperation, practical learning, responsible awareness and partnerships for sustainable social development."],["Our Values","Transparency, dignity, equal opportunity, cooperation and service without discrimination."]].map((x,i)=><div key={i} className="bg-zinc-50 p-6 rounded-2xl border border-zinc-100"><FaCheckCircle className="text-[#FF6600] mb-4"/><h3 className="font-bold text-[#002344] mb-2">{x[0]}</h3><p className="text-sm text-zinc-600 leading-relaxed">{x[1]}</p></div>)}</div><div className="flex justify-center mt-10"><Link to="/About" className="group flex items-center gap-3 px-8 py-3 bg-white border-2 border-[#002344] text-[#002344] font-bold rounded-full hover:bg-[#002344] hover:text-white transition-all">Read Our Full Story <FaArrowRight className="group-hover:translate-x-1 transition-transform" /></Link></div></div></div></section>
      <section className="py-16 bg-[#001529] text-white"><div className="container mx-auto px-4 max-w-6xl"><div className="grid md:grid-cols-2 gap-10 items-center"><div><p className="text-[#FF6600] font-bold text-sm tracking-[0.2em] uppercase">Transparency & partnership</p><h2 className="text-3xl md:text-4xl font-bold mt-3">Trust grows when information is clear.</h2><p className="text-zinc-300 text-lg leading-relaxed mt-5">Explore SSF's journey, activities, reports and partnership opportunities. We aim to keep our work clear, responsible and community-focused.</p></div><div className="grid grid-cols-2 gap-4"><Link to="/Impact" className="p-5 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition"><h3 className="font-bold">Our Impact</h3><p className="text-sm text-zinc-400 mt-1">Activities & journey</p></Link><Link to="/GetInvolved#partner" className="p-5 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition"><h3 className="font-bold">Partnership</h3><p className="text-sm text-zinc-400 mt-1">CSR & institutions</p></Link><Link to="/Blog" className="p-5 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition"><h3 className="font-bold">SSF Updates</h3><p className="text-sm text-zinc-400 mt-1">News & awareness</p></Link><a href={`mailto:${CONTACT_INFO.primaryEmail}`} className="p-5 rounded-2xl bg-[#FF6600] hover:bg-[#e65c00] transition"><h3 className="font-bold">Contact SSF</h3><p className="text-sm text-white/80 mt-1">Get in touch</p></a></div></div></div></section>
      <ImpactTimeline />
      <AuthModal open={authOpen} initialMode={authMode} onClose={() => setAuthOpen(false)} />
    </div>
  );
}
