import { Link } from '@tanstack/react-router'
import WorkEvidenceBanner from '../components/WorkEvidenceBanner'
import OptimizedImage from '../components/OptimizedImage'
import pageHeader from '../assets/page-header.jpg'
import { FaArrowRight, FaBookOpen, FaBullhorn, FaChild, FaFemale, FaHandsHelping, FaHeartbeat, FaLeaf, FaMapMarkerAlt, FaPeopleCarry, FaSeedling, FaUserFriends, FaLaptop, FaCertificate, FaGlobeAsia, FaShieldAlt } from 'react-icons/fa'

const initiatives = [
  { icon: FaBookOpen, title: 'SSF Learning HUB — All India', tag: 'Online | All India', description: 'An online learning and support initiative connecting children and learners through educational sessions, interaction, confidence-building activities and guidance.', points: ['Online classes', 'Subject-based learning', 'English conversation and speaking practice', 'Confidence-building and learner engagement'], link: '/LearningHub', linkText: 'Explore Learning HUB', featured: true },
  { icon: FaChild, title: 'Education & Child Development', tag: 'Learning support', description: 'We support learning opportunities, educational awareness, mentorship, communication activities and volunteer-led engagement for children and young learners.', points: ['Learning assistance', 'Educational awareness', 'Mentorship and guidance', 'Reading, speaking and communication activities'] },
  { icon: FaHandsHelping, title: 'Counselling & Guidance', tag: 'Support & awareness', description: 'General social, educational and child-focused guidance, with referrals or professional support where available.', points: ['Children’s guidance', 'Educational guidance', 'General social guidance', 'Legal information and referral guidance where available'] },
  { icon: FaHeartbeat, title: 'Health & Well-being', tag: 'Awareness & prevention', description: 'Health awareness, preventive education, hygiene awareness and community-focused health information, with referral guidance where available.', points: ['Health awareness', 'Preventive health education', 'Health and hygiene awareness', 'Referral guidance where available'] },
  { icon: FaFemale, title: 'Women Empowerment & Livelihood', tag: 'Skills & self-reliance', description: 'We promote participation, skills, opportunity awareness and pathways that may support women’s confidence and self-reliance.', points: ['Skill development awareness', 'Women’s participation', 'Livelihood guidance', 'Entrepreneurship and opportunity awareness'], link: '/SkillPrograms', linkText: 'Explore Skill Programs' },
  { icon: FaLeaf, title: 'Environment & Sustainability', tag: 'Community action', description: 'Encouraging environmental responsibility through plantation, cleanliness and sustainable-living awareness activities.', points: ['Plantation activities', 'Cleanliness awareness', 'Environmental responsibility', 'Community participation'] },
  { icon: FaSeedling, title: 'Rural & Community Development', tag: 'Grassroots participation', description: 'Community participation, rural awareness and local initiatives that contribute to a vision of more self-reliant communities.', points: ['Rural awareness', 'Community participation', 'Self-reliant village vision', 'Local support activities'] },
  { icon: FaBullhorn, title: 'Social Awareness & Public Participation', tag: 'Citizen engagement', description: 'Awareness communication and public-interest engagement encouraging responsible citizenship, rights awareness and social participation.', points: ['Public-interest awareness', 'Citizen participation', 'Social responsibility campaigns', 'Rights and responsibilities awareness'] },
]

const supportAreas = [
  ['Education', 'Learning resources and educational activities'], ['Learning HUB', 'Digital learning and student engagement'], ['Community Health', 'Local awareness and agreed screening activities'], ['Women & Livelihood', 'Skills and opportunity awareness'], ['Environment', 'Plantation and cleanliness activities'], ['Community Development', 'Participation and local initiatives'],
]

const workPrinciples = [
  { icon: FaHandsHelping, title: 'Support', text: 'Connecting people, learners, volunteers and community partners with practical opportunities for support.' },
  { icon: FaLaptop, title: 'Skill & Learning', text: 'Encouraging education, digital learning, communication, skills and confidence-building.' },
  { icon: FaBullhorn, title: 'Awareness', text: 'Sharing useful public-interest information and encouraging responsible participation.' },
  { icon: FaSeedling, title: 'Creation', text: 'Turning cooperation and ideas into constructive community initiatives wherever feasible.' },
]

const focusOutcomes = [
  ['Learn', 'Education, digital access, communication and knowledge-building'],
  ['Develop', 'Skills, confidence, participation and pathways toward self-reliance'],
  ['Care', 'Health, hygiene, well-being and community support awareness'],
  ['Participate', 'Volunteering, partnerships, citizenship and local action'],
]

export default function OurInitiativesPage() {
  return <main className="bg-white text-[#002344]">
    <section className="relative overflow-hidden bg-[#001529] px-6 pb-24 pt-36 text-white">
      <div className="absolute inset-0 z-0">
        <OptimizedImage src={pageHeader} alt="Swastik Srijan Foundation community work" className="h-full w-full" objectFit="cover" />
        <div className="absolute inset-0 bg-[#001529]/65 bg-gradient-to-b from-[#001529]/60 via-[#001529]/55 to-[#001529]/85" />
      </div>
      <div className="relative z-10 mx-auto max-w-6xl text-center">
        <p className="mb-4 text-sm font-extrabold uppercase tracking-[0.25em] text-[#FFB066]">Education • Health • Skills • Awareness • Community Development</p>
        <h1 className="text-4xl font-black tracking-tight md:text-6xl">Our Initiatives & Impact</h1>
        <p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-white/80 md:text-xl">Swastik Srijan Foundation works to create meaningful opportunities through education, health awareness, counselling, skill development, social participation and community support.</p>
        <div className="mt-9 flex flex-wrap justify-center gap-3"><Link to="/Donate" className="rounded-full bg-[#FF6600] px-7 py-3.5 font-extrabold shadow-lg transition hover:-translate-y-0.5">Support Our Work</Link><Link to="/Volunteer" className="rounded-full border border-white/30 bg-white/10 px-7 py-3.5 font-extrabold backdrop-blur transition hover:bg-white/15">Become a Volunteer</Link><Link to="/PartnerWithUs" className="rounded-full border border-white/30 px-7 py-3.5 font-extrabold transition hover:bg-white/10">Partner With Us</Link></div>
      </div>
    </section>

    <WorkEvidenceBanner page="initiatives" />

    <section className="border-b border-zinc-200 bg-white px-6 py-7"><div className="mx-auto grid max-w-6xl gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl bg-zinc-50 p-5"><FaGlobeAsia className="text-xl text-[#FF6600]" /><p className="mt-3 text-xs font-extrabold uppercase tracking-wider text-zinc-500">Reach</p><p className="mt-1 font-black">Across India</p></div><div className="rounded-2xl bg-zinc-50 p-5"><FaCertificate className="text-xl text-[#FF6600]" /><p className="mt-3 text-xs font-extrabold uppercase tracking-wider text-zinc-500">Established</p><p className="mt-1 font-black">December 2013</p></div><div className="rounded-2xl bg-zinc-50 p-5"><FaMapMarkerAlt className="text-xl text-[#FF6600]" /><p className="mt-3 text-xs font-extrabold uppercase tracking-wider text-zinc-500">Registered Office</p><p className="mt-1 font-black">Rewa, Madhya Pradesh</p></div><div className="rounded-2xl bg-zinc-50 p-5"><FaShieldAlt className="text-xl text-[#FF6600]" /><p className="mt-3 text-xs font-extrabold uppercase tracking-wider text-zinc-500">Approach</p><p className="mt-1 font-black">Responsible & Inclusive</p></div></div></section>

    <section className="px-6 py-20"><div className="mx-auto max-w-6xl">
      <div className="mx-auto mb-12 max-w-3xl text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#FF6600]">How We Work</p><h2 className="mt-2 text-3xl font-black md:text-4xl">From cooperation to meaningful action</h2><p className="mt-4 text-lg leading-8 text-zinc-600">Our work is guided by four simple ideas: support people, build skills, spread useful awareness and create constructive opportunities through community participation.</p></div>
      <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{workPrinciples.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-50 text-xl text-[#FF6600]"><Icon /></div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-600">{text}</p></article>)}</div>
    </div></section>

    <section className="bg-zinc-50 px-6 py-20"><div className="mx-auto max-w-6xl">
      <div className="mb-12 max-w-3xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#FF6600]">What We Do</p><h2 className="mt-2 text-3xl font-black md:text-4xl">A clear view of our initiatives</h2><p className="mt-4 text-lg leading-8 text-zinc-600">Our initiatives reflect the Foundation’s broad registered objectives while presenting current public-facing work in a clear and responsible way. The scope of any particular activity depends on resources, volunteers, partnerships and local requirements.</p></div>
      <div className="grid gap-6 md:grid-cols-2">{initiatives.map((item) => { const Icon = item.icon; return <article key={item.title} className={`group rounded-3xl border p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl ${item.featured ? 'border-[#FF6600]/30 bg-orange-50/40 md:col-span-2' : 'border-zinc-200 bg-white'}`}><div className="flex items-start gap-5"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-[#002344] text-2xl text-white shadow-md"><Icon /></div><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><h3 className="text-xl font-black md:text-2xl">{item.title}</h3><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-bold text-zinc-600">{item.tag}</span></div><p className="leading-7 text-zinc-600">{item.description}</p><ul className="mt-5 grid gap-2 sm:grid-cols-2">{item.points.map((point) => <li key={point} className="flex gap-2 text-sm font-semibold text-zinc-700"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#FF6600]" />{point}</li>)}</ul>{item.link && <Link to={item.link} className="mt-6 inline-flex items-center gap-2 font-extrabold text-[#002344] hover:text-[#FF6600]">{item.linkText}<FaArrowRight className="text-sm transition group-hover:translate-x-1" /></Link>}</div></div></article> })}</div>
    </div></section>

    <section className="px-6 py-20"><div className="mx-auto max-w-6xl"><div className="mb-10 text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#FF6600]">From Work to Outcomes</p><h2 className="mt-2 text-3xl font-black md:text-4xl">What our work aims to enable</h2><p className="mx-auto mt-4 max-w-3xl text-lg leading-8 text-zinc-600">We focus on practical, people-centred outcomes rather than inflated numbers. Programme outcomes and beneficiary figures are reported only when supported by available records.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{focusOutcomes.map(([title, desc]) => <div key={title} className="rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm"><div className="text-sm font-black uppercase tracking-wider text-[#FF6600]">{title}</div><p className="mt-3 leading-7 text-zinc-600">{desc}</p></div>)}</div></div></section>

    <section className="bg-zinc-50 px-6 py-20"><div className="mx-auto max-w-6xl"><div className="grid gap-10 lg:grid-cols-[1.1fr_0.9fr]">
      <div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#FF6600]">Local Collaboration</p><h2 className="mt-2 text-3xl font-black md:text-4xl">Wagholi Community Healthcare Collaboration</h2><div className="mt-5 flex items-center gap-2 font-bold text-zinc-700"><FaMapMarkerAlt className="text-[#FF6600]" /> Wagholi, Pune, Maharashtra</div><p className="mt-5 text-lg leading-8 text-zinc-600">This is a local healthcare collaboration focused on community health awareness and agreed basic screening support through a local diagnostic partner. It is not presented as a Pan-India healthcare service.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Dental check-up / oral screening', 'Blood pressure check', 'Random blood sugar', 'Weight measurement', 'Health screening support', 'Diagnostic referral support'].map((x) => <div key={x} className="rounded-2xl border border-zinc-200 bg-white p-4 font-semibold text-zinc-700 shadow-sm">{x}</div>)}</div></div>
      <div className="rounded-3xl border border-zinc-200 bg-white p-7 shadow-sm"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-50 text-xl text-[#FF6600]"><FaHeartbeat /></div><h3 className="text-xl font-black">Scope & safety note</h3><p className="mt-4 leading-7 text-zinc-600">Services are subject to availability, eligibility and the applicable agreed terms. Free, concession or other terms should only be represented where specifically agreed.</p><p className="mt-4 leading-7 text-zinc-600">Screening does not constitute diagnosis or treatment. For medical decisions, beneficiaries should consult an appropriately qualified healthcare professional.</p><Link to="/Contact" className="mt-6 inline-flex items-center gap-2 font-extrabold text-[#002344] hover:text-[#FF6600]">Contact SSF <FaArrowRight /></Link></div>
    </div></div></section>

    <section className="px-6 py-20"><div className="mx-auto max-w-6xl"><div className="rounded-[2rem] bg-[#002344] p-8 text-white shadow-xl md:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#FFB066]">Work With Us</p><h2 className="mt-2 text-3xl font-black md:text-4xl">Good work grows through cooperation</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-white/75">Volunteers, members, institutions, trainers, companies, CSR partners and community supporters can contribute according to their capacity and shared objectives.</p></div><Link to="/GetInvolved" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#FF6600] px-7 py-4 font-extrabold shadow-lg transition hover:-translate-y-0.5">Get Involved <FaArrowRight /></Link></div></div></div></section>

    <section className="px-6 pb-20"><div className="mx-auto max-w-6xl"><div className="mb-10 text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#FF6600]">Support With Purpose</p><h2 className="mt-2 text-3xl font-black md:text-4xl">Your Support Can Help Us</h2><p className="mx-auto mt-4 max-w-2xl text-zinc-600">Support may contribute to programme activities, resources and community engagement. We avoid claiming specific beneficiary outcomes unless supported by records.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{supportAreas.map(([title, desc]) => <div key={title} className="rounded-2xl border border-zinc-200 p-6"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-600">{desc}</p></div>)}</div><div className="mt-10 flex flex-wrap justify-center gap-3"><Link to="/Donate" className="inline-flex items-center gap-2 rounded-full bg-[#FF6600] px-7 py-3.5 font-extrabold text-white">Support Our Work <FaArrowRight /></Link><Link to="/GetInvolved" className="inline-flex items-center gap-2 rounded-full border-2 border-[#002344] px-7 py-3.5 font-extrabold text-[#002344]">Get Involved <FaUserFriends /></Link><Link to="/CSRPartnership" className="inline-flex items-center gap-2 rounded-full border border-zinc-300 px-7 py-3.5 font-extrabold text-zinc-700">CSR Partnership <FaPeopleCarry /></Link></div></div></section>

    <section className="border-t border-zinc-200 bg-white px-6 py-10"><div className="mx-auto max-w-5xl text-center"><p className="text-sm leading-7 text-zinc-500">Public information note: This page is a concise presentation of SSF’s areas of work and initiatives. It does not replace the Foundation’s registration documents, statutory records, programme approvals, partner agreements or activity reports.</p><Link to="/Impact" className="mt-4 inline-flex items-center gap-2 font-extrabold text-[#002344] hover:text-[#FF6600]">View Impact & Journey <FaArrowRight /></Link></div></section>
  </main>
}
