import { Link } from '@tanstack/react-router'
import { FaArrowRight, FaBookOpen, FaBullhorn, FaChild, FaFemale, FaHandsHelping, FaHeartbeat, FaLeaf, FaMapMarkerAlt, FaPeopleCarry, FaSeedling, FaUserFriends } from 'react-icons/fa'

const initiatives = [
  { icon: FaBookOpen, title: 'SSF Learning HUB — All India', tag: 'Online | All India', description: 'An online learning and support initiative connecting children and learners through educational sessions, interaction, confidence-building activities and guidance.', points: ['Online classes', 'Subject-based learning', 'English conversation and speaking practice', 'Confidence-building and learner engagement'], link: '/LearningHub', linkText: 'Explore Learning HUB', featured: true },
  { icon: FaChild, title: 'Education & Child Development', tag: 'Learning support', description: 'We support learning opportunities, educational awareness, mentorship, communication activities and volunteer-led engagement for children and young learners.', points: ['Learning assistance', 'Educational awareness', 'Mentorship and guidance', 'Reading, speaking and communication activities'] },
  { icon: FaHandsHelping, title: 'Counselling & Guidance', tag: 'Support & awareness', description: 'General social, educational and child-focused guidance, with referrals or professional support where available.', points: ['Children’s guidance', 'Educational guidance', 'General social guidance', 'Legal information and referral guidance where available'] },
  { icon: FaHeartbeat, title: 'Health & Well-being', tag: 'Awareness & prevention', description: 'Health awareness, preventive education, hygiene awareness and community-focused health information, with referral guidance where available.', points: ['Health awareness', 'Preventive health education', 'Health and hygiene awareness', 'Referral guidance where available'] },
  { icon: FaFemale, title: 'Women Empowerment & Livelihood', tag: 'Skills & self-reliance', description: 'We promote participation, skills, opportunity awareness and pathways that may support women’s confidence and self-reliance.', points: ['Skill development awareness', 'Women’s participation', 'Livelihood guidance', 'Entrepreneurship and opportunity awareness'], link: '/SkillPrograms', linkText: 'Explore Skill Programs' },
  { icon: FaLeaf, title: 'Environment & Sustainability', tag: 'Community action', description: 'Encouraging environmental responsibility through plantation, cleanliness and sustainable-living awareness activities.', points: ['Plantation activities', 'Cleanliness awareness', 'Environmental responsibility', 'Community participation'] },
  { icon: FaSeedling, title: 'Rural & Community Development', tag: 'Grassroots participation', description: 'Community participation, rural awareness and local initiatives that contribute to a vision of more self-reliant communities.', points: ['Rural awareness', 'Community participation', 'Self-reliant village vision', 'Local support activities'] },
  { icon: FaBullhorn, title: 'Social Awareness & Public Participation', tag: 'Citizen engagement', description: 'Awareness communication and public-interest engagement encouraging responsible citizenship, rights awareness and social participation.', points: ['Public-interest awareness', 'Citizen participation', 'Social responsibility campaigns', 'Rights and responsibilities awareness'] },
]

const supportAreas = [
  ['Education', 'Learning resources and educational activities'], ['Learning HUB', 'Digital learning and student engagement'], ['Community Health', 'Local awareness and agreed screening activities'], ['Women & Livelihood', 'Skills and opportunity awareness'], ['Environment', 'Plantation and cleanliness activities'], ['Community Development', 'Participation and local initiatives'],
]

export default function OurInitiativesPage() {
  return <main className="bg-white text-[#002344]">
    <section className="relative overflow-hidden bg-[#002344] px-6 pb-24 pt-36 text-white">
      <div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-[#FF6600]/20 blur-3xl" /><div className="absolute -bottom-32 -left-20 h-72 w-72 rounded-full bg-[#0a668f]/30 blur-3xl" />
      <div className="relative mx-auto max-w-6xl text-center">
        <p className="mb-4 text-sm font-extrabold uppercase tracking-[0.25em] text-[#FFB066]">Education • Health • Skills • Awareness • Community Development</p>
        <h1 className="text-4xl font-black tracking-tight md:text-6xl">Our Initiatives & Impact</h1>
        <p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-white/80 md:text-xl">Swastik Srijan Foundation works to create meaningful opportunities through education, health awareness, counselling, skill development, social participation and community support.</p>
        <div className="mt-9 flex flex-wrap justify-center gap-3"><Link to="/Donate" className="rounded-full bg-[#FF6600] px-7 py-3.5 font-extrabold shadow-lg transition hover:-translate-y-0.5">Support Our Work</Link><Link to="/Volunteer" className="rounded-full border border-white/30 bg-white/10 px-7 py-3.5 font-extrabold backdrop-blur transition hover:bg-white/15">Become a Volunteer</Link><Link to="/PartnerWithUs" className="rounded-full border border-white/30 px-7 py-3.5 font-extrabold transition hover:bg-white/10">Partner With Us</Link></div>
      </div>
    </section>

    <section className="px-6 py-20"><div className="mx-auto max-w-6xl">
      <div className="mb-12 max-w-3xl"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#FF6600]">What We Do</p><h2 className="mt-2 text-3xl font-black md:text-4xl">A clear view of our work</h2><p className="mt-4 text-lg leading-8 text-zinc-600">Each initiative is presented according to its actual scope, reach and available support. Local collaborations are kept separate from All India online initiatives.</p></div>
      <div className="grid gap-6 md:grid-cols-2">{initiatives.map((item) => { const Icon = item.icon; return <article key={item.title} className={`group rounded-3xl border p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl ${item.featured ? 'border-[#FF6600]/30 bg-orange-50/40 md:col-span-2' : 'border-zinc-200 bg-white'}`}><div className="flex items-start gap-5"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-[#002344] text-2xl text-white shadow-md"><Icon /></div><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><h3 className="text-xl font-black md:text-2xl">{item.title}</h3><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-bold text-zinc-600">{item.tag}</span></div><p className="leading-7 text-zinc-600">{item.description}</p><ul className="mt-5 grid gap-2 sm:grid-cols-2">{item.points.map((point) => <li key={point} className="flex gap-2 text-sm font-semibold text-zinc-700"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#FF6600]" />{point}</li>)}</ul>{item.link && <Link to={item.link} className="mt-6 inline-flex items-center gap-2 font-extrabold text-[#002344] hover:text-[#FF6600]">{item.linkText}<FaArrowRight className="text-sm transition group-hover:translate-x-1" /></Link>}</div></div></article> })}</div>
    </div></section>

    <section className="bg-zinc-50 px-6 py-20"><div className="mx-auto max-w-6xl"><div className="grid gap-10 lg:grid-cols-[1.1fr_0.9fr]">
      <div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#FF6600]">Local Collaboration</p><h2 className="mt-2 text-3xl font-black md:text-4xl">Wagholi Community Healthcare Collaboration</h2><div className="mt-5 flex items-center gap-2 font-bold text-zinc-700"><FaMapMarkerAlt className="text-[#FF6600]" /> Wagholi, Pune, Maharashtra</div><p className="mt-5 text-lg leading-8 text-zinc-600">This is a local healthcare collaboration focused on community health awareness and agreed basic screening support through a local diagnostic partner. It is not presented as a Pan-India healthcare service.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Dental check-up / oral screening', 'Blood pressure check', 'Random blood sugar', 'Weight measurement', 'Health screening support', 'Diagnostic referral support'].map((x) => <div key={x} className="rounded-2xl border border-zinc-200 bg-white p-4 font-semibold text-zinc-700 shadow-sm">{x}</div>)}</div></div>
      <div className="rounded-3xl border border-zinc-200 bg-white p-7 shadow-sm"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-50 text-xl text-[#FF6600]"><FaHeartbeat /></div><h3 className="text-xl font-black">Scope & safety note</h3><p className="mt-4 leading-7 text-zinc-600">Services are subject to availability, eligibility and the applicable agreed terms. Free, concession or other terms should only be represented where specifically agreed.</p><p className="mt-4 leading-7 text-zinc-600">Screening does not constitute diagnosis or treatment. For medical decisions, beneficiaries should consult an appropriately qualified healthcare professional.</p><Link to="/Contact" className="mt-6 inline-flex items-center gap-2 font-extrabold text-[#002344] hover:text-[#FF6600]">Contact SSF <FaArrowRight /></Link></div>
    </div></div></section>

    <section className="px-6 py-20"><div className="mx-auto max-w-6xl"><div className="mb-10 text-center"><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#FF6600]">Support With Purpose</p><h2 className="mt-2 text-3xl font-black md:text-4xl">Your Support Can Help Us</h2><p className="mx-auto mt-4 max-w-2xl text-zinc-600">Support may contribute to programme activities, resources and community engagement. We avoid claiming specific beneficiary outcomes unless supported by records.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{supportAreas.map(([title, desc]) => <div key={title} className="rounded-2xl border border-zinc-200 p-6"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-600">{desc}</p></div>)}</div><div className="mt-10 flex flex-wrap justify-center gap-3"><Link to="/Donate" className="inline-flex items-center gap-2 rounded-full bg-[#FF6600] px-7 py-3.5 font-extrabold text-white">Support Our Work <FaArrowRight /></Link><Link to="/GetInvolved" className="inline-flex items-center gap-2 rounded-full border-2 border-[#002344] px-7 py-3.5 font-extrabold text-[#002344]">Get Involved <FaUserFriends /></Link><Link to="/CSRPartnership" className="inline-flex items-center gap-2 rounded-full border border-zinc-300 px-7 py-3.5 font-extrabold text-zinc-700">CSR Partnership <FaPeopleCarry /></Link></div></div></section>
  </main>
}
