import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { FaArrowRight, FaBell, FaBuilding, FaCheckCircle, FaClock, FaEye, FaFileAlt, FaGraduationCap, FaHandsHelping, FaHeart, FaIdCard, FaSignOutAlt, FaShieldAlt, FaUserCircle } from "react-icons/fa";
import { API_BASE_URL, ENDPOINTS } from "../config/api";
const SESSION_KEY="ssf_user_session";
const statusClass=s=>["approved","selected","completed","paid","offline"].includes(String(s||"").toLowerCase())?"bg-emerald-100 text-emerald-700":["rejected","failed"].includes(String(s||"").toLowerCase())?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700";
const statusText=s=>String(s||"pending").replace(/_/g," ");
const dateText=d=>d?new Date(d).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";
const docLink=(href,label="Open")=>href?<a href={href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 px-3 py-2 rounded-lg bg-[#002344] text-white text-xs font-bold hover:bg-[#ff6600] transition"><FaEye/>{label}</a>:<span className="text-xs text-zinc-400">Not issued</span>;
export default function UserPortal(){
 const navigate=useNavigate();const [user,setUser]=useState(null);const [portal,setPortal]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let alive=true;(async()=>{try{const saved=JSON.parse(localStorage.getItem(SESSION_KEY)||"null");if(!saved?.id){navigate({to:"/"});return}setUser(saved);const r=await fetch(ENDPOINTS.USER_PORTAL(saved.id));if(!r.ok)throw new Error("Unable to load your portal");const d=await r.json();if(!alive)return;setPortal(d);if(d.account){const fresh={...saved,...d.account};setUser(fresh);localStorage.setItem(SESSION_KEY,JSON.stringify(fresh));window.dispatchEvent(new CustomEvent("ssf-auth-changed",{detail:fresh}))}}catch(e){if(alive)setError(e.message||"Unable to load portal")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[navigate]);
 const logout=()=>{localStorage.removeItem(SESSION_KEY);window.dispatchEvent(new CustomEvent("ssf-auth-changed",{detail:null}));navigate({to:"/"})};if(!user)return null;
 const volunteers=portal?.activities?.volunteers||[],donors=portal?.activities?.donors||[],internships=portal?.activities?.internships||[];const memberApproved=user.status==="approved"&&!!user.memberId;const approvedVolunteer=volunteers.find(v=>v.status==="approved");const selectedIntern=internships.find(i=>["selected","completed"].includes(i.status));
 const activeRoles=[memberApproved,volunteers.some(v=>v.status==="approved"),internships.some(i=>["selected","completed"].includes(i.status)),donors.some(d=>["paid","offline"].includes(String(d.paymentStatus).toLowerCase()))].filter(Boolean).length;
 const notifications=useMemo(()=>[...volunteers.map(v=>({id:`v${v.id}`,title:"Volunteer application",status:v.status,date:v.approvedAt||v.createdAt,detail:v.volunteerId||"Under review"})),...internships.map(i=>({id:`i${i.id}`,title:`Internship — ${i.internshipType}`,status:i.status,date:i.completedAt||i.selectedAt||i.createdAt,detail:i.internId||"Under review"})),...donors.map(d=>({id:`d${d.id}`,title:`Donation — ${d.donationPurpose||"General"}`,status:d.paymentStatus,date:d.createdAt,detail:d.donorId})),...(memberApproved?[{id:"member",title:"Membership",status:"approved",date:user.certificateIssuedAt||user.createdAt,detail:user.memberId}]:[])],[volunteers,internships,donors,memberApproved,user]);
 const profilePhoto=user.profilePhotoPath?( /^https?:\/\//i.test(user.profilePhotoPath)?user.profilePhotoPath:`${API_BASE_URL}${user.profilePhotoPath.startsWith("/")?"":"/"}${user.profilePhotoPath}`):null;
 const docCount=[memberApproved&&user.memberId,memberApproved&&user.certId,approvedVolunteer?.volunteerId,approvedVolunteer?.certId,...donors.filter(d=>d.receiptUrl).map(d=>d.donorId),selectedIntern?.internId,selectedIntern?.joiningLetterId,selectedIntern?.completionCertId].filter(Boolean).length;
 return <div className="min-h-screen bg-[#f6f8fa] pt-28 pb-20 px-4 sm:px-6"><div className="max-w-7xl mx-auto space-y-6">
 <header className="bg-white rounded-[2rem] border border-zinc-100 shadow-sm p-6 md:p-8 flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div className="flex items-center gap-4"><div className="w-16 h-16 rounded-2xl bg-[#002344] text-white overflow-hidden flex items-center justify-center text-3xl">{profilePhoto?<img src={profilePhoto} alt="Profile" className="w-full h-full object-cover"/>:<FaUserCircle/>}</div><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff6600]">Swastik Srijan Foundation Samiti</p><h1 className="text-2xl md:text-3xl font-black text-[#002344]">Welcome, {user.fullName}</h1><p className="text-sm text-zinc-500 mt-1">{user.email} · {user.phone||"Mobile not added"}</p></div></div><div className="flex gap-2"><button onClick={()=>navigate({to:"/Members"})} className="px-4 py-3 rounded-xl bg-zinc-100 font-bold text-[#002344]">My Profile</button><button onClick={logout} className="px-4 py-3 rounded-xl bg-[#002344] text-white font-bold inline-flex items-center gap-2"><FaSignOutAlt/> Logout</button></div></header>
 {error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded-2xl p-4 font-semibold">{error}</div>}
 <section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Stat title="Account" value={statusText(user.status||"active")} sub={user.email} dark/><Stat title="Active Roles" value={activeRoles} sub="Approved / active participation"/><Stat title="Applications" value={volunteers.length+internships.length+(user.memberType!=="general"?1:0)} sub="Submitted records"/><Stat title="Documents" value={docCount} sub="Currently available"/></section>
 <section className="bg-white rounded-[2rem] border shadow-sm p-6 md:p-8"><div className="flex items-center justify-between mb-6"><div><h2 className="text-2xl font-black text-[#002344]">My Official Identity</h2><p className="text-sm text-zinc-500 mt-1">Official cards appear only after the relevant admin approval.</p></div><FaShieldAlt className="text-[#ff6600] text-2xl"/></div>{!memberApproved&&!approvedVolunteer&&!selectedIntern?<Empty title="No official ID issued yet" text="Choose a role and complete its application. Pending applications do not receive an official identity card."/>:<div className="grid lg:grid-cols-3 gap-5">{memberApproved&&<IdentityCard title="MEMBERSHIP ID CARD" name={user.fullName} id={user.memberId} cert={user.certId} photo={profilePhoto} view={user.idCardUrl}/>} {approvedVolunteer&&<IdentityCard title="VOLUNTEER ID CARD" name={approvedVolunteer.fullName} id={approvedVolunteer.volunteerId} cert={approvedVolunteer.certId} photo={profilePhoto} view={approvedVolunteer.idCardUrl}/>} {selectedIntern?.internId&&<IdentityCard title="INTERNSHIP ID CARD" name={selectedIntern.fullName} id={selectedIntern.internId} cert={selectedIntern.completionCertId||selectedIntern.joiningLetterId} photo={profilePhoto} view={selectedIntern.idCardUrl}/>}</div>}</section>
 <section className="bg-white rounded-[2rem] border shadow-sm p-6 md:p-8"><div className="flex items-center gap-3 mb-5"><FaFileAlt className="text-[#ff6600]"/><div><h2 className="text-xl font-black text-[#002344]">My Applications & Roles</h2><p className="text-sm text-zinc-500">Each role remains independent. Approval in one role does not create another role.</p></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><Role title="Volunteer for India" icon={FaHandsHelping} active={volunteers.length>0} detail={volunteers.length?`${volunteers.length} application(s)":"Apply to serve with SSF"} href="/Volunteer"/><Role title="Become a Member" icon={FaIdCard} active={memberApproved||user.memberType!=="general"} detail={memberApproved?`Member ID: ${user.memberId}`:"Membership application"} href="/Members"/><Role title="Join as an Intern" icon={FaGraduationCap} active={internships.length>0} detail={internships.length?`${internships.length} application(s)":"Apply for internship"} href="/Internship"/><Role title="Nation-Building Movement" icon={FaHandsHelping} active={false} detail="Community participation" href="/GetInvolved#movement"/><Role title="Become a Donor" icon={FaHeart} active={donors.length>0} detail={donors.length?`${donors.length} donation record(s)":"Support SSF programmes"} href="/Donate"/><Role title="Partner with the Mission" icon={FaBuilding} active={false} detail="CSR / institutional collaboration" href="/GetInvolved#partner"/></div></section>
 <section className="grid lg:grid-cols-2 gap-6"><div className="bg-white rounded-[2rem] border shadow-sm p-6 md:p-8"><h2 className="text-xl font-black text-[#002344] mb-5">My Official Documents</h2><div className="space-y-3">{memberApproved&&<Document title="Membership ID Card" number={user.memberId} href={user.idCardUrl}/>} {memberApproved&&<Document title="Membership Certificate" number={user.certId} href={user.certificateUrl}/>} {approvedVolunteer&&<Document title="Volunteer ID Card" number={approvedVolunteer.volunteerId} href={approvedVolunteer.idCardUrl}/>} {approvedVolunteer&&<Document title="Volunteer Certificate" number={approvedVolunteer.certId} href={approvedVolunteer.certificateUrl}/>} {donors.filter(d=>d.receiptUrl).map(d=><Document key={d.id} title="Donation Receipt" number={d.donorId} href={d.receiptUrl}/>)} {selectedIntern?.internId&&<Document title="Internship ID Card" number={selectedIntern.internId} href={selectedIntern.idCardUrl}/>} {selectedIntern?.joiningLetterId&&<Document title="Internship Joining Letter" number={selectedIntern.joiningLetterId} href={selectedIntern.joiningLetterUrl}/>} {selectedIntern?.completionCertId&&<Document title="Internship Completion Certificate" number={selectedIntern.completionCertId} href={selectedIntern.completionCertificateUrl}/>} {!docCount&&<Empty title="No documents available" text="Documents appear only when they are officially issued."/>}</div></div>
 <div className="bg-white rounded-[2rem] border shadow-sm p-6 md:p-8"><h2 className="text-xl font-black text-[#002344] mb-5">Notifications & Status</h2>{loading&&<p className="p-4 bg-zinc-50 rounded-xl text-sm">Refreshing latest records…</p>}<div className="space-y-3">{notifications.length?notifications.map(n=><div key={n.id} className="p-4 rounded-xl bg-zinc-50 border border-zinc-100 flex items-start gap-3"><FaBell className="text-[#ff6600] mt-1"/><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><strong className="text-[#002344]">{n.title}</strong><span className={`px-2 py-1 rounded-full text-[10px] font-black uppercase ${statusClass(n.status)}`}>{statusText(n.status)}</span></div><p className="text-xs text-zinc-500 mt-1">{n.detail} · {dateText(n.date)}</p></div></div>):<Empty title="No activity yet" text="Your application and participation updates will appear here."/>}</div></div></section>
 <section className="bg-white rounded-[2rem] border shadow-sm p-6 md:p-8"><div className="flex items-center gap-3 mb-5"><FaHeart className="text-[#ff6600]"/><h2 className="text-xl font-black text-[#002344]">My Donations</h2></div>{donors.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-zinc-400 border-b"><th className="p-3">Date</th><th className="p-3">Purpose</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Receipt</th></tr></thead><tbody>{donors.map(d=><tr key={d.id} className="border-b last:border-0"><td className="p-3">{dateText(d.createdAt)}</td><td className="p-3">{d.donationPurpose||"General"}</td><td className="p-3 font-black">{d.amount?`₹${d.amount}`:"—"}</td><td className="p-3"><span className={`px-2 py-1 rounded-full text-[10px] font-black uppercase ${statusClass(d.paymentStatus)}`}>{statusText(d.paymentStatus)}</span></td><td className="p-3">{docLink(d.receiptUrl,"Receipt")}</td></tr>)}</tbody></table></div>:<p className="text-sm text-zinc-500 bg-zinc-50 rounded-xl p-5">No donation records linked to this account yet.</p>}</section>
 <section className="bg-white rounded-[2rem] border shadow-sm p-6 md:p-8"><div className="flex items-center gap-3 mb-5"><FaGraduationCap className="text-[#ff6600]"/><h2 className="text-xl font-black text-[#002344]">My Internship</h2></div>{internships.length?internships.map(i=><InternshipRow key={i.id} item={i}/>):<p className="text-sm text-zinc-500 bg-zinc-50 rounded-xl p-5">No internship application linked to this account.</p>}</section>
 <section className="bg-[#002344] text-white rounded-[2rem] p-6 md:p-8"><div className="flex gap-4"><FaCheckCircle className="text-emerald-300 text-2xl mt-1"/><div><h2 className="font-black text-xl">Official document lifecycle</h2><p className="text-sm text-white/70 mt-2 leading-relaxed">Application → Review → Approval / Selection → Official ID → Certificate / Receipt → Public Verification. Pending applications never receive an official document.</p></div><FaClock className="hidden sm:block ml-auto text-white/30"/></div></section>
 </div></div>;
}
function Stat({title,value,sub,dark}){return <div className={`${dark?"bg-[#002344] text-white":"bg-white"} rounded-2xl p-5 border`}><p className="text-xs uppercase tracking-widest opacity-60">{title}</p><p className="font-black text-2xl mt-2 break-all capitalize">{value}</p><p className="text-xs opacity-60 mt-1 truncate">{sub}</p></div>}
function Role({title,icon:Icon,active,detail,href}){return <a href={href} className={`rounded-2xl border p-5 hover:-translate-y-1 transition ${active?"border-emerald-200 bg-emerald-50/50":"bg-zinc-50 border-zinc-100"}`}><div className="flex justify-between"><Icon className="text-2xl text-[#002344]"/>{active&&<FaCheckCircle className="text-emerald-500"/>}</div><h3 className="font-black text-[#002344] mt-4">{title}</h3><p className="text-xs text-zinc-500 mt-2">{detail}</p><span className="text-xs font-black text-[#ff6600] inline-flex gap-1 items-center mt-4">Open <FaArrowRight/></span></a>}
function IdentityCard({title,name,id,cert,photo,view}){return <div className="rounded-2xl overflow-hidden border-2 border-[#002344] shadow-lg bg-white"><div className="bg-[#002344] text-white p-4"><p className="text-[10px] font-black tracking-[.2em]">SWASTIK SRIJAN FOUNDATION SAMITI</p><h3 className="font-black mt-1">{title}</h3></div><div className="p-5 flex gap-4"><div className="w-20 h-24 rounded-xl bg-zinc-100 overflow-hidden flex items-center justify-center text-2xl text-zinc-300">{photo?<img src={photo} alt={name} className="w-full h-full object-cover"/>:<FaUserCircle/>}</div><div className="text-sm min-w-0"><p className="font-black text-[#002344] truncate">{name}</p><p className="text-[10px] text-zinc-400 uppercase mt-2">Official ID</p><p className="font-black text-[#002344] break-all">{id}</p>{cert&&<p className="text-[10px] text-zinc-500 mt-1">Document: {cert}</p>}</div></div><div className="px-5 pb-5">{docLink(view,"View / Download ID")}</div></div>}
function Document({title,number,href}){return <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-4 rounded-xl border bg-zinc-50"><div><p className="font-black text-[#002344]">{title}</p><p className="text-xs text-zinc-500 mt-1">{number}</p></div>{docLink(href,"View / Download")}</div>}
function Empty({title,text}){return <div className="rounded-xl border border-dashed bg-zinc-50 p-5 text-center"><p className="font-black text-[#002344]">{title}</p><p className="text-xs text-zinc-500 mt-1">{text}</p></div>}
function InternshipRow({item:i}){return <div className="border rounded-2xl p-5 mb-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black text-[#002344]">{i.internshipType}</h3><p className="text-xs text-zinc-500 mt-1">{i.college} · {i.course} · {i.duration}</p></div><span className={`px-3 py-1 rounded-full text-xs font-black capitalize ${statusClass(i.status)}`}>{statusText(i.status)}</span></div><div className="grid sm:grid-cols-3 gap-3 mt-4 text-xs"><div><span className="text-zinc-400">Application</span><p className="font-bold break-all">{i.id}</p></div><div><span className="text-zinc-400">Intern ID</span><p className="font-bold">{i.internId||"Not issued"}</p></div><div><span className="text-zinc-400">Submitted</span><p className="font-bold">{dateText(i.createdAt)}</p></div></div><div className="flex flex-wrap gap-2 mt-4">{docLink(i.idCardUrl,"ID Card")}{docLink(i.joiningLetterUrl,"Joining Letter")}{docLink(i.completionCertificateUrl,"Completion Certificate")}</div></div>}
