import { useEffect, useRef, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { FaArrowRight, FaCamera, FaHeart, FaSignOutAlt, FaTrash, FaUserCircle, FaUserFriends, FaUsers, FaGraduationCap, FaCalendarAlt, FaHandshake, FaTools } from "react-icons/fa";
import { API_BASE_URL, ENDPOINTS } from "../config/api";
import UserParticipationForms from "../components/UserParticipationForms";

const SESSION_KEY = "ssf_user_session";
const statusText = (value) => { const s = String(value || "pending").toLowerCase(); const map = { approved: "Approved", selected: "Selected", completed: "Completed", paid: "Paid", offline: "Received", pending: "Under review", submitted: "Under review", rejected: "Not approved", failed: "Failed", new: "Under review", contacted: "Under review" }; return map[s] || s.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()); };
const statusClass = (value) => { const s = String(value || "").toLowerCase(); if (["approved", "selected", "completed", "paid", "offline"].includes(s)) return "bg-emerald-50 text-emerald-700 border-emerald-200"; if (["rejected", "failed"].includes(s)) return "bg-red-50 text-red-700 border-red-200"; return "bg-amber-50 text-amber-700 border-amber-200"; };
const dateText = (value) => value ? new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";
const fileUrl = (path) => path ? (/^(?:https?:\/\/|data:image\/)/i.test(path) ? path : `${API_BASE_URL}${path.startsWith("/") ? "" : "/"}${path}`) : null;

const participation = [
  { key: "volunteer", title: "Volunteer", icon: FaUserFriends, text: "Serve with SSF through the same working membership form and choose the appropriate member role." },
  { key: "membership", title: "Membership", icon: FaUsers, text: "Join SSF as a General, Active, Life or Advisory / Expert member." },
  { key: "donor", title: "Donor", icon: FaHeart, text: "Support SSF through a donation and register your donor details for record and receipt support." },
  { key: "internship", title: "Internship", icon: FaGraduationCap, text: "Learn through practical social-service and community experience." },
  { key: "activities", title: "Activities & Events", icon: FaCalendarAlt, text: "Join awareness, education, health, environment and community activities." },
  { key: "partnership", title: "Partnership & Collaboration", icon: FaHandshake, text: "Build meaningful institutional, professional, CSR or community partnerships." },
  { key: "skills", title: "Skills & Professional Support", icon: FaTools, text: "Share expertise in education, health, legal, finance, technology, media and more." },
];

export default function UserPortal() {
  const navigate = useNavigate();
  const [user, setUser] = useState(null);
  const [portal, setPortal] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [openForm, setOpenForm] = useState(null);
  const [photoFile, setPhotoFile] = useState(null);
  const [photoPreview, setPhotoPreview] = useState(null);
  const [photoBusy, setPhotoBusy] = useState(false);
  const [photoMessage, setPhotoMessage] = useState("");
  const fileRef = useRef(null);

  const refresh = async (saved) => {
    const response = await fetch(ENDPOINTS.USER_PORTAL(saved.id));
    if (!response.ok) throw new Error("Unable to load your portal");
    const data = await response.json();
    setPortal(data);
    if (data.account) {
      const fresh = { ...saved, ...data.account };
      setUser(fresh);
      localStorage.setItem(SESSION_KEY, JSON.stringify(fresh));
      window.dispatchEvent(new CustomEvent("ssf-auth-changed", { detail: fresh }));
    }
  };

  useEffect(() => { let alive = true; (async () => { try { const saved = JSON.parse(localStorage.getItem(SESSION_KEY) || "null"); if (!saved?.id) { navigate({ to: "/" }); return; } setUser(saved); await refresh(saved); } catch (e) { if (alive) setError(e.message || "Unable to load portal"); } finally { if (alive) setLoading(false); } })(); return () => { alive = false; }; }, [navigate]);
  useEffect(() => () => { if (photoPreview) URL.revokeObjectURL(photoPreview); }, [photoPreview]);
  const logout = () => { localStorage.removeItem(SESSION_KEY); window.dispatchEvent(new CustomEvent("ssf-auth-changed", { detail: null })); navigate({ to: "/" }); };
  const choosePhoto = (event) => { const file = event.target.files?.[0]; if (!file) return; setPhotoMessage(""); if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) { setPhotoMessage("JPG, PNG or WebP photo only."); event.target.value = ""; return; } if (file.size > 2 * 1024 * 1024) { setPhotoMessage("Photo must be 2MB or smaller."); event.target.value = ""; return; } setPhotoFile(file); setPhotoPreview(URL.createObjectURL(file)); };
  const savePhoto = async () => { if (!photoFile || !user?.id) return; setPhotoBusy(true); setPhotoMessage(""); try { const data = new FormData(); data.append("profilePhoto", photoFile); const response = await fetch(ENDPOINTS.MEMBER_PROFILE_PHOTO(user.id), { method: "PATCH", body: data }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Unable to upload photo"); const fresh = { ...user, profilePhotoPath: result.profilePhotoPath }; setUser(fresh); localStorage.setItem(SESSION_KEY, JSON.stringify(fresh)); window.dispatchEvent(new CustomEvent("ssf-auth-changed", { detail: fresh })); setPhotoFile(null); setPhotoPreview(null); if (fileRef.current) fileRef.current.value = ""; setPhotoMessage("Profile photo updated."); } catch (e) { setPhotoMessage(e.message || "Unable to upload photo."); } finally { setPhotoBusy(false); } };
  const removePhoto = async () => { if (!user?.id || !user.profilePhotoPath) return; setPhotoBusy(true); setPhotoMessage(""); try { const response = await fetch(ENDPOINTS.MEMBER_PROFILE_PHOTO(user.id), { method: "DELETE" }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Unable to remove photo"); const fresh = { ...user, profilePhotoPath: null }; setUser(fresh); localStorage.setItem(SESSION_KEY, JSON.stringify(fresh)); window.dispatchEvent(new CustomEvent("ssf-auth-changed", { detail: fresh })); setPhotoMessage("Profile photo removed."); } catch (e) { setPhotoMessage(e.message || "Unable to remove photo."); } finally { setPhotoBusy(false); } };
  if (!user) return null;
  const volunteers = portal?.activities?.volunteers || []; const donors = portal?.activities?.donors || []; const internships = portal?.activities?.internships || []; const interests = portal?.activities?.interests || [];
  const memberApproved = user.status === "approved" && !!user.memberId; const approvedVolunteer = volunteers.find((item) => item.status === "approved"); const selectedIntern = internships.find((item) => ["selected", "completed"].includes(item.status)); const photo = fileUrl(user.profilePhotoPath); const displayPhoto = photoPreview || photo;
  const documents = [memberApproved && { title: "Membership ID Card", id: user.memberId, href: user.idCardUrl }, memberApproved && { title: "Membership Certificate", id: user.certId, href: user.certificateUrl }, approvedVolunteer && { title: "Volunteer ID Card", id: approvedVolunteer.volunteerId, href: approvedVolunteer.idCardUrl }, approvedVolunteer && { title: "Volunteer Certificate", id: approvedVolunteer.certId, href: approvedVolunteer.certificateUrl }, ...donors.filter((item) => item.receiptUrl).map((item) => ({ title: "Donation Receipt", id: item.donorId, href: item.receiptUrl })), selectedIntern?.internId && { title: "Internship ID Card", id: selectedIntern.internId, href: selectedIntern.idCardUrl }, selectedIntern?.joiningLetterId && { title: "Internship Joining Letter", id: selectedIntern.joiningLetterId, href: selectedIntern.joiningLetterUrl }, selectedIntern?.completionCertId && { title: "Internship Completion Certificate", id: selectedIntern.completionCertId, href: selectedIntern.completionCertificateUrl }].filter(Boolean);
  const genericInterestCount = interests.filter((item) => ["movement", "partner"].includes(item.interestType)).length; const applicationCount = volunteers.length + internships.length + genericInterestCount + (user.memberType && user.memberType !== "general" ? 1 : 0); const activeRoleCount = [memberApproved, !!approvedVolunteer, !!selectedIntern, donors.some((item) => ["paid", "offline"].includes(String(item.paymentStatus).toLowerCase()))].filter(Boolean).length;

  return <main className="min-h-screen bg-[#f6f8fa] pt-28 pb-16 px-4 sm:px-6"><div className="max-w-6xl mx-auto space-y-5"><header className="bg-white rounded-3xl border shadow-sm p-5 md:p-7 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-center gap-4"><Avatar src={displayPhoto} /><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#ff6600]">My SSF</p><h1 className="text-2xl md:text-3xl font-black text-[#002344]">Welcome, {user.fullName}</h1><p className="text-sm text-zinc-500 mt-1">{user.email}{user.phone ? ` · ${user.phone}` : ""}</p></div></div><button onClick={logout} className="self-start sm:self-auto px-4 py-2.5 rounded-xl bg-[#002344] text-white font-bold inline-flex items-center gap-2"><FaSignOutAlt /> Logout</button></header>
  {error && <div className="bg-red-50 border border-red-200 text-red-700 rounded-2xl p-4 font-semibold">{error}</div>}
  <section className="bg-white rounded-3xl border shadow-sm p-5 md:p-7"><div className="flex flex-col md:flex-row md:items-center gap-6"><div className="relative shrink-0"><Avatar src={displayPhoto} large /><button type="button" onClick={() => fileRef.current?.click()} disabled={photoBusy} aria-label="Change profile photo" className="absolute -bottom-2 -right-2 w-10 h-10 rounded-full bg-[#ff6600] text-white flex items-center justify-center shadow"><FaCamera /></button></div><div className="flex-1"><p className="text-xs font-black uppercase tracking-[.18em] text-[#ff6600]">My Profile</p><h2 className="text-2xl font-black text-[#002344] mt-1">{user.fullName}</h2><div className="grid sm:grid-cols-2 gap-2 mt-3 text-sm"><p><span className="text-zinc-400">Email:</span> <strong>{user.email}</strong></p><p><span className="text-zinc-400">Phone:</span> <strong>{user.phone || "Not added"}</strong></p><p><span className="text-zinc-400">Account:</span> <strong>{statusText(user.status || "active")}</strong></p><p><span className="text-zinc-400">Member ID:</span> <strong>{user.memberId || "Not issued"}</strong></p></div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={choosePhoto} className="hidden" /><div className="flex flex-wrap gap-2 mt-4"><button type="button" onClick={() => fileRef.current?.click()} disabled={photoBusy} className="px-4 py-2 rounded-xl bg-[#002344] text-white text-sm font-bold">Change Photo</button>{photoFile && <button type="button" onClick={savePhoto} disabled={photoBusy} className="px-4 py-2 rounded-xl bg-emerald-600 text-white text-sm font-bold">{photoBusy ? "Saving…" : "Save Photo"}</button>}{photo && <button type="button" onClick={removePhoto} disabled={photoBusy} className="px-4 py-2 rounded-xl bg-zinc-100 text-red-600 text-sm font-bold inline-flex items-center gap-2"><FaTrash /> Remove</button>}</div>{photoMessage && <p className="text-sm text-zinc-500 mt-2">{photoMessage}</p>}</div></div></section>
  <section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Summary title="Account" value={statusText(user.status || "active")} /><Summary title="Active roles" value={activeRoleCount} /><Summary title="Applications" value={applicationCount} /><Summary title="Documents" value={documents.length} /></section>
  <section className="bg-white rounded-3xl border shadow-sm p-5 md:p-7"><div className="mb-5"><h2 className="text-xl font-black text-[#002344]">My SSF Participation</h2><p className="text-sm text-zinc-500 mt-1">Choose any way you would like to participate. The form opens right here.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{participation.map((item) => { const Icon = item.icon; const existing = item.key === "volunteer" ? volunteers.length : item.key === "internship" ? internships.length : item.key === "membership" ? memberApproved : interests.some((i) => i.category === item.title); return <button key={item.key} type="button" onClick={() => setOpenForm(item.key)} className="text-left group rounded-2xl border border-zinc-200 p-5 hover:border-[#ff6600] hover:-translate-y-1 hover:shadow-lg transition bg-white"><div className="flex items-start justify-between gap-3"><div className="w-11 h-11 rounded-2xl bg-orange-50 text-[#ff6600] flex items-center justify-center text-lg"><Icon /></div><FaArrowRight className="text-zinc-300 group-hover:text-[#ff6600] mt-2 transition" /></div><h3 className="font-black text-[#002344] mt-5">{item.title}</h3><p className="text-sm text-zinc-500 mt-2 min-h-[48px]">{item.text}</p><div className="mt-4 text-xs font-black text-[#ff6600]">{existing ? "Open & manage" : "Start form"} <span className="ml-1">→</span></div></button>; })}</div></section>
  {donors.length > 0 && <section className="bg-white rounded-3xl border shadow-sm p-5 md:p-7"><h2 className="text-xl font-black text-[#002344] mb-4">My Donations</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-zinc-400 border-b"><th className="p-3">Date</th><th className="p-3">Purpose</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Receipt</th></tr></thead><tbody>{donors.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-3">{dateText(item.createdAt)}</td><td className="p-3">{item.donationPurpose || "General"}</td><td className="p-3 font-bold">{item.amount ? `₹${item.amount}` : "—"}</td><td className="p-3"><span className={`px-2 py-1 rounded-full border text-[10px] font-black ${statusClass(item.paymentStatus)}`}>{statusText(item.paymentStatus)}</span></td><td className="p-3">{item.receiptUrl ? <a href={item.receiptUrl} target="_blank" rel="noreferrer" className="text-[#ff6600] font-bold">View receipt</a> : <span className="text-zinc-400">Not issued</span>}</td></tr>)}</tbody></table></div></section>}
  {documents.length > 0 && <section className="bg-white rounded-3xl border shadow-sm p-5 md:p-7"><h2 className="text-xl font-black text-[#002344] mb-4">My Documents</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{documents.map((doc, index) => <div key={`${doc.title}-${doc.id || index}`} className="border rounded-2xl p-4 flex items-center justify-between gap-3"><div><p className="font-black text-[#002344]">{doc.title}</p><p className="text-xs text-zinc-400 mt-1">{doc.id || "Available"}</p></div>{doc.href ? <a href={fileUrl(doc.href)} target="_blank" rel="noreferrer" className="text-[#ff6600] font-bold text-sm inline-flex items-center gap-1">Open <FaArrowRight /></a> : <span className="text-xs text-zinc-400">Pending</span>}</div>)}</div></section>}
  <div className="text-center pt-2"><button onClick={logout} className="text-sm font-bold text-zinc-400 hover:text-red-600 inline-flex items-center gap-2"><FaSignOutAlt /> Logout</button></div>
  </div><UserParticipationForms openForm={openForm} onClose={() => setOpenForm(null)} user={user} /></main>;
}

function Summary({ title, value }) { return <div className="bg-white rounded-2xl border shadow-sm p-5"><p className="text-xs font-black uppercase tracking-wider text-zinc-400">{title}</p><p className="text-2xl font-black text-[#002344] mt-2">{value}</p></div>; }
function Avatar({ src, large = false }) { return <div className={`${large ? "w-28 h-28 text-4xl" : "w-14 h-14 text-xl"} rounded-full overflow-hidden bg-zinc-100 text-zinc-400 flex items-center justify-center border-4 border-white shadow`}>{src ? <img src={src} alt="Profile" className="w-full h-full object-cover" /> : <FaUserCircle />}</div>; }