import { useEffect, useState } from "react";
import { useParams } from "@tanstack/react-router";
import { FaCheckCircle, FaShieldAlt, FaTimesCircle } from "react-icons/fa";
import { ENDPOINTS } from "../config/api";

export default function VerifyDocument(){
 const {code}=useParams({strict:false}); const [data,setData]=useState(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const r=await fetch(ENDPOINTS.VERIFY(code));const d=await r.json();setData(r.ok?d:{valid:false,message:d.message})}catch{setData({valid:false,message:"Verification service unavailable."})}finally{setLoading(false)}})()},[code]);
 return <main className="min-h-screen bg-[#f5f8fa] pt-32 pb-20 px-4"><div className="max-w-2xl mx-auto"><div className="bg-white rounded-[2rem] shadow-xl border overflow-hidden"><div className="bg-[#002344] text-white p-7 text-center"><FaShieldAlt className="mx-auto text-4xl text-[#ff6600]"/><p className="text-xs tracking-[.25em] font-black mt-4">SWASTIK SRIJAN FOUNDATION SAMITI</p><h1 className="text-3xl font-black mt-2">Document Verification</h1><p className="text-white/60 text-sm mt-2">Official online verification</p></div><div className="p-7 md:p-10">{loading?<p className="text-center text-zinc-500">Checking document…</p>:data?.valid?<><div className="flex items-center gap-3 text-emerald-600"><FaCheckCircle className="text-3xl"/><div><p className="font-black text-xl">Verified & Valid</p><p className="text-xs text-zinc-500">This record is present in the official SSF verification system.</p></div></div><div className="mt-7 space-y-3"><Info label="Document Type" value={data.type}/><Info label="Name" value={data.name}/><Info label="Official ID" value={data.officialId}/><Info label="Document ID" value={data.documentId}/><Info label="Category / Role" value={data.category}/><Info label="Issued / Approved" value={data.issuedAt?new Date(data.issuedAt).toLocaleDateString("en-IN"):"—"}/></div></>:<div className="text-center"><FaTimesCircle className="mx-auto text-4xl text-red-500"/><h2 className="font-black text-xl text-[#002344] mt-4">Document Not Verified</h2><p className="text-sm text-zinc-500 mt-2">{data?.message||"No matching official record was found."}</p></div>}<p className="text-[11px] text-zinc-400 text-center mt-8 break-all">Verification code: {code}</p></div></div></div></main>;
}
function Info({label,value}){return <div className="flex flex-col sm:flex-row sm:justify-between gap-1 rounded-xl bg-zinc-50 border p-4"><span className="text-xs text-zinc-400 uppercase tracking-wider">{label}</span><strong className="text-sm text-[#002344] text-right break-all">{value||"—"}</strong></div>}
