/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as InstitutionalDnaRouteImport } from './routes/institutional-dna'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as VolunteerRouteImport } from './routes/Volunteer'
import { Route as VisionRouteImport } from './routes/Vision'
import { Route as UserPortalRouteImport } from './routes/UserPortal'
import { Route as UpcomingProjectsRouteImport } from './routes/UpcomingProjects'
import { Route as TransparencyRouteImport } from './routes/Transparency'
import { Route as TermsAndConditionsRouteImport } from './routes/TermsAndConditions'
import { Route as TeamRouteImport } from './routes/Team'
import { Route as StoriesRouteImport } from './routes/Stories'
import { Route as SkillProgramsRouteImport } from './routes/SkillPrograms'
import { Route as SSFNationalAcademyRouteImport } from './routes/SSFNationalAcademy'
import { Route as SSFDigitalOfficeRouteImport } from './routes/SSFDigitalOffice'
import { Route as RegistrationDetailsRouteImport } from './routes/RegistrationDetails'
import { Route as RefundPolicyRouteImport } from './routes/RefundPolicy'
import { Route as RefundAndCancellationRouteImport } from './routes/RefundAndCancellation'
import { Route as PrivacyPolicyRouteImport } from './routes/PrivacyPolicy'
import { Route as PartnerWithUsRouteImport } from './routes/PartnerWithUs'
import { Route as OurInitiativesRouteImport } from './routes/OurInitiatives'
import { Route as ObjectivesRouteImport } from './routes/Objectives'
import { Route as MissionRouteImport } from './routes/Mission'
import { Route as MemorandumAndRulesRouteImport } from './routes/MemorandumAndRules'
import { Route as MembersRouteImport } from './routes/Members'
import { Route as MemberDashboardRouteImport } from './routes/MemberDashboard'
import { Route as MediaRouteImport } from './routes/Media'
import { Route as LegalPoliciesRouteImport } from './routes/LegalPolicies'
import { Route as LearningHubRouteImport } from './routes/LearningHub'
import { Route as LearningCertificateVerifyRouteImport } from './routes/LearningCertificateVerify'
import { Route as JourneyRouteImport } from './routes/Journey'
import { Route as JoinUsRouteImport } from './routes/JoinUs'
import { Route as JoinRouteImport } from './routes/Join'
import { Route as InternshipRouteImport } from './routes/Internship'
import { Route as ImpactRouteImport } from './routes/Impact'
import { Route as HumanityChar38TruthRouteImport } from './routes/Humanity&Truth'
import { Route as GetInvolvedRouteImport } from './routes/GetInvolved'
import { Route as DonorRouteImport } from './routes/Donor'
import { Route as DonationRefundPolicyRouteImport } from './routes/DonationRefundPolicy'
import { Route as DonateAndSupportRouteImport } from './routes/DonateAndSupport'
import { Route as DonateRouteImport } from './routes/Donate'
import { Route as CookiePolicyRouteImport } from './routes/CookiePolicy'
import { Route as ContactRouteImport } from './routes/Contact'
import { Route as CampaignsRouteImport } from './routes/Campaigns'
import { Route as CampaignRouteImport } from './routes/Campaign'
import { Route as CSRPartnershipRouteImport } from './routes/CSRPartnership'
import { Route as BlogRouteImport } from './routes/Blog'
import { Route as AdminPortalRouteImport } from './routes/AdminPortal'
import { Route as AboutRouteImport } from './routes/About'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImsIndexRouteImport } from './routes/ims/index'
import { Route as LearningHubIndexRouteImport } from './routes/LearningHub/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as VerifyCertIdRouteImport } from './routes/verify.$certId'
import { Route as ImsUsersRouteImport } from './routes/ims/users'
import { Route as ImsSocialRouteImport } from './routes/ims/social'
import { Route as ImsSeparationsRouteImport } from './routes/ims/separations'
import { Route as ImsSearchRouteImport } from './routes/ims/search'
import { Route as ImsReportsRouteImport } from './routes/ims/reports'
import { Route as ImsRegistersRouteImport } from './routes/ims/registers'
import { Route as ImsProcurementRouteImport } from './routes/ims/procurement'
import { Route as ImsPoliciesRouteImport } from './routes/ims/policies'
import { Route as ImsPermissionsRouteImport } from './routes/ims/permissions'
import { Route as ImsOrgProfileRouteImport } from './routes/ims/org-profile'
import { Route as ImsOfficialDocumentsRouteImport } from './routes/ims/official-documents'
import { Route as ImsOfficeRouteImport } from './routes/ims/office'
import { Route as ImsNotificationsRouteImport } from './routes/ims/notifications'
import { Route as ImsMembershipContributionsRouteImport } from './routes/ims/membership-contributions'
import { Route as ImsMembersRouteImport } from './routes/ims/members'
import { Route as ImsMeetingsRouteImport } from './routes/ims/meetings'
import { Route as ImsManagingCommitteeRouteImport } from './routes/ims/managing-committee'
import { Route as ImsLearningCertificatesRouteImport } from './routes/ims/learning-certificates'
import { Route as ImsKnowledgeRouteImport } from './routes/ims/knowledge'
import { Route as ImsIntegrityRouteImport } from './routes/ims/integrity'
import { Route as ImsImpactRouteImport } from './routes/ims/impact'
import { Route as ImsHistoryRouteImport } from './routes/ims/history'
import { Route as ImsDownloadCenterRouteImport } from './routes/ims/download-center'
import { Route as ImsDonorSlipsRouteImport } from './routes/ims/donor-slips'
import { Route as ImsDataRouteImport } from './routes/ims/data'
import { Route as ImsConstitutionRouteImport } from './routes/ims/constitution'
import { Route as ImsCashBookRouteImport } from './routes/ims/cash-book'
import { Route as ImsCasesRouteImport } from './routes/ims/cases'
import { Route as ImsBankBookRouteImport } from './routes/ims/bank-book'
import { Route as ImsAuditTrailRouteImport } from './routes/ims/audit-trail'
import { Route as ImsAppointmentLettersRouteImport } from './routes/ims/appointment-letters'
import { Route as ImsActivitiesRouteImport } from './routes/ims/activities'
import { Route as LearningHubMyLearningRouteImport } from './routes/LearningHub/my-learning'
import { Route as LearningHubKnowledgeWorldRouteImport } from './routes/LearningHub/knowledge-world'
import { Route as LearningHubExploreRouteImport } from './routes/LearningHub/explore'
import { Route as BlogTopicRouteImport } from './routes/Blog/$topic'
import { Route as ImsFinanceIndexRouteImport } from './routes/ims/finance/index'
import { Route as ImsSectionsSectionRouteImport } from './routes/ims/sections/$section'
import { Route as ImsRResourceRouteImport } from './routes/ims/r/$resource'
import { Route as ImsPersonIdRouteImport } from './routes/ims/person/$id'
import { Route as ImsMemberIdRouteImport } from './routes/ims/member/$id'
import { Route as ImsLegacyModuleRouteImport } from './routes/ims/legacy/$module'
import { Route as ImsFinanceReceiptsPaymentsRouteImport } from './routes/ims/finance/receipts-payments'
import { Route as ImsFinanceLedgerRouteImport } from './routes/ims/finance/ledger'
import { Route as ImsFinanceCostCentresRouteImport } from './routes/ims/finance/cost-centres'
import { Route as LearningHubCourseSubjectIdRouteImport } from './routes/LearningHub/course.$subjectId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalDnaRoute = InstitutionalDnaRouteImport.update({
  id: '/institutional-dna',
  path: '/institutional-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/Volunteer',
  path: '/Volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/Vision',
  path: '/Vision',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPortalRoute = UserPortalRouteImport.update({
  id: '/UserPortal',
  path: '/UserPortal',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingProjectsRoute = UpcomingProjectsRouteImport.update({
  id: '/UpcomingProjects',
  path: '/UpcomingProjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/Transparency',
  path: '/Transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/TermsAndConditions',
  path: '/TermsAndConditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/Team',
  path: '/Team',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/Stories',
  path: '/Stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillProgramsRoute = SkillProgramsRouteImport.update({
  id: '/SkillPrograms',
  path: '/SkillPrograms',
  getParentRoute: () => rootRouteImport,
} as any)
const SSFNationalAcademyRoute = SSFNationalAcademyRouteImport.update({
  id: '/SSFNationalAcademy',
  path: '/SSFNationalAcademy',
  getParentRoute: () => rootRouteImport,
} as any)
const SSFDigitalOfficeRoute = SSFDigitalOfficeRouteImport.update({
  id: '/SSFDigitalOffice',
  path: '/SSFDigitalOffice',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationDetailsRoute = RegistrationDetailsRouteImport.update({
  id: '/RegistrationDetails',
  path: '/RegistrationDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/RefundPolicy',
  path: '/RefundPolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundAndCancellationRoute = RefundAndCancellationRouteImport.update({
  id: '/RefundAndCancellation',
  path: '/RefundAndCancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/PrivacyPolicy',
  path: '/PrivacyPolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithUsRoute = PartnerWithUsRouteImport.update({
  id: '/PartnerWithUs',
  path: '/PartnerWithUs',
  getParentRoute: () => rootRouteImport,
} as any)
const OurInitiativesRoute = OurInitiativesRouteImport.update({
  id: '/OurInitiatives',
  path: '/OurInitiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/Objectives',
  path: '/Objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/Mission',
  path: '/Mission',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorandumAndRulesRoute = MemorandumAndRulesRouteImport.update({
  id: '/MemorandumAndRules',
  path: '/MemorandumAndRules',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/Members',
  path: '/Members',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/MemberDashboard',
  path: '/MemberDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/Media',
  path: '/Media',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPoliciesRoute = LegalPoliciesRouteImport.update({
  id: '/LegalPolicies',
  path: '/LegalPolicies',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningHubRoute = LearningHubRouteImport.update({
  id: '/LearningHub',
  path: '/LearningHub',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCertificateVerifyRoute =
  LearningCertificateVerifyRouteImport.update({
    id: '/LearningCertificateVerify',
    path: '/LearningCertificateVerify',
    getParentRoute: () => rootRouteImport,
  } as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/Journey',
  path: '/Journey',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/JoinUs',
  path: '/JoinUs',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/Join',
  path: '/Join',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipRoute = InternshipRouteImport.update({
  id: '/Internship',
  path: '/Internship',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/Impact',
  path: '/Impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanityChar38TruthRoute = HumanityChar38TruthRouteImport.update({
  id: '/Humanity&Truth',
  path: '/Humanity&Truth',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/GetInvolved',
  path: '/GetInvolved',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorRoute = DonorRouteImport.update({
  id: '/Donor',
  path: '/Donor',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationRefundPolicyRoute = DonationRefundPolicyRouteImport.update({
  id: '/DonationRefundPolicy',
  path: '/DonationRefundPolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateAndSupportRoute = DonateAndSupportRouteImport.update({
  id: '/DonateAndSupport',
  path: '/DonateAndSupport',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/Donate',
  path: '/Donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/CookiePolicy',
  path: '/CookiePolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/Campaigns',
  path: '/Campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/Campaign',
  path: '/Campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CSRPartnershipRoute = CSRPartnershipRouteImport.update({
  id: '/CSRPartnership',
  path: '/CSRPartnership',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/Blog',
  path: '/Blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalRoute = AdminPortalRouteImport.update({
  id: '/AdminPortal',
  path: '/AdminPortal',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsIndexRoute = ImsIndexRouteImport.update({
  id: '/ims/',
  path: '/ims/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningHubIndexRoute = LearningHubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearningHubRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertIdRoute = VerifyCertIdRouteImport.update({
  id: '/verify/$certId',
  path: '/verify/$certId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsUsersRoute = ImsUsersRouteImport.update({
  id: '/ims/users',
  path: '/ims/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsSocialRoute = ImsSocialRouteImport.update({
  id: '/ims/social',
  path: '/ims/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsSeparationsRoute = ImsSeparationsRouteImport.update({
  id: '/ims/separations',
  path: '/ims/separations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsSearchRoute = ImsSearchRouteImport.update({
  id: '/ims/search',
  path: '/ims/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsReportsRoute = ImsReportsRouteImport.update({
  id: '/ims/reports',
  path: '/ims/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsRegistersRoute = ImsRegistersRouteImport.update({
  id: '/ims/registers',
  path: '/ims/registers',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsProcurementRoute = ImsProcurementRouteImport.update({
  id: '/ims/procurement',
  path: '/ims/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsPoliciesRoute = ImsPoliciesRouteImport.update({
  id: '/ims/policies',
  path: '/ims/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsPermissionsRoute = ImsPermissionsRouteImport.update({
  id: '/ims/permissions',
  path: '/ims/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsOrgProfileRoute = ImsOrgProfileRouteImport.update({
  id: '/ims/org-profile',
  path: '/ims/org-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsOfficialDocumentsRoute = ImsOfficialDocumentsRouteImport.update({
  id: '/ims/official-documents',
  path: '/ims/official-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsOfficeRoute = ImsOfficeRouteImport.update({
  id: '/ims/office',
  path: '/ims/office',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsNotificationsRoute = ImsNotificationsRouteImport.update({
  id: '/ims/notifications',
  path: '/ims/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsMembershipContributionsRoute =
  ImsMembershipContributionsRouteImport.update({
    id: '/ims/membership-contributions',
    path: '/ims/membership-contributions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImsMembersRoute = ImsMembersRouteImport.update({
  id: '/ims/members',
  path: '/ims/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsMeetingsRoute = ImsMeetingsRouteImport.update({
  id: '/ims/meetings',
  path: '/ims/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsManagingCommitteeRoute = ImsManagingCommitteeRouteImport.update({
  id: '/ims/managing-committee',
  path: '/ims/managing-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsLearningCertificatesRoute = ImsLearningCertificatesRouteImport.update({
  id: '/ims/learning-certificates',
  path: '/ims/learning-certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsKnowledgeRoute = ImsKnowledgeRouteImport.update({
  id: '/ims/knowledge',
  path: '/ims/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsIntegrityRoute = ImsIntegrityRouteImport.update({
  id: '/ims/integrity',
  path: '/ims/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsImpactRoute = ImsImpactRouteImport.update({
  id: '/ims/impact',
  path: '/ims/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsHistoryRoute = ImsHistoryRouteImport.update({
  id: '/ims/history',
  path: '/ims/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsDownloadCenterRoute = ImsDownloadCenterRouteImport.update({
  id: '/ims/download-center',
  path: '/ims/download-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsDonorSlipsRoute = ImsDonorSlipsRouteImport.update({
  id: '/ims/donor-slips',
  path: '/ims/donor-slips',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsDataRoute = ImsDataRouteImport.update({
  id: '/ims/data',
  path: '/ims/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsConstitutionRoute = ImsConstitutionRouteImport.update({
  id: '/ims/constitution',
  path: '/ims/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsCashBookRoute = ImsCashBookRouteImport.update({
  id: '/ims/cash-book',
  path: '/ims/cash-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsCasesRoute = ImsCasesRouteImport.update({
  id: '/ims/cases',
  path: '/ims/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsBankBookRoute = ImsBankBookRouteImport.update({
  id: '/ims/bank-book',
  path: '/ims/bank-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsAuditTrailRoute = ImsAuditTrailRouteImport.update({
  id: '/ims/audit-trail',
  path: '/ims/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsAppointmentLettersRoute = ImsAppointmentLettersRouteImport.update({
  id: '/ims/appointment-letters',
  path: '/ims/appointment-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsActivitiesRoute = ImsActivitiesRouteImport.update({
  id: '/ims/activities',
  path: '/ims/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningHubMyLearningRoute = LearningHubMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => LearningHubRoute,
} as any)
const LearningHubKnowledgeWorldRoute =
  LearningHubKnowledgeWorldRouteImport.update({
    id: '/knowledge-world',
    path: '/knowledge-world',
    getParentRoute: () => LearningHubRoute,
  } as any)
const LearningHubExploreRoute = LearningHubExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => LearningHubRoute,
} as any)
const BlogTopicRoute = BlogTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => BlogRoute,
} as any)
const ImsFinanceIndexRoute = ImsFinanceIndexRouteImport.update({
  id: '/ims/finance/',
  path: '/ims/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsSectionsSectionRoute = ImsSectionsSectionRouteImport.update({
  id: '/ims/sections/$section',
  path: '/ims/sections/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsRResourceRoute = ImsRResourceRouteImport.update({
  id: '/ims/r/$resource',
  path: '/ims/r/$resource',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsPersonIdRoute = ImsPersonIdRouteImport.update({
  id: '/ims/person/$id',
  path: '/ims/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsMemberIdRoute = ImsMemberIdRouteImport.update({
  id: '/ims/member/$id',
  path: '/ims/member/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsLegacyModuleRoute = ImsLegacyModuleRouteImport.update({
  id: '/ims/legacy/$module',
  path: '/ims/legacy/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsFinanceReceiptsPaymentsRoute =
  ImsFinanceReceiptsPaymentsRouteImport.update({
    id: '/ims/finance/receipts-payments',
    path: '/ims/finance/receipts-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImsFinanceLedgerRoute = ImsFinanceLedgerRouteImport.update({
  id: '/ims/finance/ledger',
  path: '/ims/finance/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ImsFinanceCostCentresRoute = ImsFinanceCostCentresRouteImport.update({
  id: '/ims/finance/cost-centres',
  path: '/ims/finance/cost-centres',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningHubCourseSubjectIdRoute =
  LearningHubCourseSubjectIdRouteImport.update({
    id: '/course/$subjectId',
    path: '/course/$subjectId',
    getParentRoute: () => LearningHubRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/AdminPortal': typeof AdminPortalRoute
  '/Blog': typeof BlogRouteWithChildren
  '/CSRPartnership': typeof CSRPartnershipRoute
  '/Campaign': typeof CampaignRoute
  '/Campaigns': typeof CampaignsRoute
  '/Contact': typeof ContactRoute
  '/CookiePolicy': typeof CookiePolicyRoute
  '/Donate': typeof DonateRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
  '/DonationRefundPolicy': typeof DonationRefundPolicyRoute
  '/Donor': typeof DonorRoute
  '/GetInvolved': typeof GetInvolvedRoute
  '/Humanity&Truth': typeof HumanityChar38TruthRoute
  '/Impact': typeof ImpactRoute
  '/Internship': typeof InternshipRoute
  '/Join': typeof JoinRoute
  '/JoinUs': typeof JoinUsRoute
  '/Journey': typeof JourneyRoute
  '/LearningCertificateVerify': typeof LearningCertificateVerifyRoute
  '/LearningHub': typeof LearningHubRouteWithChildren
  '/LegalPolicies': typeof LegalPoliciesRoute
  '/Media': typeof MediaRoute
  '/MemberDashboard': typeof MemberDashboardRoute
  '/Members': typeof MembersRoute
  '/MemorandumAndRules': typeof MemorandumAndRulesRoute
  '/Mission': typeof MissionRoute
  '/Objectives': typeof ObjectivesRoute
  '/OurInitiatives': typeof OurInitiativesRoute
  '/PartnerWithUs': typeof PartnerWithUsRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/RefundAndCancellation': typeof RefundAndCancellationRoute
  '/RefundPolicy': typeof RefundPolicyRoute
  '/RegistrationDetails': typeof RegistrationDetailsRoute
  '/SSFDigitalOffice': typeof SSFDigitalOfficeRoute
  '/SSFNationalAcademy': typeof SSFNationalAcademyRoute
  '/SkillPrograms': typeof SkillProgramsRoute
  '/Stories': typeof StoriesRoute
  '/Team': typeof TeamRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/Transparency': typeof TransparencyRoute
  '/UpcomingProjects': typeof UpcomingProjectsRoute
  '/UserPortal': typeof UserPortalRoute
  '/Vision': typeof VisionRoute
  '/Volunteer': typeof VolunteerRoute
  '/admin': typeof AdminRoute
  '/institutional-dna': typeof InstitutionalDnaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/Blog/$topic': typeof BlogTopicRoute
  '/LearningHub/explore': typeof LearningHubExploreRoute
  '/LearningHub/knowledge-world': typeof LearningHubKnowledgeWorldRoute
  '/LearningHub/my-learning': typeof LearningHubMyLearningRoute
  '/ims/activities': typeof ImsActivitiesRoute
  '/ims/appointment-letters': typeof ImsAppointmentLettersRoute
  '/ims/audit-trail': typeof ImsAuditTrailRoute
  '/ims/bank-book': typeof ImsBankBookRoute
  '/ims/cases': typeof ImsCasesRoute
  '/ims/cash-book': typeof ImsCashBookRoute
  '/ims/constitution': typeof ImsConstitutionRoute
  '/ims/data': typeof ImsDataRoute
  '/ims/donor-slips': typeof ImsDonorSlipsRoute
  '/ims/download-center': typeof ImsDownloadCenterRoute
  '/ims/history': typeof ImsHistoryRoute
  '/ims/impact': typeof ImsImpactRoute
  '/ims/integrity': typeof ImsIntegrityRoute
  '/ims/knowledge': typeof ImsKnowledgeRoute
  '/ims/learning-certificates': typeof ImsLearningCertificatesRoute
  '/ims/managing-committee': typeof ImsManagingCommitteeRoute
  '/ims/meetings': typeof ImsMeetingsRoute
  '/ims/members': typeof ImsMembersRoute
  '/ims/membership-contributions': typeof ImsMembershipContributionsRoute
  '/ims/notifications': typeof ImsNotificationsRoute
  '/ims/office': typeof ImsOfficeRoute
  '/ims/official-documents': typeof ImsOfficialDocumentsRoute
  '/ims/org-profile': typeof ImsOrgProfileRoute
  '/ims/permissions': typeof ImsPermissionsRoute
  '/ims/policies': typeof ImsPoliciesRoute
  '/ims/procurement': typeof ImsProcurementRoute
  '/ims/registers': typeof ImsRegistersRoute
  '/ims/reports': typeof ImsReportsRoute
  '/ims/search': typeof ImsSearchRoute
  '/ims/separations': typeof ImsSeparationsRoute
  '/ims/social': typeof ImsSocialRoute
  '/ims/users': typeof ImsUsersRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/LearningHub/': typeof LearningHubIndexRoute
  '/ims': typeof ImsIndexRoute
  '/LearningHub/course/$subjectId': typeof LearningHubCourseSubjectIdRoute
  '/ims/finance/cost-centres': typeof ImsFinanceCostCentresRoute
  '/ims/finance/ledger': typeof ImsFinanceLedgerRoute
  '/ims/finance/receipts-payments': typeof ImsFinanceReceiptsPaymentsRoute
  '/ims/legacy/$module': typeof ImsLegacyModuleRoute
  '/ims/member/$id': typeof ImsMemberIdRoute
  '/ims/person/$id': typeof ImsPersonIdRoute
  '/ims/r/$resource': typeof ImsRResourceRoute
  '/ims/sections/$section': typeof ImsSectionsSectionRoute
  '/ims/finance': typeof ImsFinanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/AdminPortal': typeof AdminPortalRoute
  '/Blog': typeof BlogRouteWithChildren
  '/CSRPartnership': typeof CSRPartnershipRoute
  '/Campaign': typeof CampaignRoute
  '/Campaigns': typeof CampaignsRoute
  '/Contact': typeof ContactRoute
  '/CookiePolicy': typeof CookiePolicyRoute
  '/Donate': typeof DonateRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
  '/DonationRefundPolicy': typeof DonationRefundPolicyRoute
  '/Donor': typeof DonorRoute
  '/GetInvolved': typeof GetInvolvedRoute
  '/Humanity&Truth': typeof HumanityChar38TruthRoute
  '/Impact': typeof ImpactRoute
  '/Internship': typeof InternshipRoute
  '/Join': typeof JoinRoute
  '/JoinUs': typeof JoinUsRoute
  '/Journey': typeof JourneyRoute
  '/LearningCertificateVerify': typeof LearningCertificateVerifyRoute
  '/LegalPolicies': typeof LegalPoliciesRoute
  '/Media': typeof MediaRoute
  '/MemberDashboard': typeof MemberDashboardRoute
  '/Members': typeof MembersRoute
  '/MemorandumAndRules': typeof MemorandumAndRulesRoute
  '/Mission': typeof MissionRoute
  '/Objectives': typeof ObjectivesRoute
  '/OurInitiatives': typeof OurInitiativesRoute
  '/PartnerWithUs': typeof PartnerWithUsRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/RefundAndCancellation': typeof RefundAndCancellationRoute
  '/RefundPolicy': typeof RefundPolicyRoute
  '/RegistrationDetails': typeof RegistrationDetailsRoute
  '/SSFDigitalOffice': typeof SSFDigitalOfficeRoute
  '/SSFNationalAcademy': typeof SSFNationalAcademyRoute
  '/SkillPrograms': typeof SkillProgramsRoute
  '/Stories': typeof StoriesRoute
  '/Team': typeof TeamRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/Transparency': typeof TransparencyRoute
  '/UpcomingProjects': typeof UpcomingProjectsRoute
  '/UserPortal': typeof UserPortalRoute
  '/Vision': typeof VisionRoute
  '/Volunteer': typeof VolunteerRoute
  '/admin': typeof AdminRoute
  '/institutional-dna': typeof InstitutionalDnaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/Blog/$topic': typeof BlogTopicRoute
  '/LearningHub/explore': typeof LearningHubExploreRoute
  '/LearningHub/knowledge-world': typeof LearningHubKnowledgeWorldRoute
  '/LearningHub/my-learning': typeof LearningHubMyLearningRoute
  '/ims/activities': typeof ImsActivitiesRoute
  '/ims/appointment-letters': typeof ImsAppointmentLettersRoute
  '/ims/audit-trail': typeof ImsAuditTrailRoute
  '/ims/bank-book': typeof ImsBankBookRoute
  '/ims/cases': typeof ImsCasesRoute
  '/ims/cash-book': typeof ImsCashBookRoute
  '/ims/constitution': typeof ImsConstitutionRoute
  '/ims/data': typeof ImsDataRoute
  '/ims/donor-slips': typeof ImsDonorSlipsRoute
  '/ims/download-center': typeof ImsDownloadCenterRoute
  '/ims/history': typeof ImsHistoryRoute
  '/ims/impact': typeof ImsImpactRoute
  '/ims/integrity': typeof ImsIntegrityRoute
  '/ims/knowledge': typeof ImsKnowledgeRoute
  '/ims/learning-certificates': typeof ImsLearningCertificatesRoute
  '/ims/managing-committee': typeof ImsManagingCommitteeRoute
  '/ims/meetings': typeof ImsMeetingsRoute
  '/ims/members': typeof ImsMembersRoute
  '/ims/membership-contributions': typeof ImsMembershipContributionsRoute
  '/ims/notifications': typeof ImsNotificationsRoute
  '/ims/office': typeof ImsOfficeRoute
  '/ims/official-documents': typeof ImsOfficialDocumentsRoute
  '/ims/org-profile': typeof ImsOrgProfileRoute
  '/ims/permissions': typeof ImsPermissionsRoute
  '/ims/policies': typeof ImsPoliciesRoute
  '/ims/procurement': typeof ImsProcurementRoute
  '/ims/registers': typeof ImsRegistersRoute
  '/ims/reports': typeof ImsReportsRoute
  '/ims/search': typeof ImsSearchRoute
  '/ims/separations': typeof ImsSeparationsRoute
  '/ims/social': typeof ImsSocialRoute
  '/ims/users': typeof ImsUsersRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/LearningHub': typeof LearningHubIndexRoute
  '/ims': typeof ImsIndexRoute
  '/LearningHub/course/$subjectId': typeof LearningHubCourseSubjectIdRoute
  '/ims/finance/cost-centres': typeof ImsFinanceCostCentresRoute
  '/ims/finance/ledger': typeof ImsFinanceLedgerRoute
  '/ims/finance/receipts-payments': typeof ImsFinanceReceiptsPaymentsRoute
  '/ims/legacy/$module': typeof ImsLegacyModuleRoute
  '/ims/member/$id': typeof ImsMemberIdRoute
  '/ims/person/$id': typeof ImsPersonIdRoute
  '/ims/r/$resource': typeof ImsRResourceRoute
  '/ims/sections/$section': typeof ImsSectionsSectionRoute
  '/ims/finance': typeof ImsFinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/AdminPortal': typeof AdminPortalRoute
  '/Blog': typeof BlogRouteWithChildren
  '/CSRPartnership': typeof CSRPartnershipRoute
  '/Campaign': typeof CampaignRoute
  '/Campaigns': typeof CampaignsRoute
  '/Contact': typeof ContactRoute
  '/CookiePolicy': typeof CookiePolicyRoute
  '/Donate': typeof DonateRoute
  '/DonateAndSupport': typeof DonateAndSupportRoute
  '/DonationRefundPolicy': typeof DonationRefundPolicyRoute
  '/Donor': typeof DonorRoute
  '/GetInvolved': typeof GetInvolvedRoute
  '/Humanity&Truth': typeof HumanityChar38TruthRoute
  '/Impact': typeof ImpactRoute
  '/Internship': typeof InternshipRoute
  '/Join': typeof JoinRoute
  '/JoinUs': typeof JoinUsRoute
  '/Journey': typeof JourneyRoute
  '/LearningCertificateVerify': typeof LearningCertificateVerifyRoute
  '/LearningHub': typeof LearningHubRouteWithChildren
  '/LegalPolicies': typeof LegalPoliciesRoute
  '/Media': typeof MediaRoute
  '/MemberDashboard': typeof MemberDashboardRoute
  '/Members': typeof MembersRoute
  '/MemorandumAndRules': typeof MemorandumAndRulesRoute
  '/Mission': typeof MissionRoute
  '/Objectives': typeof ObjectivesRoute
  '/OurInitiatives': typeof OurInitiativesRoute
  '/PartnerWithUs': typeof PartnerWithUsRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/RefundAndCancellation': typeof RefundAndCancellationRoute
  '/RefundPolicy': typeof RefundPolicyRoute
  '/RegistrationDetails': typeof RegistrationDetailsRoute
  '/SSFDigitalOffice': typeof SSFDigitalOfficeRoute
  '/SSFNationalAcademy': typeof SSFNationalAcademyRoute
  '/SkillPrograms': typeof SkillProgramsRoute
  '/Stories': typeof StoriesRoute
  '/Team': typeof TeamRoute
  '/TermsAndConditions': typeof TermsAndConditionsRoute
  '/Transparency': typeof TransparencyRoute
  '/UpcomingProjects': typeof UpcomingProjectsRoute
  '/UserPortal': typeof UserPortalRoute
  '/Vision': typeof VisionRoute
  '/Volunteer': typeof VolunteerRoute
  '/admin': typeof AdminRoute
  '/institutional-dna': typeof InstitutionalDnaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/Blog/$topic': typeof BlogTopicRoute
  '/LearningHub/explore': typeof LearningHubExploreRoute
  '/LearningHub/knowledge-world': typeof LearningHubKnowledgeWorldRoute
  '/LearningHub/my-learning': typeof LearningHubMyLearningRoute
  '/ims/activities': typeof ImsActivitiesRoute
  '/ims/appointment-letters': typeof ImsAppointmentLettersRoute
  '/ims/audit-trail': typeof ImsAuditTrailRoute
  '/ims/bank-book': typeof ImsBankBookRoute
  '/ims/cases': typeof ImsCasesRoute
  '/ims/cash-book': typeof ImsCashBookRoute
  '/ims/constitution': typeof ImsConstitutionRoute
  '/ims/data': typeof ImsDataRoute
  '/ims/donor-slips': typeof ImsDonorSlipsRoute
  '/ims/download-center': typeof ImsDownloadCenterRoute
  '/ims/history': typeof ImsHistoryRoute
  '/ims/impact': typeof ImsImpactRoute
  '/ims/integrity': typeof ImsIntegrityRoute
  '/ims/knowledge': typeof ImsKnowledgeRoute
  '/ims/learning-certificates': typeof ImsLearningCertificatesRoute
  '/ims/managing-committee': typeof ImsManagingCommitteeRoute
  '/ims/meetings': typeof ImsMeetingsRoute
  '/ims/members': typeof ImsMembersRoute
  '/ims/membership-contributions': typeof ImsMembershipContributionsRoute
  '/ims/notifications': typeof ImsNotificationsRoute
  '/ims/office': typeof ImsOfficeRoute
  '/ims/official-documents': typeof ImsOfficialDocumentsRoute
  '/ims/org-profile': typeof ImsOrgProfileRoute
  '/ims/permissions': typeof ImsPermissionsRoute
  '/ims/policies': typeof ImsPoliciesRoute
  '/ims/procurement': typeof ImsProcurementRoute
  '/ims/registers': typeof ImsRegistersRoute
  '/ims/reports': typeof ImsReportsRoute
  '/ims/search': typeof ImsSearchRoute
  '/ims/separations': typeof ImsSeparationsRoute
  '/ims/social': typeof ImsSocialRoute
  '/ims/users': typeof ImsUsersRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/LearningHub/': typeof LearningHubIndexRoute
  '/ims/': typeof ImsIndexRoute
  '/LearningHub/course/$subjectId': typeof LearningHubCourseSubjectIdRoute
  '/ims/finance/cost-centres': typeof ImsFinanceCostCentresRoute
  '/ims/finance/ledger': typeof ImsFinanceLedgerRoute
  '/ims/finance/receipts-payments': typeof ImsFinanceReceiptsPaymentsRoute
  '/ims/legacy/$module': typeof ImsLegacyModuleRoute
  '/ims/member/$id': typeof ImsMemberIdRoute
  '/ims/person/$id': typeof ImsPersonIdRoute
  '/ims/r/$resource': typeof ImsRResourceRoute
  '/ims/sections/$section': typeof ImsSectionsSectionRoute
  '/ims/finance/': typeof ImsFinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/About'
    | '/AdminPortal'
    | '/Blog'
    | '/CSRPartnership'
    | '/Campaign'
    | '/Campaigns'
    | '/Contact'
    | '/CookiePolicy'
    | '/Donate'
    | '/DonateAndSupport'
    | '/DonationRefundPolicy'
    | '/Donor'
    | '/GetInvolved'
    | '/Humanity&Truth'
    | '/Impact'
    | '/Internship'
    | '/Join'
    | '/JoinUs'
    | '/Journey'
    | '/LearningCertificateVerify'
    | '/LearningHub'
    | '/LegalPolicies'
    | '/Media'
    | '/MemberDashboard'
    | '/Members'
    | '/MemorandumAndRules'
    | '/Mission'
    | '/Objectives'
    | '/OurInitiatives'
    | '/PartnerWithUs'
    | '/PrivacyPolicy'
    | '/RefundAndCancellation'
    | '/RefundPolicy'
    | '/RegistrationDetails'
    | '/SSFDigitalOffice'
    | '/SSFNationalAcademy'
    | '/SkillPrograms'
    | '/Stories'
    | '/Team'
    | '/TermsAndConditions'
    | '/Transparency'
    | '/UpcomingProjects'
    | '/UserPortal'
    | '/Vision'
    | '/Volunteer'
    | '/admin'
    | '/institutional-dna'
    | '/reset-password'
    | '/Blog/$topic'
    | '/LearningHub/explore'
    | '/LearningHub/knowledge-world'
    | '/LearningHub/my-learning'
    | '/ims/activities'
    | '/ims/appointment-letters'
    | '/ims/audit-trail'
    | '/ims/bank-book'
    | '/ims/cases'
    | '/ims/cash-book'
    | '/ims/constitution'
    | '/ims/data'
    | '/ims/donor-slips'
    | '/ims/download-center'
    | '/ims/history'
    | '/ims/impact'
    | '/ims/integrity'
    | '/ims/knowledge'
    | '/ims/learning-certificates'
    | '/ims/managing-committee'
    | '/ims/meetings'
    | '/ims/members'
    | '/ims/membership-contributions'
    | '/ims/notifications'
    | '/ims/office'
    | '/ims/official-documents'
    | '/ims/org-profile'
    | '/ims/permissions'
    | '/ims/policies'
    | '/ims/procurement'
    | '/ims/registers'
    | '/ims/reports'
    | '/ims/search'
    | '/ims/separations'
    | '/ims/social'
    | '/ims/users'
    | '/verify/$certId'
    | '/verify/$code'
    | '/LearningHub/'
    | '/ims'
    | '/LearningHub/course/$subjectId'
    | '/ims/finance/cost-centres'
    | '/ims/finance/ledger'
    | '/ims/finance/receipts-payments'
    | '/ims/legacy/$module'
    | '/ims/member/$id'
    | '/ims/person/$id'
    | '/ims/r/$resource'
    | '/ims/sections/$section'
    | '/ims/finance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/About'
    | '/AdminPortal'
    | '/Blog'
    | '/CSRPartnership'
    | '/Campaign'
    | '/Campaigns'
    | '/Contact'
    | '/CookiePolicy'
    | '/Donate'
    | '/DonateAndSupport'
    | '/DonationRefundPolicy'
    | '/Donor'
    | '/GetInvolved'
    | '/Humanity&Truth'
    | '/Impact'
    | '/Internship'
    | '/Join'
    | '/JoinUs'
    | '/Journey'
    | '/LearningCertificateVerify'
    | '/LegalPolicies'
    | '/Media'
    | '/MemberDashboard'
    | '/Members'
    | '/MemorandumAndRules'
    | '/Mission'
    | '/Objectives'
    | '/OurInitiatives'
    | '/PartnerWithUs'
    | '/PrivacyPolicy'
    | '/RefundAndCancellation'
    | '/RefundPolicy'
    | '/RegistrationDetails'
    | '/SSFDigitalOffice'
    | '/SSFNationalAcademy'
    | '/SkillPrograms'
    | '/Stories'
    | '/Team'
    | '/TermsAndConditions'
    | '/Transparency'
    | '/UpcomingProjects'
    | '/UserPortal'
    | '/Vision'
    | '/Volunteer'
    | '/admin'
    | '/institutional-dna'
    | '/reset-password'
    | '/Blog/$topic'
    | '/LearningHub/explore'
    | '/LearningHub/knowledge-world'
    | '/LearningHub/my-learning'
    | '/ims/activities'
    | '/ims/appointment-letters'
    | '/ims/audit-trail'
    | '/ims/bank-book'
    | '/ims/cases'
    | '/ims/cash-book'
    | '/ims/constitution'
    | '/ims/data'
    | '/ims/donor-slips'
    | '/ims/download-center'
    | '/ims/history'
    | '/ims/impact'
    | '/ims/integrity'
    | '/ims/knowledge'
    | '/ims/learning-certificates'
    | '/ims/managing-committee'
    | '/ims/meetings'
    | '/ims/members'
    | '/ims/membership-contributions'
    | '/ims/notifications'
    | '/ims/office'
    | '/ims/official-documents'
    | '/ims/org-profile'
    | '/ims/permissions'
    | '/ims/policies'
    | '/ims/procurement'
    | '/ims/registers'
    | '/ims/reports'
    | '/ims/search'
    | '/ims/separations'
    | '/ims/social'
    | '/ims/users'
    | '/verify/$certId'
    | '/verify/$code'
    | '/LearningHub'
    | '/ims'
    | '/LearningHub/course/$subjectId'
    | '/ims/finance/cost-centres'
    | '/ims/finance/ledger'
    | '/ims/finance/receipts-payments'
    | '/ims/legacy/$module'
    | '/ims/member/$id'
    | '/ims/person/$id'
    | '/ims/r/$resource'
    | '/ims/sections/$section'
    | '/ims/finance'
  id:
    | '__root__'
    | '/'
    | '/About'
    | '/AdminPortal'
    | '/Blog'
    | '/CSRPartnership'
    | '/Campaign'
    | '/Campaigns'
    | '/Contact'
    | '/CookiePolicy'
    | '/Donate'
    | '/DonateAndSupport'
    | '/DonationRefundPolicy'
    | '/Donor'
    | '/GetInvolved'
    | '/Humanity&Truth'
    | '/Impact'
    | '/Internship'
    | '/Join'
    | '/JoinUs'
    | '/Journey'
    | '/LearningCertificateVerify'
    | '/LearningHub'
    | '/LegalPolicies'
    | '/Media'
    | '/MemberDashboard'
    | '/Members'
    | '/MemorandumAndRules'
    | '/Mission'
    | '/Objectives'
    | '/OurInitiatives'
    | '/PartnerWithUs'
    | '/PrivacyPolicy'
    | '/RefundAndCancellation'
    | '/RefundPolicy'
    | '/RegistrationDetails'
    | '/SSFDigitalOffice'
    | '/SSFNationalAcademy'
    | '/SkillPrograms'
    | '/Stories'
    | '/Team'
    | '/TermsAndConditions'
    | '/Transparency'
    | '/UpcomingProjects'
    | '/UserPortal'
    | '/Vision'
    | '/Volunteer'
    | '/admin'
    | '/institutional-dna'
    | '/reset-password'
    | '/Blog/$topic'
    | '/LearningHub/explore'
    | '/LearningHub/knowledge-world'
    | '/LearningHub/my-learning'
    | '/ims/activities'
    | '/ims/appointment-letters'
    | '/ims/audit-trail'
    | '/ims/bank-book'
    | '/ims/cases'
    | '/ims/cash-book'
    | '/ims/constitution'
    | '/ims/data'
    | '/ims/donor-slips'
    | '/ims/download-center'
    | '/ims/history'
    | '/ims/impact'
    | '/ims/integrity'
    | '/ims/knowledge'
    | '/ims/learning-certificates'
    | '/ims/managing-committee'
    | '/ims/meetings'
    | '/ims/members'
    | '/ims/membership-contributions'
    | '/ims/notifications'
    | '/ims/office'
    | '/ims/official-documents'
    | '/ims/org-profile'
    | '/ims/permissions'
    | '/ims/policies'
    | '/ims/procurement'
    | '/ims/registers'
    | '/ims/reports'
    | '/ims/search'
    | '/ims/separations'
    | '/ims/social'
    | '/ims/users'
    | '/verify/$certId'
    | '/verify/$code'
    | '/LearningHub/'
    | '/ims/'
    | '/LearningHub/course/$subjectId'
    | '/ims/finance/cost-centres'
    | '/ims/finance/ledger'
    | '/ims/finance/receipts-payments'
    | '/ims/legacy/$module'
    | '/ims/member/$id'
    | '/ims/person/$id'
    | '/ims/r/$resource'
    | '/ims/sections/$section'
    | '/ims/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminPortalRoute: typeof AdminPortalRoute
  BlogRoute: typeof BlogRouteWithChildren
  CSRPartnershipRoute: typeof CSRPartnershipRoute
  CampaignRoute: typeof CampaignRoute
  CampaignsRoute: typeof CampaignsRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DonateRoute: typeof DonateRoute
  DonateAndSupportRoute: typeof DonateAndSupportRoute
  DonationRefundPolicyRoute: typeof DonationRefundPolicyRoute
  DonorRoute: typeof DonorRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  HumanityChar38TruthRoute: typeof HumanityChar38TruthRoute
  ImpactRoute: typeof ImpactRoute
  InternshipRoute: typeof InternshipRoute
  JoinRoute: typeof JoinRoute
  JoinUsRoute: typeof JoinUsRoute
  JourneyRoute: typeof JourneyRoute
  LearningCertificateVerifyRoute: typeof LearningCertificateVerifyRoute
  LearningHubRoute: typeof LearningHubRouteWithChildren
  LegalPoliciesRoute: typeof LegalPoliciesRoute
  MediaRoute: typeof MediaRoute
  MemberDashboardRoute: typeof MemberDashboardRoute
  MembersRoute: typeof MembersRoute
  MemorandumAndRulesRoute: typeof MemorandumAndRulesRoute
  MissionRoute: typeof MissionRoute
  ObjectivesRoute: typeof ObjectivesRoute
  OurInitiativesRoute: typeof OurInitiativesRoute
  PartnerWithUsRoute: typeof PartnerWithUsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundAndCancellationRoute: typeof RefundAndCancellationRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegistrationDetailsRoute: typeof RegistrationDetailsRoute
  SSFDigitalOfficeRoute: typeof SSFDigitalOfficeRoute
  SSFNationalAcademyRoute: typeof SSFNationalAcademyRoute
  SkillProgramsRoute: typeof SkillProgramsRoute
  StoriesRoute: typeof StoriesRoute
  TeamRoute: typeof TeamRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TransparencyRoute: typeof TransparencyRoute
  UpcomingProjectsRoute: typeof UpcomingProjectsRoute
  UserPortalRoute: typeof UserPortalRoute
  VisionRoute: typeof VisionRoute
  VolunteerRoute: typeof VolunteerRoute
  AdminRoute: typeof AdminRoute
  InstitutionalDnaRoute: typeof InstitutionalDnaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ImsActivitiesRoute: typeof ImsActivitiesRoute
  ImsAppointmentLettersRoute: typeof ImsAppointmentLettersRoute
  ImsAuditTrailRoute: typeof ImsAuditTrailRoute
  ImsBankBookRoute: typeof ImsBankBookRoute
  ImsCasesRoute: typeof ImsCasesRoute
  ImsCashBookRoute: typeof ImsCashBookRoute
  ImsConstitutionRoute: typeof ImsConstitutionRoute
  ImsDataRoute: typeof ImsDataRoute
  ImsDonorSlipsRoute: typeof ImsDonorSlipsRoute
  ImsDownloadCenterRoute: typeof ImsDownloadCenterRoute
  ImsHistoryRoute: typeof ImsHistoryRoute
  ImsImpactRoute: typeof ImsImpactRoute
  ImsIntegrityRoute: typeof ImsIntegrityRoute
  ImsKnowledgeRoute: typeof ImsKnowledgeRoute
  ImsLearningCertificatesRoute: typeof ImsLearningCertificatesRoute
  ImsManagingCommitteeRoute: typeof ImsManagingCommitteeRoute
  ImsMeetingsRoute: typeof ImsMeetingsRoute
  ImsMembersRoute: typeof ImsMembersRoute
  ImsMembershipContributionsRoute: typeof ImsMembershipContributionsRoute
  ImsNotificationsRoute: typeof ImsNotificationsRoute
  ImsOfficeRoute: typeof ImsOfficeRoute
  ImsOfficialDocumentsRoute: typeof ImsOfficialDocumentsRoute
  ImsOrgProfileRoute: typeof ImsOrgProfileRoute
  ImsPermissionsRoute: typeof ImsPermissionsRoute
  ImsPoliciesRoute: typeof ImsPoliciesRoute
  ImsProcurementRoute: typeof ImsProcurementRoute
  ImsRegistersRoute: typeof ImsRegistersRoute
  ImsReportsRoute: typeof ImsReportsRoute
  ImsSearchRoute: typeof ImsSearchRoute
  ImsSeparationsRoute: typeof ImsSeparationsRoute
  ImsSocialRoute: typeof ImsSocialRoute
  ImsUsersRoute: typeof ImsUsersRoute
  VerifyCertIdRoute: typeof VerifyCertIdRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  ImsIndexRoute: typeof ImsIndexRoute
  ImsFinanceCostCentresRoute: typeof ImsFinanceCostCentresRoute
  ImsFinanceLedgerRoute: typeof ImsFinanceLedgerRoute
  ImsFinanceReceiptsPaymentsRoute: typeof ImsFinanceReceiptsPaymentsRoute
  ImsLegacyModuleRoute: typeof ImsLegacyModuleRoute
  ImsMemberIdRoute: typeof ImsMemberIdRoute
  ImsPersonIdRoute: typeof ImsPersonIdRoute
  ImsRResourceRoute: typeof ImsRResourceRoute
  ImsSectionsSectionRoute: typeof ImsSectionsSectionRoute
  ImsFinanceIndexRoute: typeof ImsFinanceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional-dna': {
      id: '/institutional-dna'
      path: '/institutional-dna'
      fullPath: '/institutional-dna'
      preLoaderRoute: typeof InstitutionalDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Volunteer': {
      id: '/Volunteer'
      path: '/Volunteer'
      fullPath: '/Volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Vision': {
      id: '/Vision'
      path: '/Vision'
      fullPath: '/Vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UserPortal': {
      id: '/UserPortal'
      path: '/UserPortal'
      fullPath: '/UserPortal'
      preLoaderRoute: typeof UserPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UpcomingProjects': {
      id: '/UpcomingProjects'
      path: '/UpcomingProjects'
      fullPath: '/UpcomingProjects'
      preLoaderRoute: typeof UpcomingProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Transparency': {
      id: '/Transparency'
      path: '/Transparency'
      fullPath: '/Transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TermsAndConditions': {
      id: '/TermsAndConditions'
      path: '/TermsAndConditions'
      fullPath: '/TermsAndConditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Team': {
      id: '/Team'
      path: '/Team'
      fullPath: '/Team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Stories': {
      id: '/Stories'
      path: '/Stories'
      fullPath: '/Stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SkillPrograms': {
      id: '/SkillPrograms'
      path: '/SkillPrograms'
      fullPath: '/SkillPrograms'
      preLoaderRoute: typeof SkillProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SSFNationalAcademy': {
      id: '/SSFNationalAcademy'
      path: '/SSFNationalAcademy'
      fullPath: '/SSFNationalAcademy'
      preLoaderRoute: typeof SSFNationalAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SSFDigitalOffice': {
      id: '/SSFDigitalOffice'
      path: '/SSFDigitalOffice'
      fullPath: '/SSFDigitalOffice'
      preLoaderRoute: typeof SSFDigitalOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegistrationDetails': {
      id: '/RegistrationDetails'
      path: '/RegistrationDetails'
      fullPath: '/RegistrationDetails'
      preLoaderRoute: typeof RegistrationDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RefundPolicy': {
      id: '/RefundPolicy'
      path: '/RefundPolicy'
      fullPath: '/RefundPolicy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RefundAndCancellation': {
      id: '/RefundAndCancellation'
      path: '/RefundAndCancellation'
      fullPath: '/RefundAndCancellation'
      preLoaderRoute: typeof RefundAndCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PrivacyPolicy': {
      id: '/PrivacyPolicy'
      path: '/PrivacyPolicy'
      fullPath: '/PrivacyPolicy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PartnerWithUs': {
      id: '/PartnerWithUs'
      path: '/PartnerWithUs'
      fullPath: '/PartnerWithUs'
      preLoaderRoute: typeof PartnerWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/OurInitiatives': {
      id: '/OurInitiatives'
      path: '/OurInitiatives'
      fullPath: '/OurInitiatives'
      preLoaderRoute: typeof OurInitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Objectives': {
      id: '/Objectives'
      path: '/Objectives'
      fullPath: '/Objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mission': {
      id: '/Mission'
      path: '/Mission'
      fullPath: '/Mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MemorandumAndRules': {
      id: '/MemorandumAndRules'
      path: '/MemorandumAndRules'
      fullPath: '/MemorandumAndRules'
      preLoaderRoute: typeof MemorandumAndRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Members': {
      id: '/Members'
      path: '/Members'
      fullPath: '/Members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MemberDashboard': {
      id: '/MemberDashboard'
      path: '/MemberDashboard'
      fullPath: '/MemberDashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Media': {
      id: '/Media'
      path: '/Media'
      fullPath: '/Media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LegalPolicies': {
      id: '/LegalPolicies'
      path: '/LegalPolicies'
      fullPath: '/LegalPolicies'
      preLoaderRoute: typeof LegalPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LearningHub': {
      id: '/LearningHub'
      path: '/LearningHub'
      fullPath: '/LearningHub'
      preLoaderRoute: typeof LearningHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LearningCertificateVerify': {
      id: '/LearningCertificateVerify'
      path: '/LearningCertificateVerify'
      fullPath: '/LearningCertificateVerify'
      preLoaderRoute: typeof LearningCertificateVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Journey': {
      id: '/Journey'
      path: '/Journey'
      fullPath: '/Journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/JoinUs': {
      id: '/JoinUs'
      path: '/JoinUs'
      fullPath: '/JoinUs'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Join': {
      id: '/Join'
      path: '/Join'
      fullPath: '/Join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Internship': {
      id: '/Internship'
      path: '/Internship'
      fullPath: '/Internship'
      preLoaderRoute: typeof InternshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Impact': {
      id: '/Impact'
      path: '/Impact'
      fullPath: '/Impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Humanity&Truth': {
      id: '/Humanity&Truth'
      path: '/Humanity&Truth'
      fullPath: '/Humanity&Truth'
      preLoaderRoute: typeof HumanityChar38TruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/GetInvolved': {
      id: '/GetInvolved'
      path: '/GetInvolved'
      fullPath: '/GetInvolved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Donor': {
      id: '/Donor'
      path: '/Donor'
      fullPath: '/Donor'
      preLoaderRoute: typeof DonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DonationRefundPolicy': {
      id: '/DonationRefundPolicy'
      path: '/DonationRefundPolicy'
      fullPath: '/DonationRefundPolicy'
      preLoaderRoute: typeof DonationRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DonateAndSupport': {
      id: '/DonateAndSupport'
      path: '/DonateAndSupport'
      fullPath: '/DonateAndSupport'
      preLoaderRoute: typeof DonateAndSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Donate': {
      id: '/Donate'
      path: '/Donate'
      fullPath: '/Donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CookiePolicy': {
      id: '/CookiePolicy'
      path: '/CookiePolicy'
      fullPath: '/CookiePolicy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Campaigns': {
      id: '/Campaigns'
      path: '/Campaigns'
      fullPath: '/Campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Campaign': {
      id: '/Campaign'
      path: '/Campaign'
      fullPath: '/Campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CSRPartnership': {
      id: '/CSRPartnership'
      path: '/CSRPartnership'
      fullPath: '/CSRPartnership'
      preLoaderRoute: typeof CSRPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Blog': {
      id: '/Blog'
      path: '/Blog'
      fullPath: '/Blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminPortal': {
      id: '/AdminPortal'
      path: '/AdminPortal'
      fullPath: '/AdminPortal'
      preLoaderRoute: typeof AdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/': {
      id: '/ims/'
      path: '/ims'
      fullPath: '/ims'
      preLoaderRoute: typeof ImsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LearningHub/': {
      id: '/LearningHub/'
      path: '/'
      fullPath: '/LearningHub/'
      preLoaderRoute: typeof LearningHubIndexRouteImport
      parentRoute: typeof LearningHubRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certId': {
      id: '/verify/$certId'
      path: '/verify/$certId'
      fullPath: '/verify/$certId'
      preLoaderRoute: typeof VerifyCertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/users': {
      id: '/ims/users'
      path: '/ims/users'
      fullPath: '/ims/users'
      preLoaderRoute: typeof ImsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/social': {
      id: '/ims/social'
      path: '/ims/social'
      fullPath: '/ims/social'
      preLoaderRoute: typeof ImsSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/separations': {
      id: '/ims/separations'
      path: '/ims/separations'
      fullPath: '/ims/separations'
      preLoaderRoute: typeof ImsSeparationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/search': {
      id: '/ims/search'
      path: '/ims/search'
      fullPath: '/ims/search'
      preLoaderRoute: typeof ImsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/reports': {
      id: '/ims/reports'
      path: '/ims/reports'
      fullPath: '/ims/reports'
      preLoaderRoute: typeof ImsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/registers': {
      id: '/ims/registers'
      path: '/ims/registers'
      fullPath: '/ims/registers'
      preLoaderRoute: typeof ImsRegistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/procurement': {
      id: '/ims/procurement'
      path: '/ims/procurement'
      fullPath: '/ims/procurement'
      preLoaderRoute: typeof ImsProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/policies': {
      id: '/ims/policies'
      path: '/ims/policies'
      fullPath: '/ims/policies'
      preLoaderRoute: typeof ImsPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/permissions': {
      id: '/ims/permissions'
      path: '/ims/permissions'
      fullPath: '/ims/permissions'
      preLoaderRoute: typeof ImsPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/org-profile': {
      id: '/ims/org-profile'
      path: '/ims/org-profile'
      fullPath: '/ims/org-profile'
      preLoaderRoute: typeof ImsOrgProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/official-documents': {
      id: '/ims/official-documents'
      path: '/ims/official-documents'
      fullPath: '/ims/official-documents'
      preLoaderRoute: typeof ImsOfficialDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/office': {
      id: '/ims/office'
      path: '/ims/office'
      fullPath: '/ims/office'
      preLoaderRoute: typeof ImsOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/notifications': {
      id: '/ims/notifications'
      path: '/ims/notifications'
      fullPath: '/ims/notifications'
      preLoaderRoute: typeof ImsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/membership-contributions': {
      id: '/ims/membership-contributions'
      path: '/ims/membership-contributions'
      fullPath: '/ims/membership-contributions'
      preLoaderRoute: typeof ImsMembershipContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/members': {
      id: '/ims/members'
      path: '/ims/members'
      fullPath: '/ims/members'
      preLoaderRoute: typeof ImsMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/meetings': {
      id: '/ims/meetings'
      path: '/ims/meetings'
      fullPath: '/ims/meetings'
      preLoaderRoute: typeof ImsMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/managing-committee': {
      id: '/ims/managing-committee'
      path: '/ims/managing-committee'
      fullPath: '/ims/managing-committee'
      preLoaderRoute: typeof ImsManagingCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/learning-certificates': {
      id: '/ims/learning-certificates'
      path: '/ims/learning-certificates'
      fullPath: '/ims/learning-certificates'
      preLoaderRoute: typeof ImsLearningCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/knowledge': {
      id: '/ims/knowledge'
      path: '/ims/knowledge'
      fullPath: '/ims/knowledge'
      preLoaderRoute: typeof ImsKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/integrity': {
      id: '/ims/integrity'
      path: '/ims/integrity'
      fullPath: '/ims/integrity'
      preLoaderRoute: typeof ImsIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/impact': {
      id: '/ims/impact'
      path: '/ims/impact'
      fullPath: '/ims/impact'
      preLoaderRoute: typeof ImsImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/history': {
      id: '/ims/history'
      path: '/ims/history'
      fullPath: '/ims/history'
      preLoaderRoute: typeof ImsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/download-center': {
      id: '/ims/download-center'
      path: '/ims/download-center'
      fullPath: '/ims/download-center'
      preLoaderRoute: typeof ImsDownloadCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/donor-slips': {
      id: '/ims/donor-slips'
      path: '/ims/donor-slips'
      fullPath: '/ims/donor-slips'
      preLoaderRoute: typeof ImsDonorSlipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/data': {
      id: '/ims/data'
      path: '/ims/data'
      fullPath: '/ims/data'
      preLoaderRoute: typeof ImsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/constitution': {
      id: '/ims/constitution'
      path: '/ims/constitution'
      fullPath: '/ims/constitution'
      preLoaderRoute: typeof ImsConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/cash-book': {
      id: '/ims/cash-book'
      path: '/ims/cash-book'
      fullPath: '/ims/cash-book'
      preLoaderRoute: typeof ImsCashBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/cases': {
      id: '/ims/cases'
      path: '/ims/cases'
      fullPath: '/ims/cases'
      preLoaderRoute: typeof ImsCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/bank-book': {
      id: '/ims/bank-book'
      path: '/ims/bank-book'
      fullPath: '/ims/bank-book'
      preLoaderRoute: typeof ImsBankBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/audit-trail': {
      id: '/ims/audit-trail'
      path: '/ims/audit-trail'
      fullPath: '/ims/audit-trail'
      preLoaderRoute: typeof ImsAuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/appointment-letters': {
      id: '/ims/appointment-letters'
      path: '/ims/appointment-letters'
      fullPath: '/ims/appointment-letters'
      preLoaderRoute: typeof ImsAppointmentLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/activities': {
      id: '/ims/activities'
      path: '/ims/activities'
      fullPath: '/ims/activities'
      preLoaderRoute: typeof ImsActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LearningHub/my-learning': {
      id: '/LearningHub/my-learning'
      path: '/my-learning'
      fullPath: '/LearningHub/my-learning'
      preLoaderRoute: typeof LearningHubMyLearningRouteImport
      parentRoute: typeof LearningHubRoute
    }
    '/LearningHub/knowledge-world': {
      id: '/LearningHub/knowledge-world'
      path: '/knowledge-world'
      fullPath: '/LearningHub/knowledge-world'
      preLoaderRoute: typeof LearningHubKnowledgeWorldRouteImport
      parentRoute: typeof LearningHubRoute
    }
    '/LearningHub/explore': {
      id: '/LearningHub/explore'
      path: '/explore'
      fullPath: '/LearningHub/explore'
      preLoaderRoute: typeof LearningHubExploreRouteImport
      parentRoute: typeof LearningHubRoute
    }
    '/Blog/$topic': {
      id: '/Blog/$topic'
      path: '/$topic'
      fullPath: '/Blog/$topic'
      preLoaderRoute: typeof BlogTopicRouteImport
      parentRoute: typeof BlogRoute
    }
    '/ims/finance/': {
      id: '/ims/finance/'
      path: '/ims/finance'
      fullPath: '/ims/finance'
      preLoaderRoute: typeof ImsFinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/sections/$section': {
      id: '/ims/sections/$section'
      path: '/ims/sections/$section'
      fullPath: '/ims/sections/$section'
      preLoaderRoute: typeof ImsSectionsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/r/$resource': {
      id: '/ims/r/$resource'
      path: '/ims/r/$resource'
      fullPath: '/ims/r/$resource'
      preLoaderRoute: typeof ImsRResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/person/$id': {
      id: '/ims/person/$id'
      path: '/ims/person/$id'
      fullPath: '/ims/person/$id'
      preLoaderRoute: typeof ImsPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/member/$id': {
      id: '/ims/member/$id'
      path: '/ims/member/$id'
      fullPath: '/ims/member/$id'
      preLoaderRoute: typeof ImsMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/legacy/$module': {
      id: '/ims/legacy/$module'
      path: '/ims/legacy/$module'
      fullPath: '/ims/legacy/$module'
      preLoaderRoute: typeof ImsLegacyModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/finance/receipts-payments': {
      id: '/ims/finance/receipts-payments'
      path: '/ims/finance/receipts-payments'
      fullPath: '/ims/finance/receipts-payments'
      preLoaderRoute: typeof ImsFinanceReceiptsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/finance/ledger': {
      id: '/ims/finance/ledger'
      path: '/ims/finance/ledger'
      fullPath: '/ims/finance/ledger'
      preLoaderRoute: typeof ImsFinanceLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ims/finance/cost-centres': {
      id: '/ims/finance/cost-centres'
      path: '/ims/finance/cost-centres'
      fullPath: '/ims/finance/cost-centres'
      preLoaderRoute: typeof ImsFinanceCostCentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LearningHub/course/$subjectId': {
      id: '/LearningHub/course/$subjectId'
      path: '/course/$subjectId'
      fullPath: '/LearningHub/course/$subjectId'
      preLoaderRoute: typeof LearningHubCourseSubjectIdRouteImport
      parentRoute: typeof LearningHubRoute
    }
  }
}

interface BlogRouteChildren {
  BlogTopicRoute: typeof BlogTopicRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogTopicRoute: BlogTopicRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface LearningHubRouteChildren {
  LearningHubExploreRoute: typeof LearningHubExploreRoute
  LearningHubKnowledgeWorldRoute: typeof LearningHubKnowledgeWorldRoute
  LearningHubMyLearningRoute: typeof LearningHubMyLearningRoute
  LearningHubIndexRoute: typeof LearningHubIndexRoute
  LearningHubCourseSubjectIdRoute: typeof LearningHubCourseSubjectIdRoute
}

const LearningHubRouteChildren: LearningHubRouteChildren = {
  LearningHubExploreRoute: LearningHubExploreRoute,
  LearningHubKnowledgeWorldRoute: LearningHubKnowledgeWorldRoute,
  LearningHubMyLearningRoute: LearningHubMyLearningRoute,
  LearningHubIndexRoute: LearningHubIndexRoute,
  LearningHubCourseSubjectIdRoute: LearningHubCourseSubjectIdRoute,
}

const LearningHubRouteWithChildren = LearningHubRoute._addFileChildren(
  LearningHubRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminPortalRoute: AdminPortalRoute,
  BlogRoute: BlogRouteWithChildren,
  CSRPartnershipRoute: CSRPartnershipRoute,
  CampaignRoute: CampaignRoute,
  CampaignsRoute: CampaignsRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DonateRoute: DonateRoute,
  DonateAndSupportRoute: DonateAndSupportRoute,
  DonationRefundPolicyRoute: DonationRefundPolicyRoute,
  DonorRoute: DonorRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  HumanityChar38TruthRoute: HumanityChar38TruthRoute,
  ImpactRoute: ImpactRoute,
  InternshipRoute: InternshipRoute,
  JoinRoute: JoinRoute,
  JoinUsRoute: JoinUsRoute,
  JourneyRoute: JourneyRoute,
  LearningCertificateVerifyRoute: LearningCertificateVerifyRoute,
  LearningHubRoute: LearningHubRouteWithChildren,
  LegalPoliciesRoute: LegalPoliciesRoute,
  MediaRoute: MediaRoute,
  MemberDashboardRoute: MemberDashboardRoute,
  MembersRoute: MembersRoute,
  MemorandumAndRulesRoute: MemorandumAndRulesRoute,
  MissionRoute: MissionRoute,
  ObjectivesRoute: ObjectivesRoute,
  OurInitiativesRoute: OurInitiativesRoute,
  PartnerWithUsRoute: PartnerWithUsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundAndCancellationRoute: RefundAndCancellationRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegistrationDetailsRoute: RegistrationDetailsRoute,
  SSFDigitalOfficeRoute: SSFDigitalOfficeRoute,
  SSFNationalAcademyRoute: SSFNationalAcademyRoute,
  SkillProgramsRoute: SkillProgramsRoute,
  StoriesRoute: StoriesRoute,
  TeamRoute: TeamRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TransparencyRoute: TransparencyRoute,
  UpcomingProjectsRoute: UpcomingProjectsRoute,
  UserPortalRoute: UserPortalRoute,
  VisionRoute: VisionRoute,
  VolunteerRoute: VolunteerRoute,
  AdminRoute: AdminRoute,
  InstitutionalDnaRoute: InstitutionalDnaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ImsActivitiesRoute: ImsActivitiesRoute,
  ImsAppointmentLettersRoute: ImsAppointmentLettersRoute,
  ImsAuditTrailRoute: ImsAuditTrailRoute,
  ImsBankBookRoute: ImsBankBookRoute,
  ImsCasesRoute: ImsCasesRoute,
  ImsCashBookRoute: ImsCashBookRoute,
  ImsConstitutionRoute: ImsConstitutionRoute,
  ImsDataRoute: ImsDataRoute,
  ImsDonorSlipsRoute: ImsDonorSlipsRoute,
  ImsDownloadCenterRoute: ImsDownloadCenterRoute,
  ImsHistoryRoute: ImsHistoryRoute,
  ImsImpactRoute: ImsImpactRoute,
  ImsIntegrityRoute: ImsIntegrityRoute,
  ImsKnowledgeRoute: ImsKnowledgeRoute,
  ImsLearningCertificatesRoute: ImsLearningCertificatesRoute,
  ImsManagingCommitteeRoute: ImsManagingCommitteeRoute,
  ImsMeetingsRoute: ImsMeetingsRoute,
  ImsMembersRoute: ImsMembersRoute,
  ImsMembershipContributionsRoute: ImsMembershipContributionsRoute,
  ImsNotificationsRoute: ImsNotificationsRoute,
  ImsOfficeRoute: ImsOfficeRoute,
  ImsOfficialDocumentsRoute: ImsOfficialDocumentsRoute,
  ImsOrgProfileRoute: ImsOrgProfileRoute,
  ImsPermissionsRoute: ImsPermissionsRoute,
  ImsPoliciesRoute: ImsPoliciesRoute,
  ImsProcurementRoute: ImsProcurementRoute,
  ImsRegistersRoute: ImsRegistersRoute,
  ImsReportsRoute: ImsReportsRoute,
  ImsSearchRoute: ImsSearchRoute,
  ImsSeparationsRoute: ImsSeparationsRoute,
  ImsSocialRoute: ImsSocialRoute,
  ImsUsersRoute: ImsUsersRoute,
  VerifyCertIdRoute: VerifyCertIdRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  ImsIndexRoute: ImsIndexRoute,
  ImsFinanceCostCentresRoute: ImsFinanceCostCentresRoute,
  ImsFinanceLedgerRoute: ImsFinanceLedgerRoute,
  ImsFinanceReceiptsPaymentsRoute: ImsFinanceReceiptsPaymentsRoute,
  ImsLegacyModuleRoute: ImsLegacyModuleRoute,
  ImsMemberIdRoute: ImsMemberIdRoute,
  ImsPersonIdRoute: ImsPersonIdRoute,
  ImsRResourceRoute: ImsRResourceRoute,
  ImsSectionsSectionRoute: ImsSectionsSectionRoute,
  ImsFinanceIndexRoute: ImsFinanceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
