// Auto-extracted from the SSF "Leadership - Volunteer & Membership" Google Form
// responses (volunteer + leadership applications). One entry per unique person.
// Bilingual names are preserved as submitted. Keep this file as the import source.

const VOLUNTEER_IMPORT = [
  {
    fullName: "Jyotsana",
    email: "Rameshpandey335@gmail.com",
    gender: "Female",
    dob: "1983-09-19",
    city: "Wagholi",
    volunteerType: "field",
    preferredArea: "Yes",
    financiallyIndependent: "NA",
    motivation: "NA",
    sourceTimestamp: "2024/09/19 12:12:51 am GMT+5:30",
  },
  {
    fullName: "Neeraj Dubey",
    email: "dubeyneeraj230@gmail.com",
    mobile: "7225900374",
    gender: "Male",
    dob: "1998-12-25",
    city: "ADRASH NAGAR SFATIK SHILA MOD, CHITRAKOOT",
    volunteerType: "field",
    preferredArea: "Rural development,livelihood,social development",
    financiallyIndependent: "Yes",
    sourceTimestamp: "2024/09/19 9:05:33 am GMT+5:30",
  },
  {
    fullName: "Dheeraj Tiwari",
    email: "dipalidheeraj95@gmail.com",
    mobile: "9372399973",
    gender: "Male",
    dob: "1995-02-18",
    city: "C/86 saidham apartment vastral ahmedabad gujarat",
    volunteerType: "field",
    preferredArea: "Gujarat",
    financiallyIndependent: "100",
    motivation: "Yes",
    sourceTimestamp: "2025/03/26 12:18:25 pm GMT+5:30",
  },
  {
    fullName: "Dipali dheeraj tiwari",
    email: "tiwaridipali514@gmail.com",
    mobile: "9712212076",
    gender: "Female",
    dob: "1996-11-10",
    city: "B/33 green park society vastral Ahmedabad",
    volunteerType: "field",
    preferredArea: "Vastral",
    financiallyIndependent: "1000",
    motivation: "Yes",
    sourceTimestamp: "2025/03/26 4:20:49 pm GMT+5:30",
  },
  {
    fullName: "Suraj Singh Advocate",
    email: "soorajsingh8588@gmail.com",
    mobile: "8826214261",
    gender: "Male",
    dob: "1999-04-04",
    city: "Chamber number 535, Surajpur District Court, Gautam Buddha Nagar, Uttar Pradesh 201306",
    volunteerType: "field",
    preferredArea: "Legal",
    motivation: "I want to be a part of your organisation and want to contribute through my legal knowledge and practice.",
    sourceTimestamp: "2025/03/27 11:07:37 am GMT+5:30",
  },
  {
    fullName: "ChamanRajora FBI",
    email: "chamanrajora@gmail.com",
    mobile: "8506003457",
    gender: "Male",
    dob: "2020-11-06",
    city: "House No 457/28 Faridabad Haryana",
    volunteerType: "field",
    preferredArea: "Faridabad",
    financiallyIndependent: "Yes",
    motivation: "Freelance",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/03/27 1:37:28 pm GMT+5:30",
  },
  {
    fullName: "Neeraj Dubey",
    email: "dubeyneeraj230@gmail.com",
    mobile: "07225900374",
    gender: "Male",
    dob: "1998-12-25",
    city: "Chitrakoot Satna Madhya pardesh",
    volunteerType: "field",
    preferredArea: "Social Work& Agriculture",
    financiallyIndependent: "Ok",
    motivation: "Education",
    sourceTimestamp: "2025/03/28 12:30:02 pm GMT+5:30",
  },
  {
    fullName: "Dhiraj Kumar",
    email: "dhirajsinght2@gmail.com",
    mobile: "9650160536",
    gender: "Male",
    dob: "1984-03-01",
    city: "Matri Park 2 Wagholi havali pune",
    volunteerType: "field",
    preferredArea: "Maharashtra",
    financiallyIndependent: "101",
    motivation: "Manav sewa",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/04/07 12:53:51 pm GMT+5:30",
  },
  {
    fullName: "Kiran Pandey",
    email: "shrirampandey586@gmail.com",
    mobile: "9993495877",
    gender: "Female",
    dob: "1984-07-01",
    city: "Ambedkar Nagar Pokhri tola Saman Rewa M. P.",
    volunteerType: "field",
    preferredArea: "Social Work",
    financiallyIndependent: "Yes",
    motivation: "Already join",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/05/10 9:30:50 am GMT+5:30",
  },
  {
    fullName: "Azad Singh Adhana",
    email: "Azad_Singh 007@yahoo.in",
    mobile: "9873913705",
    gender: "Male",
    dob: "1978-07-01",
    city: "K 601 Plumeriya Garden omicron III Greater Noida",
    volunteerType: "field",
    preferredArea: "UP",
    financiallyIndependent: "Yes",
    motivation: "Yes",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/05/12 2:42:36 pm GMT+5:30",
  },
  {
    fullName: "AMRITA SINHA",
    email: "asamritajee@gmail.com",
    mobile: "8588982966",
    gender: "Female",
    dob: "1983-12-01",
    city: "C67,Vishwas Park Uttamnagar Delhi",
    volunteerType: "field",
    preferredArea: "Teaching",
    motivation: "\"I want to become a volunteer of SSF because I have a strong desire to contribute meaningfully to society. I believe in giving back to the community and supporting causes that help improve the lives of others. Volunteering gives me an opportunity to be part of something larger than myself, to learn new skills, and to connect with people from different backgrounds. I also feel that working with SSF will help me grow personally while making a positive impact in the lives of those in need.\"",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/06/20 5:09:09 pm GMT+5:30",
  },
  {
    fullName: "Rakesh Kumar Sharma",
    email: "rakesh.pure2021@gmail.com",
    mobile: "9521772260",
    gender: "Male",
    dob: "1998-09-18",
    city: "Mahindra Wolrd City SEZ Kalwara Jaipur",
    volunteerType: "field",
    preferredArea: "Capacity Building and Life Skills Training NGO/CSR Project Management Program Implementation and Monitoring Women Empowerment and Entrepreneurship Development AI/ML & Cybersecurity Education for Underserved Communities",
    financiallyIndependent: "NA",
    motivation: "I want to become a volunteer because I am deeply committed to creating positive change at the grassroots level. With over 8 years of experience in the development sector—working on women empowerment, digital literacy, financial inclusion, and youth training—I’ve seen firsthand how small efforts can lead to meaningful transformation in people’s lives. Volunteering allows me to contribute my time, skills, and passion beyond professional roles, especially in underserved communities.\n\nIt also gives me an opportunity to stay connected with real issues on the ground, learn continuously, and be part of a larger movement for inclusive growth and social equity.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/07/17 3:20:20 pm GMT+5:30",
  },
  {
    fullName: "Dipali tiwari",
    email: "dipalitiwari911@gmail.com",
    mobile: "7049931253",
    gender: "Female",
    dob: "2007-05-20",
    city: "New bus stend",
    volunteerType: "field",
    preferredArea: "Ajad nagar",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/07/22 9:40:41 pm GMT+5:30",
  },
  {
    fullName: "Muskan sondhiya",
    email: "abhasondhiya86@gmail.com",
    mobile: "8817264368",
    gender: "Female",
    dob: "2008-07-20",
    city: "Azad nagar Rewa",
    volunteerType: "field",
    preferredArea: "Azad nagar",
    motivation: "Yes",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/07/25 9:05:46 pm GMT+5:30",
  },
  {
    fullName: "Hardik Chandrkant Gaikwad",
    email: "315hardiksvjc@gmail.com",
    mobile: "8928486280",
    gender: "Male",
    dob: "2003-10-04",
    city: "mankhurd mumbai",
    volunteerType: "field",
    preferredArea: "teaching and other",
    financiallyIndependent: "curretly not able to donate",
    motivation: "to contribute some thing to and towards society",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/08/28 1:08:32 pm GMT+5:30",
  },
  {
    fullName: "Ayushi tyagi",
    email: "tyagiayushi388@gmail.com",
    mobile: "9318352282",
    gender: "Female",
    dob: "2007-01-18",
    city: "Ghaziabad",
    volunteerType: "field",
    preferredArea: "Teaching",
    financiallyIndependent: "Yes",
    motivation: "To Give Back to the Community – “I want to contribute my time and skills to support others and give back to society.”",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/08/28 5:43:01 pm GMT+5:30",
  },
  {
    fullName: "Gayatri Duggal",
    email: "gayatriduggal9@gmail.com",
    mobile: "9769363956",
    gender: "Female",
    dob: "2003-06-17",
    city: "room No.602 Tower 20 Runwal Garden Manpada road Dombivli (east) 421004",
    volunteerType: "field",
    preferredArea: "Finance, Leadership, Management",
    financiallyIndependent: "I'm a student when i start working then i will definately donate",
    motivation: "I want to volunteer because it will help me learn teamwork, leadership, and communication skills. At the same time, I can support others in their learning and give back to the community.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/09/12 11:46:56 am GMT+5:30",
  },
  {
    fullName: "Vidushi Pal",
    email: "vidushipal633@gmail.com",
    mobile: "8057691579",
    gender: "Female",
    dob: "2002-08-30",
    city: "Vill Taimurpur Rawli Road Bijnor Bijnor (UP)",
    volunteerType: "field",
    preferredArea: "Areas near me",
    motivation: "I love to teaching profession",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/09/19 8:27:01 pm GMT+5:30",
  },
  {
    fullName: "Chanda singh",
    email: "Chanda.singh.pune@gmail.com",
    mobile: "8855915406",
    gender: "Female",
    dob: "1993-10-13",
    city: "Greater noida",
    volunteerType: "field",
    preferredArea: "Teaching",
    motivation: "I want to teach poor children because I believe education is the strongest tool to break the cycle of poverty and open doors to a better future.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/09/19 9:29:38 pm GMT+5:30",
  },
  {
    fullName: "Aparna Khanna",
    email: "Khannaaparna17@gmail.com",
    mobile: "9324292883",
    gender: "Female",
    dob: "1965-07-17",
    city: "31/701, Seawoods estates, Nerul, Navi Mumbai 400706",
    volunteerType: "field",
    preferredArea: "Teaching English and career counselling",
    motivation: "Have been volunteering since 2017. Being a teacher myself,  I feel happy to contribute in any way possible for a child’s education.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/09/22 11:56:08 am GMT+5:30",
  },
  {
    fullName: "Pavanethra M D",
    email: "pavanethramuthukumar@gmail.com",
    mobile: "6369709790",
    gender: "Female",
    dob: "2006-10-27",
    city: "Jansons institute of technology, karumathampatti, Coimbatore",
    volunteerType: "field",
    preferredArea: "English teaching and speaking",
    financiallyIndependent: "Yes",
    motivation: "I want to become a volunteer because it will allow me to develop new skills, gain experience, and grow personally while contributing to something meaningful.I believe in giving back to the community, and volunteering gives me an opportunity to support people who need help and make a positive difference in their lives.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/09/29 12:19:19 pm GMT+5:30",
  },
  {
    fullName: "Jeeva. S",
    email: "Dharveshg82@gmail. Com",
    mobile: "6383043483",
    gender: "Male",
    dob: "2005-02-08",
    city: "572,gandhi mahan street, kitchipalayam, salem.",
    volunteerType: "field",
    preferredArea: "Salem town",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/10/03 10:58:03 am GMT+5:30",
  },
  {
    fullName: "Naresh kumar",
    email: "nareshkumarkumar10494@gmail.com",
    mobile: "09971386388",
    gender: "Male",
    dob: "1983-10-04",
    city: "Palwal",
    volunteerType: "field",
    preferredArea: "Palwal",
    financiallyIndependent: "Yes",
    motivation: "Social activist",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/10/05 4:37:51 pm GMT+5:30",
  },
  {
    fullName: "Atul Pandey",
    email: "patul4909@gmail.com",
    mobile: "789816637",
    gender: "Male",
    dob: "1994-04-20",
    city: "Satna mp",
    volunteerType: "field",
    preferredArea: "satna",
    motivation: "Social work",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/10/08 12:50:43 pm GMT+5:30",
  },
  {
    fullName: "Siddhesh Ghag",
    email: "siddheshghag150@gmail.com",
    mobile: "7045221466",
    gender: "Male",
    dob: "2007-03-29",
    city: "Ciba society, amrut nagar , ghatkopar West , mumbai 400086",
    volunteerType: "field",
    preferredArea: "Web design and Development",
    motivation: "want to help make good website which make impact",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/10/17 3:33:46 pm GMT+5:30",
  },
  {
    fullName: "Naeem Shaikh",
    email: "nn9412466@gmail.com",
    mobile: "9598489890",
    gender: "Male",
    dob: "2002-07-15",
    city: "Kurla West, Mumbai 400070",
    volunteerType: "field",
    preferredArea: "Kurla",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/10/17 3:34:45 pm GMT+5:30",
  },
  {
    fullName: "Shubham yadav",
    email: "201134shubhamyadav@gmail.com",
    mobile: "7738326636",
    gender: "Male",
    dob: "2003-11-20",
    city: "Mumbra",
    volunteerType: "field",
    preferredArea: "Design and development",
    motivation: "I want to enhance my web development skill and gain experience by working on real project so I think it is perfect opportunity.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/10/17 4:12:26 pm GMT+5:30",
  },
  {
    fullName: "A.Gincy George",
    email: "Gincygin6@gmail.com",
    mobile: "8169688474",
    gender: "Female",
    dob: "1987-01-06",
    city: "Swastik house  A wing 901 , S.V road ,Kandivali  west 400067",
    volunteerType: "field",
    preferredArea: "Helping  in teaching and taking care of the sick",
    financiallyIndependent: "May be later",
    motivation: "Want to help others",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/11/07 12:02:37 pm GMT+5:30",
  },
  {
    fullName: "Pragya Asati",
    email: "asatipragya.11@gmail.com",
    gender: "Female",
    city: "Ramdaspeth Nagpur 440010",
    volunteerType: "field",
    preferredArea: "Teaching",
    motivation: "I want to keep in touch with challenges in India's education system on ground.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/12/05 10:36:01 am GMT+5:30",
  },
  {
    fullName: "Saniya Mohd Murtuza Shaikh",
    email: "saniashaikh54256@gmail.com",
    mobile: "9767054441",
    gender: "Female",
    dob: "2006-05-29",
    city: "1106-A wing, reliable prestige, Chandan Naka, Nalasopara East, 401209.",
    volunteerType: "field",
    preferredArea: "Website designing and development",
    motivation: "I would love to contribute to society in any kind of way that I can through my skills and knowledge.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/12/05 10:41:12 am GMT+5:30",
  },
  {
    fullName: "Samruddhi Pawar",
    email: "bmncollege.39@gmail.com",
    mobile: "8591541825",
    gender: "Female",
    dob: "2006-03-22",
    city: "C.B.D Belapur, Navi Mumbai",
    volunteerType: "field",
    preferredArea: "Website designing and development",
    motivation: "As I am interested in designing the website that will help the society to spread awareness of it..",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/12/05 11:02:22 am GMT+5:30",
  },
  {
    fullName: "Chandra Narayan Narayan",
    email: "Chandu528482@gmail.com",
    mobile: "98264380",
    gender: "Male",
    dob: "1995-08-16",
    city: "Raipur Chhattisgarh",
    volunteerType: "field",
    preferredArea: "Mova,saddhu ,kachna",
    motivation: "Like social  worker service,",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/12/05 12:42:48 pm GMT+5:30",
  },
  {
    fullName: "Dileep kumar verma",
    email: "dileepkkvv@gmail.com",
    mobile: "7974120569",
    gender: "Male",
    dob: "1998-09-30",
    city: "Transport nagar satna",
    volunteerType: "field",
    preferredArea: "Admin/ field support",
    motivation: "I want to volunteer in an NGO because I believe in giving back to society. This opportunity will allow me to help underprivileged people, develop new skills, and gain real-world experience while contributing to a meaningful cause.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/12/17 2:28:11 pm GMT+5:30",
  },
  {
    fullName: "Sneha Pandey",
    email: "sneharpandey67@gmail.com",
    mobile: "9321579581",
    gender: "Female",
    dob: "2005-12-12",
    city: "Gokuldham Society, First Floor -105, opp. RPS English High School, near piswali village, kalyan(E).",
    volunteerType: "field",
    preferredArea: "Web development",
    motivation: "I want to help ngo through my technical skills.",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/12/18 11:21:51 am GMT+5:30",
  },
  {
    fullName: "Vaishnavi Manik Chaudhari",
    email: "vaishnavi05chaudhari@gmail.com",
    mobile: "8879783548",
    gender: "Female",
    dob: "2005-12-05",
    city: "Aadarsh chawl no 2, Durga chowk, Manpada, Thane (W)-400 607",
    volunteerType: "field",
    preferredArea: "Web development",
    motivation: "To complete internship",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2025/12/21 7:09:41 pm GMT+5:30",
  },
  {
    fullName: "sakshi santosh chaudhari",
    email: "sakshichaudhari309@gmail.com",
    mobile: "7219369577",
    gender: "Female",
    dob: "2007-12-14",
    city: "thane",
    volunteerType: "field",
    preferredArea: "information technology",
    financiallyIndependent: "na",
    motivation: "for social help",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2026/01/23 7:50:20 pm GMT+5:30",
  },
  {
    fullName: "Mitten Mukherjee",
    email: "mittenm8@gmail.com",
    mobile: "8319306635",
    gender: "Male",
    dob: "1990-09-13",
    city: "H.no -33 , Bokaro Steel City Jharkhand",
    volunteerType: "field",
    preferredArea: "CSR / livelihood/MSME",
    motivation: "Xyz",
    declaration: "I hereby declare that I will abide by the rules, values, and code of conduct of Swastik Srijan Foundation. I understand that any unethical or inappropriate conduct will be my sole responsibility.",
    sourceTimestamp: "2026/01/24 4:42:29 pm GMT+5:30",
  },
  {
    fullName: "Ramesh Pandey",
    email: "rameshpandey335@gmail.com",
    mobile: "09718346691",
    city: "Pune",
    state: "Maharastra",
    volunteerType: "leadership",
    roleApplied: "National Level Honorary Role",
    preferredArea: "Health & Social Welfare",
    timeCommitment: "Less than 5 hours",
    financiallyIndependent: "Yes",
    experienceCapacity: "CSR proposal writing",
    contribution: "NA",
    fundraisingSupport: "Yes, directly",
    declaration: "I agree to work ethically and responsibly for the Foundation’s mission.",
    sourceTimestamp: "2026/01/25 12:36:10 am GMT+5:30",
  },
  {
    fullName: "Raj kumar",
    email: "Info@swastiksrijan.in",
    mobile: "9372711674",
    city: "Pume",
    state: "Maharastra",
    volunteerType: "leadership",
    roleApplied: "State Level Honorary Role",
    preferredArea: "Fundraising & Resource Mobilisation",
    timeCommitment: "Less than 5 hours",
    financiallyIndependent: "Yes",
    experienceCapacity: "Grant writing",
    contribution: "Yes",
    fundraisingSupport: "Yes, directly",
    declaration: "I am not expecting salary, commission, or financial benefit.",
    sourceTimestamp: "2026/01/25 1:47:44 am GMT+5:30",
  },
  {
    fullName: "Archana John",
    email: "archanajohnjbp@gmail.com",
    mobile: "9755010999",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    volunteerType: "leadership",
    roleApplied: "National Level Honorary Role",
    preferredArea: "CSR & Corporate Partnerships;Project Design & Management;Education & Skill Development;Health & Social Welfare;Women & Youth Empowerment;Documentation / Research / Reporting",
    timeCommitment: "More than 20 hours",
    financiallyIndependent: "No",
    experienceCapacity: "NGO project implementation",
    contribution: ". Large-Scale Project & Program Management \n• Skill Development & Livelihood Programs (DDUGKY / CSR / Govt Projects) \n• Stakeholder Management (Govt, Donors, Industry, NGOs) \n• Multi-State Operations & Cluster Management \n• Monitoring, Evaluation & MIS Reporting \n• Training Strategy, Workforce Development & Placements \n• Vendor & Partner Management \n• Compliance, Audits & Statutory Coordination \n• Leadership, Team Building & Performance Management",
    fundraisingSupport: "Possibly, through my network",
    declaration: "I understand that this is a purely Honorary / Volunteer role.",
    sourceTimestamp: "2026/02/02 2:13:25 pm GMT+5:30",
  },
  {
    fullName: "Basavaraj Dyamagond",
    email: "sanbassu@gmail,.com",
    mobile: "7760347603",
    city: "Bangalore",
    state: "Karnataka",
    volunteerType: "leadership",
    roleApplied: "State Level Honorary Role",
    preferredArea: "CSR & Corporate Partnerships;Project Design & Management;Education & Skill Development;Environment & Sustainability",
    timeCommitment: "5–10 hours",
    financiallyIndependent: "Yes",
    experienceCapacity: "NGO project implementation",
    contribution: "CSR Program Planning & Implementation\n\nCommunity Engagement\n\nNGO & Stakeholder Management\n\nCSR Project Coordination\n\nCorporate–NGO Partnerships",
    fundraisingSupport: "Possibly, through my network",
    declaration: "I agree to work ethically and responsibly for the Foundation’s mission.;I understand that this is a purely Honorary / Volunteer role.;I am not expecting salary, commission, or financial benefit.",
    sourceTimestamp: "2026/03/10 12:54:52 pm GMT+5:30",
  },
  {
    fullName: "Rohini Kumari",
    email: "rohikumari2504@gmail.com",
    mobile: "8851004090",
    city: "Solapur",
    state: "Maharashtra",
    volunteerType: "leadership",
    roleApplied: "Professional Volunteer",
    preferredArea: "Education & Skill Development",
    timeCommitment: "5–10 hours",
    financiallyIndependent: "Yes",
    experienceCapacity: "None of the above (learning stage)",
    contribution: "I have mentored and tutured earlier so would gladly like to work towards promotion of education, myself being an MBBS student understand the need for the same!",
    fundraisingSupport: "Not currently, but willing to learn",
    declaration: "I agree to work ethically and responsibly for the Foundation’s mission.",
    sourceTimestamp: "2026/03/13 9:07:45 pm GMT+5:30",
  },
  {
    fullName: "Santosh Tiwari",
    email: "santosht879@gmail.com",
    mobile: "8889991988",
    city: "Vidisha",
    state: "Madhya Pradesh",
    volunteerType: "leadership",
    roleApplied: "Professional Volunteer",
    preferredArea: "Education & Skill Development",
    timeCommitment: "10–20 hours",
    financiallyIndependent: "Yes",
    experienceCapacity: "NGO project implementation",
    contribution: "I am a Soft Skills & Personality Development Trainer. I believe in teamwork and some time to lead the team.\nI have 15 years of experience in education sector.\nI always eager to work for the betterment of the society.",
    fundraisingSupport: "Not currently, but willing to learn",
    declaration: "I agree to work ethically and responsibly for the Foundation’s mission.;I understand that this is a purely Honorary / Volunteer role.;I am not expecting salary, commission, or financial benefit.",
    sourceTimestamp: "2026/05/09 1:56:18 pm GMT+5:30",
  },
  {
    fullName: "Aryan Pandey",
    email: "aryanpandey8285@gmail.com",
    mobile: "7746805552",
    city: "Rewa",
    state: "Madhya Pradesh",
    volunteerType: "leadership",
    roleApplied: "Youth / Campus Coordinator",
    preferredArea: "Health & Social Welfare",
    timeCommitment: "5–10 hours",
    financiallyIndependent: "Yes",
    experienceCapacity: "NGO project implementation",
    contribution: "Na",
    fundraisingSupport: "Possibly, through my network",
    declaration: "I understand that this is a purely Honorary / Volunteer role.;I agree to work ethically and responsibly for the Foundation’s mission.;I am not expecting salary, commission, or financial benefit.",
    sourceTimestamp: "2026/05/16 6:37:49 pm GMT+5:30",
  },
  {
    fullName: "दिपक गंगाधर राजपुत",
    email: "Dr4821366@Gmail.com",
    mobile: "09834691770",
    city: "उमरेड",
    state: "महाराष्ट्र",
    volunteerType: "leadership",
    roleApplied: "Advisory Role",
    preferredArea: "Environment & Sustainability",
    timeCommitment: "5–10 hours",
    financiallyIndependent: "Yes",
    experienceCapacity: "None of the above (learning stage)",
    contribution: "I have knowledge about the environment who I can give it",
    fundraisingSupport: "Not currently, but willing to learn",
    declaration: "I agree to work ethically and responsibly for the Foundation’s mission.;I am not expecting salary, commission, or financial benefit.;I understand that this is a purely Honorary / Volunteer role.",
    sourceTimestamp: "2026/09/06 4:31:10 pm GMT+5:30",
  },
];

module.exports = { VOLUNTEER_IMPORT };
